### ISSUE TITLE
executing a bat file

### ISSUE THREAD

**Issue by alimeshgi** [qgis2web/qgis2web#1000]
Hello,
I have a question. So far I have successfully used qgis2web to create a web interface for visualizing the time series data of monitoring locations. So when a user clicks on a location, a link appears and clicking on that link allows the user to visualize the html file of that location. Now I want to check if this web interface can also be used to execute a "bat" file. In other words, when a user clicks on a monitoring location, a bat file for that location is executed. Is there a solution for this? Thanks in advance!

**Comment by boesiii** [comment]
Can you give an example of what the batch file will be doing?

**Comment by alimeshgi** [comment]
Hi, thank you very much for the reply. The batch file runs a python script for a monitor location. The Python script will then perform a calculation for that location and the output would be a graph for that monitoring location. So the idea is that, by clicking on a monitoring location in the web interface, the batch file will first run the python script for that location and then a graph will appear on the screen.
Here is the code in the batch file:

start cmd /k
call activate env
@SET drv1=%~n0
@SET drv2=%~n0
python cal.py %drv1% %drv2% 
pause

So my question is how can I do this and what command line should I add to "index.html" to connect the monitoring locations to the batch file.

Many thanks in advance for any advice!

**Comment by boesiii** [comment]
In general websites can't execute files locally.  If you have a server you should be able to accomplish your task using PHP.
