### ISSUE TITLE
Legend - groups not visible and categorised layers not editable

### ISSUE THREAD

**Issue by ikay711** [qgis2web/qgis2web#1001]
Hello, 

I am using the latest version of the plug-in. I am facing two issues with the legend:

1. I have layers put under different groups. However, when published, the grouping disappears and the layers are displayed without being under any groups.
2. For layers with categorised symbology, it is not possible to turn off/on the categories as we can do on QGIS. (image below)
![image](https://user-images.githubusercontent.com/93014052/175962816-9e6f1b59-b080-4e57-bc12-a20c1aa2369a.png)  

Is there any way to correct these and display as they are in QGIS?

Many thanks for the plug-in!

**Comment by andreaordonselli** [comment]
For openlayers layer group a solution is posted here #977

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
