### ISSUE TITLE
Geolocated pictures show full size and get truncated

### ISSUE THREAD

**Issue by xchido** [qgis2web/qgis2web#1003]
I have created a map and imported geolocated pictures. I have no issues with the map in QGIS it self all works great the pop-ups work great.

My issue is when I export the map with qgis2web I get the full size image (4003px) when I hover or click on the icon so it renders outside the screen. Is there a way to make it display at a reasonable size? at least one that does not crop the picture and the user can see what it is.

Windows 11, Chrome, Firefox, and Edge behave the same way. (all with latest updates)

**Using:** QGIS 3.22 with qgis2web 3.16.0 - exporting to leaflet

**ERRORS AND WARNING FROM THE CONSOLE F12**
_[Warning] Unexpected CSS token: : (leaflet.css, line 542)
[Warning] Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. (1) (leaflet.js, line 5)
(anonymous function) — leaflet.js:5:3232extend — leaflet.js:5:3241(anonymous function) — leaflet.pattern.js:6Global Code — leaflet.pattern.js:6:7078
[Error] Failed to load resource: Error opening C:/Users/jorge/AppData/Local/Temp/qgis2web/qgis2web_2022_06_28-15_57_12_847832/js/Autolinker.min.js.map: The system cannot find the file specified. (Autolinker.min.js.map, line 0)
[Error] Failed to load resource: Error opening C:/Users/jorge/AppData/Local/Temp/qgis2web/qgis2web_2022_06_28-15_57_12_847832/images/C__WIP_temp_heicimages: The system cannot find the file specified. (C__WIP_temp_heicimages, line 0)_

![Screenshot 2022-06-28 161651](https://user-images.githubusercontent.com/3813804/176320174-03a2be08-112a-41a3-a2fd-2d42b65a6137.png)
![Screenshot 2022-06-28 092715](https://user-images.githubusercontent.com/3813804/176320176-d9e141f2-78cf-4374-bcf7-fbbf3fd93e7e.png)
![Screenshot 2022-06-28 161758](https://user-images.githubusercontent.com/3813804/176320177-bd60783e-d9ff-4a16-8854-2808ad547c32.png)

**Comment by boesiii** [comment]
This page helped: https://gis.stackexchange.com/questions/258560/adjust-image-size-in-popup-to-fit-inside-popup-container

To fix this you will need to get your hands dirty and edit some HTML and CSS, specifically index.html and qgis2web.css

index.html
somewhere in the popupContent variable you will need to add 'class=popupImage'.
`.trim() + '" '+ 'class=popupImage' +'>' : '') + '</td>\`

qgis2web.css
at the bottom of the file
```
.popupImage {
    max-width: 100%;
    max-height: 100%;
}
```
100% will shrink the photo to fit within the popup so you can changes the percentages to get something you like.

**Comment by xchido** [comment]
TAHNK YOU!!!  I was able to make the changes and is working now!  Now have to remember to do this every time we add pictures! :

![Screenshot 2022-06-29 110619](https://user-images.githubusercontent.com/3813804/176506226-20c6dfa6-44a7-401d-a47c-c809a8923521.png)
)

**Comment by al-mackenzie** [comment]
I’ve followed the instructions above, and have set the % to 300% to get a suitable image display.  I can alter the %age to change the image size, but the popup box is staying the same (original) size.  Is there somewhere else to change the popup box size?

**Comment by tomchadwin** [comment]
@al-mackenzie The 100% refers to the width of the picture as a percentage of the width of the popup. Change it back to 100%, and then you'd have to figure out how to add another CSS rule to increase the size of the popup itself (I don't have that info to hand, I'm afraid).

**Comment by andreaordonselli** [comment]
I have just released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
