### ISSUE TITLE
Geotif Not Displaying

### ISSUE THREAD

**Issue by badshah424** [qgis2web/qgis2web#1008]
Hi I am using a geotif image in QGIS and trying converting it to offline with QGIS2WEB plugin .

But nowhere I'm getting options for Raster map and as a result my web map is not having the geotif file anywhere .

Basically I want to create a offline map with layers. One of the layers being Raster of geotif.

Please help.

**Comment by boesiii** [comment]
Are you able to share a sample of your geotif?  Maybe its a coordinate system issue.
