### ISSUE TITLE
Collapsible sections in the legend

### ISSUE THREAD

**Issue by cinthiaishida** [qgis2web/qgis2web#1016]
When we use OpenLayers, we can have a collapsible section for a group of layers, but it's not possible to create a collapsible section for different groups (as a hierarchy). I wonder if there is a solution to more options of collapsible sections in the legends? It would work for maps with many layers to have the information more organized.

**Comment by andreaordonselli** [comment]
Can this help?
https://github.com/tomchadwin/qgis2web/issues/977

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
