### ISSUE TITLE
Publish to web using leaflet timeline control

### ISSUE THREAD

**Issue by wstaelens** [qgis2web/qgis2web#1021]
How can I get leaflet timeline working with this timeline control: https://skeate.dev/Leaflet.timeline/examples/earthquakes.html ( https://github.com/skeate/Leaflet.timeline )

Qgis3.28 project has different grouped layers. The layers have temporal control.
The backgroundmap is XYZ tiles OpenStreetMap.

I've tried https://github.com/ruz76/qgis2web_time_extension but it doesn't seem to do anything. If I look into the plugin source the code is already there but doesn't seem to work:

from time extension:
````
To activate extension you have to copy ui_timedialog.py to plugin and add two lines of code to ui_maindialog.py

A. in header

from ui_timedialog import Ui_TimeDialog #time

B. in setupUi place after

self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

this line

uitime = Ui_TimeDialog(self.tabWidget, MainDialog) #time

This will place the Time Tab at the end of the list of tabs. If you want to place it after tab Export than place the code after self.tabWidget.addTab(self.tab, _fromUtf8("")).
````

**Comment by andreaordonselli** [comment]
Please ask your question in gis.stackexchange.com, here in github ask questions about current/future qgis2web features. Thanks.
