### ISSUE TITLE
Popups fields not showing in main window

### ISSUE THREAD

**Issue by basize2-0** [qgis2web/qgis2web#1028]
Greetings everyone, 

I just downloaded qgis2web with QGIS 3.30 Hertenbosch. 
I have an issue with the main window as it only shows the Visibility and Popups section for each layer. This cause my web application to not display the vector data but only the shape of it. None of those shapefiles are hidden.
Has someone encountered this problem ?

Here is a screenshot of my window.
![Capture d’écran du 2023-03-19 15-32-21](https://user-images.githubusercontent.com/128304798/226182919-3bf79b06-5a0c-4db8-a28c-df6e1828fd7c.png)

Best,
FB

**Comment by tomchadwin** [comment]
This is because your layers are in layer groups, which are very poorly supported in qgis2web. Layers not in layer groups can be properly conmfigured.

**Comment by basize2-0** [comment]
Thank you very much !

**Comment by andreaordonselli** [comment]
For openlayers layer group a solution to create a legend with groups is posted here https://github.com/tomchadwin/qgis2web/issues/977
