### ISSUE TITLE
How to reduce information in Pop-up 

### ISSUE THREAD

**Issue by juanmiguelgomez** [qgis2web/qgis2web#1035]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by juanmiguelgomez** [comment]
Hello!!
As you can see in the image, when I am not able to reduce the values of fields in popup. Actually, I expected to show only two. However, all of them are shown. Then, the only options ir seems I have are both: or showing all the field or showing no one. 
Is it possible to show two or three fields (values of them) instead?

![image](https://github.com/tomchadwin/qgis2web/assets/134065564/d201a80f-4b76-4606-a6de-c6ba1220cbc2)

Thank you very much. Regards.

**Comment by andreaordonselli** [comment]
Hi, as you can see in this [tutorial](http://www.qgistutorials.com/it/docs/web_mapping_with_qgis2web.html)  you can define, in Qgis, the properties of your layers as `hidden` and these will not be exported by qgis2web.
Let me know if you solved it.

**Comment by jmgomesp** [comment]
Hi, again, and thank you for your quick answer. 

Sorry, but in v. 330.02 (Spanish) interface is not similar. 

![image](https://github.com/tomchadwin/qgis2web/assets/135820268/85c6d0ec-18ef-487c-b502-885a684ef793)

Anyway, I have changed these parameters and it does not work. . I suppose that I have to change something (some order) in qgis2web.js file or another file but I do not know what exactly.  
 
Tutorial says "In your computer, go to the folder where the web map was exported. Locate the resources folder and open qgis2web.js file in a text editor (...)" but I do not understand what to do. Hopefully, you could help me. 

Thank you a lot, again. Regards. JM.

**Comment by andreaordonselli** [comment]
The menu item corresponding to the guide is the following
![Inkedunnamed_LI](https://github.com/tomchadwin/qgis2web/assets/89784373/7f34688d-aeaa-4143-8f3b-8a95186a6847)

Then
![image](https://github.com/tomchadwin/qgis2web/assets/89784373/178e1b2f-6886-4c70-aea7-437715a1f0e5)

**Comment by PascaleBVVB91** [comment]
Hi, 
I can't find this menu and don't understand how to set it
Thank you by advance
![image](https://github.com/tomchadwin/qgis2web/assets/149181424/143f142f-9dac-4546-8d3f-d99020dfbe09)

**Comment by andreaordonselli** [comment]
In your screen click on any field to select it, like: fid, photo, filename, directory, altitude etc...

After selection, you will see the options appear on the right screen as per my previous screenshot

**Comment by PascaleBVVB91** [comment]
@andreaordonselli Thank you ! I found the right screen as you shaw :-)
