### ISSUE TITLE
Export/preview map empty/blank without error

### ISSUE THREAD

**Issue by MatisseBE** [qgis2web/qgis2web#1044]
Hi, 
The preview and export of my map is blank with this data source. I have used different geojson files and those work fine, unfortunuately the one I need to use, does not - and frankly, I don't see any difference with the working files, let alone an issue with it! 

It is driving me crazy! 😣
![image](https://github.com/tomchadwin/qgis2web/assets/51272243/1862dba6-7a54-44dc-aad2-060a5541655a)

Data source: https://drive.google.com/file/d/1mw7f3uo0DWJZsXPoxo-rgZooK-5Ltk94/view?usp=sharing

**Comment by Juhunnm** [comment]
I'm going through the same situation right now. I used it about a month ago, but now I'm having a problem with rendering not working. The project I'm visualizing is right in front of me, so it's a big deal.

**Comment by andreaordonselli** [comment]
Can you provide more precise information regarding the problem by attaching the data that generates the error so that we can reproduce the problem?  It would also be useful to know your OS, the qgis version, the qgis2web version and also have some screenshots.  Thank you.
