### ISSUE TITLE
Relative path attachment widget not working

### ISSUE THREAD

**Issue by yvarmareveal** [qgis2web/qgis2web#1045]
qgis accepts the correct value for the default attachment location (image) from the Attribute Form -> Attachment -> Default Path field. 

However, the moment a web map using this plugin is created (with leaflet selected), the default path reverts to AppData/Local/Temp/qgis2web/.

I am unable to find a config file or any settings location within qgis2web to change the default, or atleast inherit it from the qgis value.
![qgis-web](https://github.com/tomchadwin/qgis2web/assets/139561959/e7cc7050-8c5c-4c56-8421-372222cbfe33)
![qgis-settings](https://github.com/tomchadwin/qgis2web/assets/139561959/08f0b540-7db6-4c28-92ba-46109e766190)

**Comment by andreaordonselli** [comment]
Relative path does not allow qgis2web to work correctly.
You must use an absolute path without changing the widget values.
Therefore in your layer field you will have to indicate the absolute path to the image.
I attach an example.
[qgis2web_example_image_in_popup.zip](https://github.com/qgis2web/qgis2web/files/13659419/qgis2web_example_image_in_popup.zip)

![image](https://github.com/qgis2web/qgis2web/assets/89784373/01cd1297-c354-408b-8e5a-26fd3c1c5f25)

**Comment by yvarmareveal** [comment]
@andreaordonselli I tried your example and it looks like on the Leaflet preview, it keeps defaulting to a path that starts with file:///C:/Users/<username>/AppData/Local/Temp/ 
even when a different absolute value is selected (even in your example) do you know if there is a place to change this default? Perhaps it is a Leaflet plugin issue. Thanks

**Comment by andreaordonselli** [comment]
In QGIS, you can set images as shown in my screen (with the complete file path). During preview/export, qgis2web works by taking those images from those paths and placing them in its own "images" folder of preview/export, duplicating your original images. Therefore, qgis2web becomes independent from the original path of your images, working as a standalone entity. It does this to provide the user with an export ready for online publishing. Let me understand your concerns; would you like the web map to point to the original path of your images after the preview/export?
