### ISSUE TITLE
Announcement: repository transferred

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#1046]
After @andreaordonselli's incredibly kind offer to work on qgis2web, I've moved the repo out of my @tomchadwin account. I've created a new @qgis2web organization, and moved the repo there. Please let us know if you face ny problems - if you have clones, make sure they point at this new upstream origin.

**Comment by andreaordonselli** [comment]
Thanks @tomchadwin, I am grateful to provide my support to the project.

**Comment by tomchadwin** [comment]
I am even more grateful for all your work, @andreaordonselli. Thank you!
