### ISSUE TITLE
Popup options not showing up

### ISSUE THREAD

**Issue by jkat510** [qgis2web/qgis2web#1047]
Popup options are not showing up. The space for them is there, so I think it's an option displaying them. I am pretty sure it is not a problem with my layers because they were working with the plugin yesterday. I tried reinstalling qgis2web and the issue remained.

Yesterday when everything was working, I set inline labels for one of my layers, and those are still showing up. I want to add inline labels to the other layer, but cannot.

<img width="960" alt="Screenshot 2023-12-14 113218" src="https://github.com/qgis2web/qgis2web/assets/73307344/ee78c0e8-faf6-43a0-a495-7beb284c5ee6">

**Comment by andreaordonselli** [comment]
your layer name is very long so the options have moved to the right.  You can see in your screenshot that the window has a scroll bar at the bottom.

**Comment by jkat510** [comment]
Wow do I feel silly! Thanks so much.

**Comment by andreaordonselli** [comment]
If qgis2web satisfies you, please consider donating a coffee on the github home page, thanks.
