### ISSUE TITLE
Exporting dashed or dotted line

### ISSUE THREAD

**Issue by danieljuschus** [qgis2web/qgis2web#1048]
It seems that it's not possible to export a dashed or dotted line (i.e. a line of the type `Simple Line` with a `Stroke style` other than `Solid Line.`)? See below the side-by-side comparison between the exported result and QGIS.

![image](https://github.com/qgis2web/qgis2web/assets/26310238/384e5b3b-16d8-44ae-9207-0177216a2019)

I'm using qgis2web 3.17.2.

_Previously Issue
#571 #572_

**Comment by andreaordonselli** [comment]
Good evening @danieljuschus 
I ran some tests and report line style results that can be implemented with both openlayers and leaflet export, can they meet your expectations? 

The difference between qgis and export is minimal, perhaps the scale could be adjusted slightly but the result is good. I believe that by using different thicknesses and colors already with these examples it is possible to differentiate the data visible on the map well. What do you think?

Dot lines
![dot lines](https://github.com/qgis2web/qgis2web/assets/89784373/24882a83-527b-4f4b-9348-046712b98685)

Dash lines
![dash lines](https://github.com/qgis2web/qgis2web/assets/89784373/163c2e40-8066-4e7c-b9b2-66c0bc21fe9c)

Black dash and red dot lines
![black dash lines and red dot line](https://github.com/qgis2web/qgis2web/assets/89784373/90b54f18-3958-4b04-b0b9-18a016be4100)

Multiple simple line
![multiple simple line](https://github.com/qgis2web/qgis2web/assets/89784373/3861ba81-c111-4a09-ab07-c9d05f68efad)

**Comment by danieljuschus** [comment]
The problem emerges with thicker lines. I need to use those because I'm drawing over OSM tiles.

Here's what a `Dot Line` with a `Stroke width` of 3mm looks like in the editor:

![image](https://github.com/qgis2web/qgis2web/assets/26310238/31456e21-493e-4e6c-abef-13bfe7a14b02)

The exported result:

![image](https://github.com/qgis2web/qgis2web/assets/26310238/881694fd-46bc-4a11-8fe3-2a2871d9e898)

When changing the parameter `lineDash` of the layer style js file from `[1,5]` to `[10,20]`:

![image](https://github.com/qgis2web/qgis2web/assets/26310238/5ef927c9-f77d-4c93-b9fe-7def8eb1b3d6)
 
So perhaps we would need to figure out a better mapping between the QGIS and OL parameters?

**Comment by tomchadwin** [comment]
@danieljuschus I would avoid print-based units - `mm` have no meaning on screen. Pixels is definitely sfest. There is some code in there to try to handle map units, but I cannot remember how reliable it is. I'm not saying switching to pixels will fix the issue, but that's where I'd start.

**Comment by andreaordonselli** [comment]
I should have managed to fix everything for openlayers export.
@danieljuschus Can I ask you to run some tests?
I'll leave you the [file](https://github.com/qgis2web/qgis2web/files/13794074/olStyleScripts.zip) to replace in this folder for windows sistem:
C:\Users\your_user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis2web 
Make a backup copy of the existing file.

The new version fixes:
- line width with decimals (previously there was an approximation to the whole number)
- stroke length and space length based on line width (both for dotted line, dashed line, and dash/dot line)
- separate definitions for lines or outer lines of polygons

![2023-12-29 15_06_37-NVIDIA GeForce Overlay](https://github.com/qgis2web/qgis2web/assets/89784373/497c70d0-a430-4413-88c7-85c99bd71dfb)

![2023-12-29 15_06_53-NVIDIA GeForce Overlay](https://github.com/qgis2web/qgis2web/assets/89784373/a338ea58-3cf8-4df4-adb5-f1427d6a2ff0)

![2023-12-29 15_07_59-NVIDIA GeForce Overlay](https://github.com/qgis2web/qgis2web/assets/89784373/46b9151d-77bc-4f04-95ab-b705c7f7b7eb)

**Comment by danieljuschus** [comment]
That seems to work perfectly now, thank you!

**Comment by andreaordonselli** [comment]
Thanks for the test.  Soon I will commit to github and publish the new version also in the QGIS plugin repository.  Kindly consider donating a coffee to support the project.  You can do this via the button on the home page.  Thank you.

**Comment by andreaordonselli** [comment]
Released version [3.17.3](https://github.com/qgis2web/qgis2web/releases/tag/v3.17.3) which includes a fix for this issue. The update will be available soon from the QGIS plugin repository. Thanks for the tip.
