### ISSUE TITLE
Overlapping polygons do not show on web report

### ISSUE THREAD

**Issue by Romarinho99** [qgis2web/qgis2web#1050]
Hello,
Two features from the same layer do not show on the web report regardless if I am using Leaflet or Openlayers for the export.
The overlapping feature shows in the project like this
![Screenshot from 2024-02-13 20-00-48](https://github.com/qgis2web/qgis2web/assets/114056982/6422adae-09b4-4abd-aced-5188994e2884)

But disappear in the preview and final export when creating the webreport like below

![Screenshot from 2024-02-13 20-04-38](https://github.com/qgis2web/qgis2web/assets/114056982/1e38d051-3960-48c3-8112-7f4d7e9ae7f0)

I check on other QGIS project and it seems that the export does not show overlapping polygons on the other projects too. I did not see this issue being raised, am I the only one getting it ?

Thank you in advance

**Comment by andreaordonselli** [comment]
Overlapping features in the same layer usually have no problems. 
If you want to send a zip with your data I'll try to understand the problem

OpenLayers export
![image](https://github.com/qgis2web/qgis2web/assets/89784373/6e169379-70a8-4957-8b00-aca858978334)

Leaflet export
![image](https://github.com/qgis2web/qgis2web/assets/89784373/03bf3d32-db28-4b9c-991f-3713c1a380c0)

**Comment by Romarinho99** [comment]
Hello,

Thanks for your prompt response.

I just noticed that converting the files into shapefiles works. Which solved my problem ! Nor geojson (which was the original format) and GeoPackage worked, I am wondering if the same would happen on your side if you converted your example into geojson.

I send you a modified version where I removed sensitive data and gave you three versions of the same polygons in the different formats. On my side only the shapefile displays the overlaps.

[QGIS2WEB_debug.zip](https://github.com/qgis2web/qgis2web/files/14276999/QGIS2WEB_debug.zip)

Have a nice day

**Comment by Romarinho99** [comment]
Hello Andrea,
Thanks for your prompt response. I just found the issue and it is vicious in this case.

In short, it is not a geometrical issue of overlap. QGIS2WEB does not support attributes in list/array format.

On all my projects I am working with agricultural parcels where I report about the quality of the parcel polygons data. 
One of the attribute is a list all the other polygons with which a feature overlaps (NULL otherwise if no overlap).

So in the end, maybe due to the fact that the pop ups cannot be created with list attributes, the polygons that did not overlapped were displayed correctly because their "list of overlap" attribute was NULL.


I close this discussion. Thank you again

**Comment by andreaordonselli** [comment]
Thanks to you.
I kindly ask you to consider donating a virtual coffee to support the development of qgis2web; you can do it via the button on the home page.
Good day.
