### ISSUE TITLE
Qgis2web crashes in different computers and with different qgis versions and projects

### ISSUE THREAD

**Issue by Dorexplor** [qgis2web/qgis2web#1051]
Good afternoon,
 I have been trying since several days to export a map with Qgis2web but every time I try it the plug in an the programme crash. Few months ago I used this plug in and it perfectly works but now it always crashes. I have uninstalled Qgis and reinstall different versions in my computer and I also install the latest version of the plug in but this problem persists. I leave a copy of the error report below and screenshots of the qgis2web settings used. Thank you in advance.

 ## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000eec (most recent call first):
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 253 in exportVector
    e, err = QgsVectorFileWriter.writeAsVectorFormat(cleanLayer, tmpPath,
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 231 in exportLayers
    exportVector(layer, sln, layersFolder, restrictToExtent,
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 130 in writeOL
    exportLayers(iface, layers, folder, precision, optimize,
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 81 in write
    self.preview_file = self.writeOL(iface, feedback,
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 345 in createPreview
    return writer.write(self.iface,
  File "C:\Users/Florencia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 383 in previewMap
    preview_file = self.createPreview()
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

Screenshots of Qgis2web settings:

![image](https://github.com/qgis2web/qgis2web/assets/95230986/90d8352a-b534-4097-afba-d05610d02c34)
![image](https://github.com/qgis2web/qgis2web/assets/95230986/ae3b0b3c-596a-4653-8d27-ef3889e65269)
![image](https://github.com/qgis2web/qgis2web/assets/95230986/d035e5f0-bfbb-4392-8682-df914ad1e37c)

**Comment by andreaordonselli** [comment]
Please attach your data.
Ps: groups are poorly supported, you should try exporting layers by extracting them from groups.

**Comment by andreaordonselli** [comment]
In version [3.25.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.25.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
