### ISSUE TITLE
QGIS2web keeps failing with python errors

### ISSUE THREAD

**Issue by azstumbler** [qgis2web/qgis2web#1053]
Qgis2web will not return anything, it fails without generating any type of output. I have tried ti with some maps I have use it on previously without any issue and they are now failing. I have also used it with other computers, all with QGIS 3.36.0 and they all failed. I have tried it with older versions on QGIS and versions of qgis2web and it would work just find.

The information below was using a single feature map one with a polygon and another with just a line layer.  

QGIS 3.36.0
qgis2web 3.18.2
![stack trace qgis2web](https://github.com/qgis2web/qgis2web/assets/498477/aae7f4c7-1297-4d46-a74c-ee4273a4fc0e)
[python error tab.txt](https://github.com/qgis2web/qgis2web/files/14564420/python.error.tab.txt)

**Comment by andreaordonselli** [comment]
Can you attach your data in a zip?

Another user told me that qgis2web doesn't work with the latest version of QGIS, but I still have to investigate.
It certainly works with the LTR 3.34 version.

**Comment by azstumbler** [comment]
I can verify that it does not work in the LTR 3.34 as that was one of the versions that I tried the current release of qgis2web and a previous release.
Shapefile of the 2 layers I tried it with is attached.

    On Monday, March 11, 2024 at 02:08:59 PM MST, Andrea Ordonselli ***@***.***> wrote:  
 
 


Can you attach your data in a zip?

Another user told me that qgis2web doesn't work with the latest version of QGIS, but I still have to investigate.
It certainly works with the LTR 3.34 version.

**Comment by andreaordonselli** [comment]
Attaching files via email doesn't work. you should create a zip file and upload it to the github discussion. Thank you.

**Comment by agiudiceandrea** [comment]
@andreaordonselli, the symbollayer color property value  is something like '190,178,151,255,rgb:0.74509803921568629,0.69803921568627447,0.59215686274509804,1'
See https://api.qgis.org/api/qgsfillsymbollayer_8cpp_source.html#l00355, https://api.qgis.org/api/qgscolorutils_8cpp_source.html#l00192

**Comment by azstumbler** [comment]
The 2 shp files were in one zip file

**Comment by andreaordonselli** [comment]
something is happening that doesn't allow you to attach, I still don't see the zip you upload.  send it to me by email info@opengis.it
Thanks

**Comment by tomchadwin** [comment]
> @andreaordonselli, the symbollayer color property value in QGIS 3.36 is something like `'190,178,151,255,rgb:0.74509803921568629,0.69803921568627447,0.59215686274509804,1'` while the plugin expect it as `'190,178,151,255'` 

Is this a QGIS breaking API change, @agiudiceandrea?

**Comment by andreaordonselli** [comment]
by applying a simple style to the two levels qgis2web has no problems exporting.

openlayers:

![image](https://github.com/qgis2web/qgis2web/assets/89784373/7f231ff5-8d6a-4069-80c9-f133e9246488)

leaflet:

![image](https://github.com/qgis2web/qgis2web/assets/89784373/ba7d7fa7-86ee-4f22-b72d-2a886bc3efbe)


What styles are you applying? can you export your styles in the following way and send them to me?

![image](https://github.com/qgis2web/qgis2web/assets/89784373/7624e559-bf55-4b28-b484-3618fccabc0d)

**Comment by agiudiceandrea** [comment]
> > @andreaordonselli, the symbollayer color property value in QGIS 3.36 is something like `'190,178,151,255,rgb:0.74509803921568629,0.69803921568627447,0.59215686274509804,1'` while the plugin expect it as `'190,178,151,255'`
> 
> Is this a QGIS breaking API change, @agiudiceandrea?

@tomchadwin, see: https://github.com/qgis/QGIS/pull/55718#issuecomment-1990698881 and subsequent comments.

**Comment by andreaordonselli** [comment]
Thanks for your advice, I solved it by acquiring only the first 4 values ​​and this will work with the old and new qgis.
can it be okay?

```python
def getRGBAColor(color, alpha):
    r, g, b, a = color.split(",")[:4]
    a = str(float(a) / 255 * alpha)
    return "'rgba(%s)'" % ",".join([r, g, b, str(a)])
```

**Comment by tomchadwin** [comment]
Looks good to me. Thanks!
