### ISSUE TITLE
Learning how to contribute

### ISSUE THREAD

**Issue by lecneri** [qgis2web/qgis2web#1057]
Hello,

A friend want to contribute with the project because he faced some hardtime accessing mobile, but not sure how to quite do it. And asked me to help.
He downloaded [dist version 3.20.1](https://github.com/openlayers/openlayers/releases/download/v3.20.1/v3.20.1-dist.zip) of openlayers.org and replaced ol.js and ol.css of resources folder.
Because of it, he had to alter resources/ol-layerswitcher.js at line 300
FROM 
var descendantVisibility = group.getLayersArray().map(function (l) {
To
var descendantVisibility = group.getLayers().getArray().map(function (l) {
We'd like to know how can we submit and contribute to this project doing this modification, and doing a PR

**Comment by andreaordonselli** [comment]
Thank you for wanting to contribute to the project.
The guide to create a pull request is officially explained by github here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull -requests/creating-a-pull-request

In any case it doesn't seem like a good idea to replace the current version of openlayers with an older one.
With this commit openlayers is at version 6.4.3:
https://github.com/tomchadwin/qgis2web/commit/533eaba21bf6f3329f577ff083a2beae740a3f96

What we need to do is go from version 6 to version 9, not go back to 3
Thank you
