### ISSUE TITLE
UKHab Style Sets Not Working

### ISSUE THREAD

**Issue by macavitythemysterycat** [qgis2web/qgis2web#1058]
Hi guys,

I'm an ecologist using a standard polygon and linear style set created by UKHab (with a few additions of my own where habitats are missing). I've found two slightly different issues here:

a) Leaflet - The sets work fine, but none of the basemaps load
b) OpenLayers - The basemaps work fine, but I can only load the layers without styles

I suspect it's something to do with the fills, but unfortunately we need these to appear exactly as they are because it's a standard key!
I've attached a couple of screenshots and a copy of the error readout. Let me know if you need a copy of the style sets (I can't attach them below as the file types aren't supported). 

[Error readout.docx](https://github.com/qgis2web/qgis2web/files/14882695/Error.readout.docx)
![Screenshot (887)](https://github.com/qgis2web/qgis2web/assets/166114511/ecc0def9-8a48-4e5b-abec-37d221420bff)
![Screenshot (888)](https://github.com/qgis2web/qgis2web/assets/166114511/6c976041-53c5-4a53-a185-7b4f291acd46)

**Comment by andreaordonselli** [comment]
To attach unsupported files, include them in a zip.
I would need the base layers that do not appear in leaflet;  And styles and data that don't work in Openlayers.
Thanks

**Comment by macavitythemysterycat** [comment]
Thanks Andrea! Style sets attached.

The basemaps I have been using are:

Google Satellite (I have tried adding this using both HCMGIS Basemaps and QuickMapServices)
OSM Standard (QuickMapServices)
OS OpenData StreetView (QuickMapServices)
Esri Light Gray (HCMGIS Basemaps)

Vic


________________________________

**Comment by andreaordonselli** [comment]
I've looked at your styles and they're really complex. I understand you can't change them as they default to UKHab classification, but qgis2web can't export them.
Leaflet finishes the export but I don't think the final map shows the complete styles.
To insert the base maps I recommend inserting them as an XYZ level.
An example:
openstreetmap: https://tile.openstreetmap.org/{z}/{x}/{y}.png
google satellite: http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}

I hope to be able to expand the exportable styles in the future.

**Comment by macavitythemysterycat** [comment]
Thanks Andrea!
Much appreciated.

Vic

**Comment by macavitythemysterycat** [comment]
Ah, the XYZ tiles option doesn't seem to be working (and I've just done some investigating, it doesn't appear to be supported by the more recent versions of QGIS any more). Do you have another suggestion that might work for qgis2web?

Vic
________________________________
From: Vic Standing ***@***.***>
Sent: 06 April 2024 07:59
To: qgis2web/qgis2web ***@***.***>
Subject: RE: [qgis2web/qgis2web] UKHab Style Sets Not Working (Issue #1058)


Thanks Andrea!

Much appreciated.



Vic

**Comment by andreaordonselli** [comment]
I assure you that XYZ layers are supported and work.
Watch this [Video](https://www.youtube.com/watch?v=ht7tgmuwkpA) to add them.

Attention: based on your project coordinate system, you may need to select "match project crs" in the appearance tab
![image](https://github.com/qgis2web/qgis2web/assets/89784373/b2e6a9c2-71c4-42b4-be79-47fa6c54c41d)

**Comment by macavitythemysterycat** [comment]
Hi Andrea,

I've installed the plugin successfully but this is the message I get in QGIS, and so far it hasn't successfully exported any tiles.

Vic

________________________________

**Comment by andreaordonselli** [comment]
Explain better please. Show me with screenshots how you are adding the xyz levels so I can understand why the export isn't working for you.
