### ISSUE TITLE
max-height of popup-content

### ISSUE THREAD

**Issue by JanKirchhoff** [qgis2web/qgis2web#1061]
viewport-width (vw) is used in multiple places where viewport-height (vh) would be more appropriate.

I changed max-height of popup-content to 90vh in [openlayers/qgis2web.css](https://github.com/JanKirchhoff/qgis2web/commit/219f95863ea608bdc26610b9df6cef71aaa57be2#diff-16b87e21eb063a87918826bf5de732598e2dd10c902c08abe3ee862f1993352b)

More fixes in the openlayers and leaflet css are needed.

I also changed the max-width of pop-content to 70vw. This allows for easy closing of the popup by clicking on uncovered space in my test with typical smartphone resolution.

**Comment by andreaordonselli** [comment]
You are right about vh defined for height. Thank you.
I will bring the update in the next release.
As far as the maximum size is concerned, I don't want too much height to overlap with icons or anything else.
For now I prefer to opt for a middle ground between 50 and 90, so I will set 70vh and 70vw at the popup.

**Comment by andreaordonselli** [comment]
I have just released version [3.20.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.20.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
