### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by SifisoManyala** [qgis2web/qgis2web#1062]
I am trying to create a web map using qgis2web plugin. I get the following error. I am not versed in Python so I have no idea how to pinpoint the layer that might be a problem. 

I am not sure how I can share my project data for someone to help me directly. 
https://dmtza.sharepoint.com/:f:/g/EsVNHmzCQ2dGlmMNPVSv8xUBKzKZj3YdDv8VML7FNXzDvg?e=ZJuJkT

<img width="811" alt="Screenshot 2024-04-25 140056" src="https://github.com/qgis2web/qgis2web/assets/133858901/1a457bf3-43b4-4949-b08e-1ea293a6e131">

To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by andreaordonselli** [comment]
Hello, QGIS is making some changes and I'm updating qgis2web accordingly to allow it to export data well. I therefore ask you to perform the exports with the latest LTR version of QGIS (it is now 3.34).
Please run tests on both exports, openlayers and leaflets, which sometimes behave differently on the symbologies. Also remember that when using complex symbols you do not have to check "Cluster" if you have point layers.
Let me know if you still encounter problems, if so please attach your project in the most streamlined form possible. Include a few data and the .qgz in a zip.
Thank you.
