### ISSUE TITLE
Blank preview and map

### ISSUE THREAD

**Issue by EricMaGo** [qgis2web/qgis2web#1064]
Hey!

I'm trying to export a map (a single layer with two rules) and the preview and the resulting map are empty.  

![qgis](https://github.com/qgis2web/qgis2web/assets/19272495/4e22233a-c9c0-4eda-ae25-f629a1afd4be)  
  
Any idea on how to resolve the issue? The plugin is already in the latest version and I've tried to reinstalled it and to restart the program and computer.

Thank you!

**Comment by andreaordonselli** [comment]
See the WIKI for supported styles https://qgis2web.github.io/qgis2web/#SetStyles
If you can't solve it, send your project in a zip.
Thank you.

**Comment by EricMaGo** [comment]
The layer shows ok, this is not the issue. What doesn't show is the map underneath, in this case, leaflet

**Comment by andreaordonselli** [comment]
What style are you using? Categorized, with expressions, graduated?
You should also post the error you find in the browser console. Otherwise I can't help you.

**Comment by EricMaGo** [comment]
Sorry, I'm very newbie at QGIS but the issue appears even when I don't load any layer and only ask for the background map  
  
![Screenshot from 2024-05-09 09-58-18](https://github.com/qgis2web/qgis2web/assets/19272495/0db7f72f-214d-4b8a-a64a-a3ea3fa75fca)

**Comment by andreaordonselli** [comment]
It is normal for the preview to be white and empty if you do not insert layers into the project.
If you are a beginner you could make your way with this guide which I consider complete https://www.qgistutorials.com/en/docs/3/web_mapping_with_qgis2web.html
