### ISSUE TITLE
WMS Map from geoportale.regione.lazio.it not showed 

### ISSUE THREAD

**Issue by fato63** [qgis2web/qgis2web#1067]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. I just install the latest release of qgis2web
2. No other issues
3. Every time I have same results
4. Complexity reduced.
5. Raise a Github issue, including:
  - the qgis2web version: [3.19.0] 
  - No Python error 
  - browser JS console errors -Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at file:///home/fato/Olds/fato/Documenti/speleo/rilievo/QGIS/WmsCartaGeologica/qgis2web_2024_05_13-18_39_36_023808/js/leaflet.js:5:3170
    at S.extend (file:///home/fato/Olds/fato/Documenti/speleo/rilievo/QGIS/WmsCartaGeologica/qgis2web_2024_05_13-18_39_36_023808/js/leaflet.js:5:3188)
    at file:///home/fato/Olds/fato/Documenti/speleo/rilievo/QGIS/WmsCartaGeologica/qgis2web_2024_05_13-18_39_36_023808/js/leaflet.pattern.js:6:34
    at file:///home/fato/Olds/fato/Documenti/speleo/rilievo/QGIS/WmsCartaGeologica/qgis2web_2024_05_13-18_39_36_023808/js/leaflet.pattern.js:6:7077
(anonymous) @ Class.js:121

  - Output: Blank page
 
[index.txt](https://github.com/qgis2web/qgis2web/files/15297846/index.txt)

**Comment by fato63** [comment]
[qgis2web_wms.zip](https://github.com/qgis2web/qgis2web/files/15297868/qgis2web_wms.zip)

Complete output from qgis2web.

**Comment by andreaordonselli** [comment]
What epsg is your qgis project set up with?
Have you tried 3857?
On my PC it works well both in openlayers export and with leaflets
![image](https://github.com/qgis2web/qgis2web/assets/89784373/d3b92ac7-c21c-4db5-ba19-b188ab51259a)

**Comment by fato63** [comment]
[image: Schermata del 2024-05-13 19-13-08.png]
Have you tried 3857?---Yes.

Il giorno lun 13 mag 2024 alle ore 19:06 Andrea Ordonselli <
***@***.***> ha scritto:

**Comment by andreaordonselli** [comment]
If you are happy with gis2web please consider donating a virtual coffee to support the development of the project.  Thank you.

**Comment by jukos** [comment]
Excuse me, please: I don't understand the solution to this problem.

I have also tested a WMS layer with 
https://geoportale.regione.lazio.it/capabilities/capabilities/wms/layer/56/
- 3857 for project and WMS layer. The layer is displayed in QGIS, but not for leaflet or openlayers / qgis2opengis.

Thank you and best regards

QGIS: 3.36.2-Maidenhead
qgis2web: 3.20
qgis2opengis: 2.20

**Comment by jukos** [comment]
Excuse me, please: I don't understand the solution to this problem.

I have also tested a WMS layer with
https://geoportale.regione.lazio.it/capabilities/capabilities/wms/layer/56/

    3857 for project and WMS layer. The layer is displayed in QGIS, but not for leaflet or openlayers / qgis2opengis.

Thank you and best regards

QGIS: 3.36.2-Maidenhead
qgis2web: 3.20
qgis2opengis: 2.20

**Comment by andreaordonselli** [comment]
Openlayers export has some problems that I will fix, Leaflet export works fine

https://github.com/qgis2web/qgis2web/assets/89784373/cb96ecc1-555e-4919-a949-073a0ce10931

**Comment by jukos** [comment]
OK. Thank you very much for the video. 
WMS now also works well for me. 
I have problems with WMTS, but this is not relevant at the moment.
I almost only do tests with qgis2opengis. My opinion: A very successful plugin.
Best regards

**Comment by andreaordonselli** [comment]
If you work there, I recommend you consider a recurring donation to always have the latest version of qgis2opengis. I'm glad you like it.
