### ISSUE TITLE
Incorrect translation from Dutch names (look like English) in the Dutch language again.

### ISSUE THREAD

**Issue by paulsoz** [qgis2web/qgis2web#1069]
This concerns the use of the Dutch application of Qgis with qgis2web latest version.
Some Dutch names in my attribute table that resemble English words such as "Outeren van" are automatically translated into Dutch again when creating a web map. I will then receive the text "Buiten Busje".
These translations are therefore incorrect, unwanted and very confusing.
The names should simply be displayed as they appear in the attribute table.
The problem has occurred since the last update of the qgis2web plugin

**Comment by andreaordonselli** [comment]
Hi, thanks for using qgis2web.  Regarding your problem: could it be that you have automatic translation set in your browser?
Have you tried opening the exported webmap with another browser, perhaps in an anonymous window? 
To be sure you can check the exported .js files in the layers folder and open them with a text editor.  You should find your data as in the original and this gives you the certainty that qgis2web has not translated anything.

**Comment by andreaordonselli** [comment]
If you are happy with gis2web please consider donating a virtual coffee to support the development of the project.  Thank you.
