### ISSUE TITLE
popup join data - popup link - popup video 

### ISSUE THREAD

**Issue by CamillaCao** [qgis2web/qgis2web#1070]
Why can't the web map I exported pop up the join data? I have checked that all the formats of the join columns are consistent with the original columns that can be displayed! In addition, if I want to insert a web page address including video, what should I set? Thanks

**Comment by andreaordonselli** [comment]
Thank you for using qgis2web.

It is not possible to export join fields between tables, as qgis2web transforms local data (i.e. stored on disk in the vector layer such as shp or other) into geojson.
The join fields between tables are not written in the vector, they practically do not exist outside the specific project. Therefore if you want to export them (and therefore make them visible) you must store them statically in the vector itself; please tell me if I explained myself well.

You can insert a link into a text field. It will be exported and will be clickable in the popup opening a new window.
![image](https://github.com/qgis2web/qgis2web/assets/89784373/4a398a1e-97bc-442b-a743-48760705135c)
![image](https://github.com/qgis2web/qgis2web/assets/89784373/7e3ad264-c6f0-4591-b181-32d23e8899b0)

You can insert images or videos as explained in the documentation; look at this link please: https://qgis2web.github.io/qgis2web/#setLayers

Greetings

**Comment by CamillaCao** [comment]
Hi Andrea,

Thanks so much for your reply!!

This problem was solved by your reminder. It is very helpful! By the way,
this plugin is really nice!!!

I am a master graduate in Trinity, and doing my dissertation with topic
about linking the QGIS to Kownledge Graph. If anything I could provide the
help, I am very welling to do that!

Thanks and best regards,
Camilla

**Comment by andreaordonselli** [comment]
Thank you for your offer of help.  There are many things on the to-do list for qgis2web.  But what I'm initially interested in is providing users with the same functionality between openlayers and leaflet export.  Currently leaflet has data filtering which is not supported by openlayers.  Could you give me a hand on this?  In the appearance tab there is the filter that allows the selection of fields, the leaflet export shows the filters on the right via scroll bars and more, allowing you to view only the data corresponding to the filter on the map.  ps: regarding your project, what do you mean by Kownledge Graph?

**Comment by andreaordonselli** [comment]
Hi Camilla, please test the join fields again, now the plugin should export them correctly. Be careful never to use apostrophes or quotation marks in field titles
