### ISSUE TITLE
Popup boxes appear vertically elongated with lots of content rather than wide enough to accommodate the information

### ISSUE THREAD

**Issue by Caties96** [qgis2web/qgis2web#1073]
When I had previously published a map using qgis2web, the resulting popup boxes for information were perfectly sized even with large amounts of information.  When updating the map, now using a recently updated version of the plugin, I noticed the popup boxes now elongate vertically with lots of information.  I am wondering if there is a way I could fix that?

I have attached an image that shows the difference between before and after with some confidential information greyed out for privacy purposes.

Thank you in advance, the plugin has been such a joy to use and create with.

![qgis2web query](https://github.com/qgis2web/qgis2web/assets/171470981/8e94fc56-ad23-4e6f-a0fe-dac004372524)

**Comment by andreaordonselli** [comment]
I will do a program update soon and can fix it.  Can you send me a zip of the old and new project so I can clearly see how to configure qgis2web?  I assume you used the openlayers export right?

**Comment by Caties96** [comment]
Hi there

Thank you so much for your prompt response.  I can definitely send it through to you - should I email it?  I was using Leaflet, not OpenLayers

**Comment by andreaordonselli** [comment]
You can load the zip here, otherwise send to info@opengis.it

**Comment by DNSQi** [comment]
After exporting, you can edit the dimensions of the popup using `layer.bindPopup(popupContent, {maxHeight: xxx})` in the index.html file

**Comment by andreaordonselli** [comment]
I have just released version [3.21.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.21.0), which fixes the issues discussed in this thread. The update its just available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.

**Comment by Caties96** [comment]
I have just tested it now and it worked ! Thank you so much for your
assistance!

I will look into the virtual coffee next week !

Have a wonderful day !

**Comment by andreaordonselli** [comment]
I'm glad I solved it. Please write if you see other bugs.
Thanks to you, have a nice day
