### ISSUE TITLE
TypeError: Exporting to FTP

### ISSUE THREAD

**Issue by bim-ba** [qgis2web/qgis2web#1076]
## Problem
Hello, I am having an issue with exporting to FTP server. I think the problem is with the type conversion in the progress bar context:
https://github.com/qgis2web/qgis2web/blob/98f49a775df158a291ecb799d143b00732a4e2b0/feedbackDialog.py#L157-L161

## Data
Just the standard Google Maps XYZ basemap or any other data.

## How to produce
1. Import or create layer `layer`
2. Launch qgis2web and select `layer` to export
3. In the "Export" tab select the "Export to FTP site" exporter
4. Configure FTP connection properly
5. Export

## Result after the producing
1. Error
2. Only one exported file appeared on the FTP server:
    - `public_html/css/fontawesome-all.min.css`
![image](https://github.com/qgis2web/qgis2web/assets/81964109/a898342e-e48c-4625-ab3e-9fb87041b0e0)

### Error trace
```text
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "../QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 389, in saveMap
    result = self.exporter.postProcess(results, feedback=self.feedback)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../QGIS/QGIS3\profiles\default/python/plugins\qgis2web\exporter.py", line 367, in postProcess
    if not uploadPath(os.path.join('.', source_folder)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../QGIS/QGIS3\profiles\default/python/plugins\qgis2web\exporter.py", line 361, in uploadPath
    if not uploadPath(current_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "../QGIS/QGIS3\profiles\default/python/plugins\qgis2web\exporter.py", line 352, in uploadPath
    feedback.setProgress(
  File "../QGIS/QGIS3\profiles\default/python/plugins\qgis2web\feedbackDialog.py", line 160, in setProgress
    self.progressBar.setValue(progress)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
```
### Python and QGIS details
Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527

**Comment by andreaordonselli** [comment]
At the moment I can't dedicate myself to fixing this functionality, once I have run out of priorities I will try to fix it.
In the meantime, I recommend exporting to a local folder and syncing, perhaps in real time, with a web folder using the freefilesync program

**Comment by Freecey** [comment]
Hi,

I'm following up on this issue, which was marked as completed on June 27. After reviewing the related commits, I haven't observed any changes addressing the problem.

I am still encountering the same issue with exporting to the FTP server as described in the initial report.

Could you please confirm if this issue has indeed been fixed or if it remains unresolved?

Thank you.

**Comment by andreaordonselli** [comment]
it is still an unresolved problem unfortunately
