### ISSUE TITLE
XYZ tiles exporting to overlaysTree not baseMaps

### ISSUE THREAD

**Issue by dgplacenames** [qgis2web/qgis2web#1077]
Base layers are exporting to overlaysTree, resulting in checkboxes rather than radio buttons:
![qgis2web_screenshot](https://github.com/qgis2web/qgis2web/assets/98712405/69910374-0948-4e8e-bb23-4a115da6e663)

        var baseMaps = {};
        var overlaysTree = [
            {label: '<img src="legend/southron_2.png" /> south ron', layer: layer_southron_2},
            {label: "OS 1st ed", layer: layer_OS1sted_1},
            {label: "OpenStreetMap", layer: layer_OpenStreetMap_0},]
        var lay = L.control.layers.tree(null, overlaysTree,{

Workaround: Move base layers to baseMaps with var lay = L.control.layers.tree(**baseMaps**, overlaysTree,{
This results in some odd radio button behaviour.

**Comment by andreaordonselli** [comment]
Hi, thanks for using qgis2web and thanks for your advice.  Checkboxes instead of radio buttons are desired.  Even if you selected two, only one base map would be visible, the upper one.  Furthermore, by deactivating them all it is possible to have a white background, useful in many cases.

**Comment by dgplacenames** [comment]
Thanks for the quick response. Worth noting that the WIKI still shows radio buttons which is one of the reasons I thought there might be a bug.
![image](https://github.com/qgis2web/qgis2web/assets/98712405/8838475c-3fbe-4504-b8b5-ede690a92d08)

**Comment by dgplacenames** [comment]
Radio buttons are desirable in some situations. Perhaps there could be an option to select them or checkboxes when exporting.

**Comment by andreaordonselli** [comment]
Thanks for the reports.  I put the creation of the "radio button" choice for the xyz and wms levels on the development list.  Greetings.
