### ISSUE TITLE
Collapse group in Layers List

### ISSUE THREAD

**Issue by giulianoramat** [qgis2web/qgis2web#1078]
Hi all, it seems to me that group layers default visualisation is always expanded, is there amy way in the qgis2web plugin interface to export layers group visualisation as collapsed?

**Comment by andreaordonselli** [comment]
qgis2web does not currently have this setting.
I can tell you how to do it though. Do you export with openlayers or leaflet?

**Comment by giulianoramat** [comment]
leaflet

**Comment by andreaordonselli** [comment]
Thank you for using qgis2web.
There isn't an option in the plugin yet, you can edit the code after exporting

for openlayers:
layers/layers.js -> fold: "open" or "close" 
![image](https://github.com/qgis2web/qgis2web/assets/89784373/1c0a7f8b-0f86-40ee-943e-c1ae0d61bd74)

for leflet:
index.html -> collapsed: "true" in your groups
![image](https://github.com/qgis2web/qgis2web/assets/89784373/c10585a2-eb4a-402f-9b07-143bcef9fd43)

**Comment by giulianoramat** [comment]
Thank you so much, it works perfectly!

**Comment by andreaordonselli** [comment]
In version [3.26.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.25.1) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
