### ISSUE TITLE
IndexError when exporting as Leaflet

### ISSUE THREAD

**Issue by jamesbe** [qgis2web/qgis2web#1080]
Hi there, I am having this same issue! Any help would be greatly appreciated! I am using QGIS (3.38.0) and qgis2web (3.21.0). I attached my qgis project:
[Single_Map.zip](https://github.com/user-attachments/files/16179437/Single_Map.zip)

Same issue reported here: #1026 

Little more error info:
An error has occurred while executing Python code:

IndexError: 1
Traceback (most recent call last):
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 383, in saveMap
results = writer.write(self.iface,
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
self.preview_file = self.writeLeaflet(
^^^^^^^^^^^^^^^^^^
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 276, in writeLeaflet
useOSMB) = writeVectorLayer(layer, safeLayerName,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 125, in writeVectorLayer
useShapes) = getLayerStyle(layer, safeLayerName, interactive,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 63, in getLayerStyle
pattern) = getSymbolAsStyle(cat.symbol(), markerFolder,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 183, in getSymbolAsStyle
sl = symbol.symbolLayer(sl)
^^^^^^^^^^^^^^^^^^^^^^
IndexError: 1

Python version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)]
QGIS version: 3.38.0-Grenoble Grenoble, 37aa6188bc

Python Path:
C:/PROGRA1/QGIS331.0/apps/qgis/./python
C:/Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA1/QGIS331.0/apps/qgis/./python/plugins
C:\PROGRA1\QGIS331.0\apps\grass\grass83\etc\python
C:\QGIS\Single_Map
C:\Program Files\QGIS 3.38.0\bin\python312.zip
C:\PROGRA1\QGIS331.0\apps\Python312\DLLs
C:\PROGRA1\QGIS331.0\apps\Python312\Lib
C:\Program Files\QGIS 3.38.0\bin
C:\PROGRA1\QGIS331.0\apps\Python312
C:\PROGRA1\QGIS331.0\apps\Python312\Lib\site-packages
C:\PROGRA1\QGIS331.0\apps\Python312\Lib\site-packages\win32
C:\PROGRA1\QGIS331.0\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA1\QGIS331.0\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/jberger/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\jberger\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/QGIS/Single_Map

**Comment by andreaordonselli** [comment]
Thank you for using qgis2web,
I saw your project and the symbols are too complicated, qgis2web has been programmed to replicate only simple symbols, you will necessarily have to invent something to simplify it.

No multiple symbols
![2024-07-12 11_56_21-single_map — QGIS](https://github.com/user-attachments/assets/8de5ca35-df1e-434f-bacf-724d0d21f840)

Yes simple symbols
![2024-07-12 11_56_27-single_map — QGIS](https://github.com/user-attachments/assets/dce6b371-3711-428e-a0c3-ff81663a403e)

No marker lines, only SVG Marker in points layers
![2024-07-12 11_56_42-single_map — QGIS](https://github.com/user-attachments/assets/46c5b107-258f-4766-938c-6e94a86e00ae)

No ruled based in openlayers export, maybe test with leaflet
![2024-07-12 11_56_50-single_map — QGIS](https://github.com/user-attachments/assets/b327ac45-1af4-489a-8279-9b140cf2b5d1)

Consult the guide to view the supported symbols https://qgis2web.github.io/qgis2web/#SetStyles
