### ISSUE TITLE
How to export to a designated folder just from python?

### ISSUE THREAD

**Issue by interestingsquirrel** [qgis2web/qgis2web#1082]
I used "plugins['qgis2web'].run()" to run the plugin from the python but I am struggling to find an export function. I am trying to automate the export feature simply by running code without interaction for automation purposes.

Thanks!

**Comment by interestingsquirrel** [comment]
When using the toolbox it creates a folder for the export but QGIS goes "not responding" and when it is done the html is empty.

**Comment by andreaordonselli** [comment]
We talk about it here #730
