### ISSUE TITLE
My shapefile points are not visible in preview of the webmap

### ISSUE THREAD

**Issue by SiDdHaRtHKaNoUjIa13** [qgis2web/qgis2web#1084]
![Screenshot 2024-07-24 154351](https://user-images.githubusercontent.com/130286366/351674569-fe4049d4-056a-41e8-b3f3-8c80f5ea38a0.png)
![Screenshot 2024-07-24 154420](https://user-images.githubusercontent.com/130286366/351674590-b8a1489a-2b4f-4d7c-b15a-ce672ca6a086.png)

**Comment by andreaordonselli** [comment]
I can't see the screenshots

**Comment by SiDdHaRtHKaNoUjIa13** [comment]
Sure here is the zip file with points and the project 
[Sahpefile Points.zip](https://github.com/user-attachments/files/16382686/Sahpefile.Points.zip)

**Comment by andreaordonselli** [comment]
I have no problem generating the preview with your level.
What errors do you get?

**openlayers preview**
![2024-07-26 11_22_26-Doubt — QGIS](https://github.com/user-attachments/assets/8b422522-415c-4666-a808-6df81c71cd88)

**leaflet preview**
![2024-07-26 11_22_18-Doubt — QGIS](https://github.com/user-attachments/assets/c0959291-8b25-4be7-9911-8b9a2b965f6e)
