### ISSUE TITLE
QGIS2web not working with Bing map

### ISSUE THREAD

**Issue by juanqgis2** [qgis2web/qgis2web#1088]
Hello,

I have not been able to export or preview my QGIS to QGIS2Web. I got this message: 

"qgis2web supports a new browser for webmap preview, but it is not available because the PyQtWebEngine 5.15.6 dependency is missing or your QGIS version is earlier than 3.38.0
Please ensure you have:
- QGIS >= 3.38.0
- AN ACTIVE INTERNET CONNECTION (even under proxy)
Then click the button to install."

I even could not do it with the "use the old brower" button

So I updated by QGIS to the latest version and installed a "new browser" but the map it still not exporting nor previewing. Did anyone come across the same issue?

**Comment by andreaordonselli** [comment]
I imagined there would be some problems switching to the new browser.
In any case, the change made only relates to the preview window, not to the export capacity. Therefore the software should export your project as before.

Ant questions:
- what system are you in? windows? linux? max?
- if you install the new browser what do you see?
- if you use the previous one what do you see?
- if you export what do you see?
Maybe attach some screens, thanks.

Please note that there may also be conflicts with other extensions. Maybe try temporarily disabling other extensions before launching qgis2web.

**Comment by juanqgis2** [comment]
Thanks for your swift response. As for your questions:

what system are you in? windows? linux? max? 
Windows
if you install the new browser what do you see?
Nothing, neither the Preview nor the Export
if you use the previous one what do you see?
Nothing, neither the Preview nor the Export. 
if you export what do you see?
Just a blank page.

I attach the screen.

Thanks
![qgis](https://github.com/user-attachments/assets/3bedfeda-0d48-4018-a82e-ef712e857a76)

**Comment by andreaordonselli** [comment]
Can you create a zip from your project and upload it here?

I ask you more questions:
- Do you have administrative rights?
- Are you connected to the internet? How? directly or under proxy?
- When you click Install New Browser, does not an installation screen start?
- Did you install qgis via osgeo4w or through the msi package downloaded from the site?

**Comment by andreaordonselli** [comment]
I'm glad you solved it, I hope you managed to use the new browser.

Please consider supporting the project with the donation of a virtual coffee through the button in the Home. 
Thanks
