### ISSUE TITLE
Quotes in Categorized Symbology create Blank Map

### ISSUE THREAD

**Issue by Cactusman2011** [qgis2web/qgis2web#1089]
If a layer's symbology in the "Categorized" style refer to field names by wrapping in double-quotes, the map (and map preview) will be blank. This is true regardless if only I reference one field or if I use an expression. Importantly, using "Rule-Based" symbology does _not_ cause the issue. 

Reproduction steps:

1. qgis2web 3.22; qgis 3.38.1
2. Have any layer in the categorized style of symbology.
3. Instead of the field drop-down, manually type the field name "like_so".
4. The layer being marked for export will cause the map and preview to be blank. Unchecking the export box for this layer will restore the preview and export.

**Comment by andreaordonselli** [comment]
In version [3.24.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.24.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
