### ISSUE TITLE
Two layers from the same source but with different symbology won't both show in Qgis2web [SOLVED: do not write the # in the field name]

### ISSUE THREAD

**Issue by evert30** [qgis2web/qgis2web#1091]
I am trying to create a online map for my project where I can visualize certain layers. I got two layers, who both share the same source, attribute table, features, etc. They only differ in symbology. The Qgis2web plugin does visualize the layer which is categorized on field 'Corporatie', but does not work for the layer categorized on field 'Geplanderenovatie'.
![Screenshot 2024-08-12 151532](https://github.com/user-attachments/assets/4794fd4a-9db8-48ad-bda6-fafc5733d26d)
![Screenshot 2024-08-12 151559](https://github.com/user-attachments/assets/f2903e89-584c-42c4-9dd0-ccbcdd72b770)

I have tried a variety of solutions, from changes in the attribute table, CRS, to the symbology and classification. Nothing has seemed to work so far. Other fields do also not get visualized. The field 'Corporatie' seems to be the only working on as of yet.
[240731 - Overzichtskaart Koppelkansen STUW 0.2.qgz.zip](https://github.com/user-attachments/files/16582134/240731.-.Overzichtskaart.Koppelkansen.STUW.0.2.qgz.zip)

Any idea what could be the issue?
Thanks in advance,
Evert

**Comment by andreaordonselli** [comment]
When qgis2web exports your data in geojson format it stops exporting fields that have titles starting with #.
Solve this problem and this will be the result.
[qgis2web_2024_08_14-14_14_56_405143.zip](https://github.com/user-attachments/files/16612841/qgis2web_2024_08_14-14_14_56_405143.zip)
