### ISSUE TITLE
suggestions: button size and other button search for other layer.

### ISSUE THREAD

**Issue by vzlprojects** [qgis2web/qgis2web#1092]
Hello!
congratulations on your excellent work! I'll just suggest two updates:

1) possibility to add more than one search button on the layers. Currently we can only search a single layer. If you could add another button to search another layer it would be great!

2) The native buttons, including search, zoom, etc., are too small. Could you make them bigger?

Thanks again for your excellent work!

**Comment by andreaordonselli** [comment]
Thanks for your advice, I will take it into consideration
