### ISSUE TITLE
remove or hidden side bar and multilayer search (coffe version)

### ISSUE THREAD

**Issue by vzlprojects** [qgis2web/qgis2web#1093]
Good morning! 
A few days ago I suggested some updates, but then I saw that they are in the most complete version (thanks for the coffee).
However, I can't get the option to search in one or more layers to appear (apparence Tab).
Am I doing something wrong? 
By the way, how can I remove the tab sidebar?

Thanks again for your excellent work!

plugin version: 2.22.0
QGIS: 3.38

![1](https://github.com/user-attachments/assets/1f7e876e-e6ba-4f41-878c-0b3c26866a88)

**Comment by andreaordonselli** [comment]
please open this comment in the right repository [here](https://github.com/andreaordonselli/qgis2o.gis/issues)
