### ISSUE TITLE
Openlayers export does not correctly show geometries with graduated symbology which have (NULL) values ​​in the table [SOLVED]

### ISSUE THREAD

**Issue by doerte-fin** [qgis2web/qgis2web#1096]
I made a classified layer and if there are values in the attribute table with nothing in it, then the export for OpenLayers only shows the marker if you zoom in very much.
When there are no blanks, then the markers are always visible.
I created a small working example to show the error.
[QGIS_Zoom_Bug.zip](https://github.com/user-attachments/files/16921938/QGIS_Zoom_Bug.zip)

**Comment by doerte-fin** [comment]
Cool thank you, that went quickly :)

**Comment by andreaordonselli** [comment]
I have just released version [3.23.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.23.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
