### ISSUE TITLE
Colours won't export

### ISSUE THREAD

**Issue by ooa-tech** [qgis2web/qgis2web#1098]
I have colouored my map with values from a csv file joined to the geometry layer's attribute table.  All works fine in QGIS.  Each polygon is coloured according to the value in the attribute table, but when I export with QGIs2web the colours do not appear and they do not appear in the web preview panel on  either leaflet or open layer. All I get is a uniform, solid colour fill. 

Is there an obvious setting I have missed somewhere?

**Comment by andreaordonselli** [comment]
Hi, unfortunately there isn't a setting you haven't seen. Symbols must be applied directly to features to be exported. qgis2web can't get them from the table. If you want to send an example of your project, I'll see if it's possible to apply the coloring logic afterwards.
You can upload your zip file here.
Greetings.

**Comment by ooa-tech** [comment]
You are very generous with your time. Thank you.

I've attahced the project file and data sources.  It's a fairly simple file.  Just one layer with 650 features.
[QGIS.zip](https://github.com/user-attachments/files/17025661/QGIS.zip)

**Comment by andreaordonselli** [comment]
Export your project with openlayers
Edit the style file inside the style folder.
![image](https://github.com/user-attachments/assets/a52c094b-30a7-495a-b024-0cf7b165060e)
Then:
![image](https://github.com/user-attachments/assets/9ece9f50-3f74-44eb-8db0-210d37df5c5e)

Add this code to acquire colors from json table:
```javascript
    // get single colors
    var red = feature.get('winning_color3_red');
    var green = feature.get('winning_color3_green');
    var blue = feature.get('winning_color3_blue');
    
    // Define rgba
    var fillColor = 'rgba(' + red + ',' + green + ',' + blue + ',1.0)';
```

Add "fillColor" into the function
```javascript
    var style = [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.988}),fill: new ol.style.Fill({color: fillColor}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })];
```

Here is the complete code:

```javascript
var size = 0;
var placement = 'point';

var style_Westminster_Parliamentary_Constituencies_July_2024_Boundaries_UK_BSC_4567235412635543479PCON_JULY_2024_UK_BSCshp_0 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
	
	
    // get single colors
    var red = feature.get('winning_color3_red');
    var green = feature.get('winning_color3_green');
    var blue = feature.get('winning_color3_blue');
    
    // Define rgba
    var fillColor = 'rgba(' + red + ',' + green + ',' + blue + ',1.0)';
	
	
	
    var value = ""
    var labelText = "";
    size = 0;
    var labelFont = "10px, sans-serif";
    var labelFill = "#000000";
    var bufferColor = "";
    var bufferWidth = 0;
    var textAlign = "left";
    var offsetX = 8;
    var offsetY = 3;
    var placement = 'point';
    if ("" !== null) {
        labelText = String("");
    }
    var style = [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.988}),fill: new ol.style.Fill({color: fillColor}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })];

    return style;
};
```
Result:
![image](https://github.com/user-attachments/assets/42d95f9e-f162-4523-ae1d-1ea9001d69f7)

**Comment by ooa-tech** [comment]
That's wonderful. I can't thank you enough for your help.  Genuinely appreicated.

**Comment by andreaordonselli** [comment]
Evaluate a donation to support qgis2web via the button in the GitHub home repo.
Greetings
