### ISSUE TITLE
Headless Web export (CLI / QGIS Processing Executor) [UNSOLVED - show #730 issue]

### ISSUE THREAD

**Issue by Awbmilne** [qgis2web/qgis2web#1099]
Hey there, been working my way through QGIS and QGIS2Web. I am currently using QGIS and this plugin to create a web-hosted map for personal use. I would like to host it through Github pages, but I also want to automatically export the web files and host them using GitHub Actions.

Is there any known method for running QGIS2web from the command line? I was able to find a reference to the [QGIS Processing Executor](https://docs.qgis.org/3.34/en/docs/user_manual/processing/standalone.html#using-processing-from-the-command-line) which didn't have any processes for QGIS2web, but maybe im not looking in the right place.

Thanks for the help!

(Yes, I know I could run QGIS2Web in the repository and then upload the updated web files, but I want to automate as much as possible)

**Comment by andreaordonselli** [comment]
We talk about it here #730 but there are still no solutions.
