### ISSUE TITLE
layers are not showing, only google basemap shows [SOLVED - check project and layers CRS - use known CRS]

### ISSUE THREAD

**Issue by pravesh-kasare** [qgis2web/qgis2web#1100]
![image](https://github.com/user-attachments/assets/678f2092-d43e-41c8-90b0-130c6e6eae08)

![image](https://github.com/user-attachments/assets/307f9e97-61fb-44d1-b6f2-5bc4134f5bf3)

**Comment by pravesh-kasare** [comment]
![image](https://github.com/user-attachments/assets/00d0acb9-889b-40fd-ae29-220cc7f6272a)

data to export as web page

**Comment by andreaordonselli** [comment]
Can you upload a zip file here containing your project and your data?

**Comment by pravesh-kasare** [comment]
[Adminstrative_Boundary.zip](https://github.com/user-attachments/files/17148703/Adminstrative_Boundary.zip)

**Comment by andreaordonselli** [comment]
qgis2web cannot handle your custom CRS. Should you transform your data into a known CRS, can you do it?
Save layers in other CRS
![image](https://github.com/user-attachments/assets/f56c0dc6-4585-44ef-b1c0-6d2ac418e3c7)
Run qgis2web
![image](https://github.com/user-attachments/assets/91824fde-91fe-46da-8811-8c6b452b12d4)

**Comment by pravesh-kasare** [comment]
can you tell me which projection you set.. im trying UTM 43N but my project shifting to somewhere else

**Comment by andreaordonselli** [comment]
I exported the layer to 4326 and added it to the map. Then I set the CRS of the project, at the bottom right, Always in 4326.
Then in your project was the Pattern line which is an unsupported symbology, Remember to use simple symbols and if you want the transparency of the fill you can make the color transparent, not the layer. Let me know if you can fix it.

**Comment by pravesh-kasare** [comment]
thanks, ive to transform all my files to know crs.
thanks for the help
