### ISSUE TITLE
The label appears off-center [SOLVED - act on the code after export - additional code here]

### ISSUE THREAD

**Issue by Killenheladan** [qgis2web/qgis2web#1101]
Hi!

My numbered points in my survey layer show up off-center in the exported version. They appear as if i have chosen the labels to appear around point in the layer properties. No matter how i choose the alignment or appearance, they still show show up off-center. I'm new to both QGis and qgis2web so there might be an easy solution to this.

Thanks!

![In QGis](https://github.com/user-attachments/assets/7cdeaf94-d6c3-44dd-bb8d-d15e5e90b9d1)
![In qgis2web](https://github.com/user-attachments/assets/c10673cb-5b48-41be-93ff-93c542be0fa3)

**Comment by Killenheladan** [comment]
Thank You!

Now all the points dissappear completely :)

the style script (layername_style.js) looks like this now:

var size = 0;
var placement = 'point';
function categories_survey_Glemmingebro_4(feature, value, size, resolution, labelText,
                       labelFont, labelFill, bufferColor, bufferWidth,
                       placement) {
                switch(value.toString()) {case '1':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 12.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.0}), fill: new ol.style.Fill({color: 'rgba(255,255,255,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth, offsetX, offsetY, textAlign)
    })];
                    break;
case '2':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 12.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.0}), fill: new ol.style.Fill({color: 'rgba(31,255,1,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth, offsetX, offsetY, textAlign)
    })];
                    break;
case '3':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 12.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.0}), fill: new ol.style.Fill({color: 'rgba(232,255,61,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth, offsetX, offsetY, textAlign)
    })];
                    break;
case '4':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 12.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.0}), fill: new ol.style.Fill({color: 'rgba(255,127,0,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth, offsetX, offsetY, textAlign)
    })];
                    break;
case '5':
                    return [ new ol.style.Style({
        image: new ol.style.Circle({radius: 12.0 + size,
            stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0.0}), fill: new ol.style.Fill({color: 'rgba(249,158,252,1.0)'})}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth, offsetX, offsetY, textAlign)
    })];
                    break;}};

var style_survey_Glemmingebro_4 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = feature.get("åtgärdstid");
    var labelText = "";
    size = 0;
    var labelFont = "13.0px \'Open Sans\', sans-serif";
    var labelFill = "#323232";
    var bufferColor = "";
    var bufferWidth = 0;
    var textAlign = "center";
    var offsetX = 0;
    var offsetY = -15;
    var placement = 'point';
    if (feature.get("Nr") !== null) {
        labelText = String(feature.get("Nr"));
    }
    
var style = categories_survey_Glemmingebro_4(feature, value, size, resolution, labelText,
                          labelFont, labelFill, bufferColor,
                          bufferWidth, placement );

    return style;
};

and the resources look like this:

var createTextStyle = function(feature, resolution, labelText, labelFont,
                               labelFill, placement, bufferColor,
                               bufferWidth, offsetX, offsetY, textAlign) {

    if (feature.hide || !labelText) {
        return; 
    } 

    if (bufferWidth == 0) {
        var bufferStyle = null;
    } else {
        var bufferStyle = new ol.style.Stroke({
            color: bufferColor,
            width: bufferWidth
        })
    }
    
    var textStyle = new ol.style.Text({
        font: labelFont,
        text: labelText,
        textBaseline: "middle",
        textAlign: "textAlign",
        offsetX: offsetX,
        offsetY: offsetY,
        placement: placement,
        maxAngle: 0,
        fill: new ol.style.Fill({
          color: labelFill
        }),
        stroke: bufferStyle
    });

    return textStyle;
};

function stripe(stripeWidth, gapWidth, angle, color) {
    var canvas = document.createElement('canvas');
    var context = canvas.getContext('2d');
    canvas.width = screen.width;
    canvas.height = stripeWidth + gapWidth;
    context.fillStyle = color;
    context.lineWidth = stripeWidth;
    context.fillRect(0, 0, canvas.width, stripeWidth);
    innerPattern = context.createPattern(canvas, 'repeat');

    var outerCanvas = document.createElement('canvas');
    var outerContext = outerCanvas.getContext('2d');
    outerCanvas.width = screen.width;
    outerCanvas.height = screen.height;
    outerContext.rotate((Math.PI / 180) * angle);
    outerContext.translate(-(screen.width/2), -(screen.height/2));
    outerContext.fillStyle = innerPattern;
    outerContext.fillRect(0,0,screen.width,screen.height);

    return outerContext.createPattern(outerCanvas, 'no-repeat');
};

**Comment by andreaordonselli** [comment]
Can you do a new export, create a zip and upload it here?

**Comment by Killenheladan** [comment]
[qgis2web_2024_09_30-13_06_13_431421.zip](https://github.com/user-attachments/files/17188732/qgis2web_2024_09_30-13_06_13_431421.zip)

**Comment by andreaordonselli** [comment]
Since your style is categorized or graduated the modification must be made slightly different, I confirm the modification to function.js and this is the modification to your style

```
var style_survey_Glemmingebro_4 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = feature.get("åtgärdstid");
    var labelText = "";
    size = 0;
    var labelFont = "13.0px \'Open Sans\', sans-serif";
    var labelFill = "#323232";
    var bufferColor = "";
    var bufferWidth = 0;
    var textAlign = "center";
    var offsetX = 0;
    var offsetY = -15;
    var placement = 'point';
    if (feature.get("Nr") !== null) {
        labelText = String(feature.get("Nr"));
    }
    
var style = categories_survey_Glemmingebro_4(feature, value, size, resolution, labelText,
                          labelFont, labelFill, bufferColor,
                          bufferWidth, placement, textAlign);

    return style;
};

```

I attach the adjusted project
[qgis2web_2024_09_30-13_06_13_431421.zip](https://github.com/user-attachments/files/17188820/qgis2web_2024_09_30-13_06_13_431421.zip)


Result:

![image](https://github.com/user-attachments/assets/141276bf-c04d-44e2-ad2a-2b094396cc08)

**Comment by Killenheladan** [comment]
That is perfect. Thank you very much! I'll make sure to buy You a cup of coffee!!

**Comment by Killenheladan** [comment]
Can I just ask another question; How come all three layers (glemmingebro, Valleberga and Ingelstorp) show upp correctly, even though it's just glemmingebro that has edited var textAlign, var offsetX and var offsetY. I'm just trying to grasp what i need to do for my next project to get it right.
