### ISSUE TITLE
Export with errors and blank map

### ISSUE THREAD

**Issue by thierryS51** [qgis2web/qgis2web#1103]
Hi,

i built a map with several layers. One is a Delimited text file. (csv source). When i export the project i have this red message :"Traceback (most recent call last): File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 52, in exportStyles useMapUnits) = categorized(defs, sln, layer, renderer, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 260, in categorized useMapUnits) = (getSymbolAsStyle(symbol, stylesFolder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 554, in getSymbolAsStyle getIcon("styles/" + base_filename, File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 794, in getIcon scale = str(float(size) / float(svgWidth)) ^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '84.676pt' "

The html is produced but i get a blank map.

csv headlines are :
![image](https://github.com/user-attachments/assets/f1daaae9-9f66-4746-84bf-381487e30d58)

Can you explain why this kind of layer is wrong ?

If i don't join this layer, the webmap is produced.

I use a layer for towns with a filter, [ADMIN-EXPRESS-COG-CARTO_3-0__SHP__FRA_2021-05-19\ADMIN-EXPRESS-COG-CARTO\1_DONNEES_LIVRAISON_2021-05-19\ADECOGC_3-0_SHP_LAMB93_FR\COMMUNE.shp](file:///K:/ThS/QGIS-%20Cartes/ADMIN-EXPRESS-COG-CARTO_3-0__SHP__FRA_2021-05-19/ADMIN-EXPRESS-COG-CARTO/1_DONNEES_LIVRAISON_2021-05-19/ADECOGC_3-0_SHP_LAMB93_FR/COMMUNE.shp)

the name of the city is only visible if I zoom in enormously. There is certainly a parameter to modify somewhere, but where?

finally, I created popups in html. They appear in qgis, but not in the produced web map.

can you help me ?

Best regards

**Comment by andreaordonselli** [comment]
Can you upload the zip of your project? I would like to reproduce the problem.

The error is: ValueError: could not convert string to float: '84.676pt' "
Where is this data written?

For the zoom I should test.

The popup is the default of the exported map. You do not see what you set in HTML in QGIS.

**Comment by thierryS51** [comment]
[projet carte métiers.zip](https://github.com/user-attachments/files/17260338/projet.carte.metiers.zip)

**Comment by thierryS51** [comment]
Hello,

i don't understand. In the zip there is the qgz and csv i use. You don't found it ?
Or you need another file ?

**Comment by andreaordonselli** [comment]
the problem is that you are applying the style to a value coming from an expression (type + ':' + service)

![image](https://github.com/user-attachments/assets/6ea54893-47f6-4a43-b1b2-b51355089c36)

applies the style to a single field in the table (you could create a new field where you join the data from multiple fields)
![image](https://github.com/user-attachments/assets/1e915e65-3802-4cfb-a687-32af14d9a78f)

here I applied the svg symbol to the type values:
![image](https://github.com/user-attachments/assets/40d48473-77c7-40b7-b8f9-566b61feb872)

**Comment by thierryS51** [comment]
ok, i'll try this and i'll tell you

thks

**Comment by thierryS51** [comment]
hello,

i changed the type of the legend, but the result is exactly the same....

export in qgis2web :

Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting DISI IDF to JSON... done
Exporting DISI NORD to JSON... done
Exporting DISI SE to JSON... done
Exporting DISI RAAB to JSON... done
Exporting DISI SO to JSON... done
Exporting DISI CO to JSON... done
Exporting DISI GE to JSON... done
Exporting COMMUNE to JSON... done
Exporting ESI - Métiers to JSON... done done
Exception in layer listes_esi_metiers2_1047109a_a7ee_4cdd_ba40_deab93b9549c with renderer CATEGORIZED: idx type arc::arc::MARKER SYMBOL (1 layers) color 27,10,27,255:1 cyb::cyb::MARKER SYMBOL (1 layers) color 0,0,0,255:1 dvc::dvc::MARKER SYMBOL (1 layers) color 47,31,216,255:1 dvj::dvj::MARKER SYMBOL (1 layers) color 189,8,11,255:1 dvk::dvk::MARKER SYMBOL (1 layers) color 234,84,201,255:1 dvo::dvo::MARKER SYMBOL (1 layers) color 196,239,87,255:1 dvp::dvp::MARKER SYMBOL (1 layers) color 238,234,17,255:1 dwb::dwb::MARKER SYMBOL (1 layers) color 238,32,207,255:1 dws::dws::MARKER SYMBOL (1 layers) color 20,19,33,255:1 edq::edq::MARKER SYMBOL (1 layers) color 227,26,28,255:1 exa::exa::MARKER SYMBOL (1 layers) color 238,130,79,255:1 exg::exg::MARKER SYMBOL (1 layers) color 51,160,44,255:1 exl::exl::MARKER SYMBOL (1 layers) color 31,120,180,255:1 exp::exp::MARKER SYMBOL (1 layers) color 227,26,28,255:1 exz::exz::MARKER SYMBOL (1 layers) color 132,32,182,255:1 iia::iia::MARKER SYMBOL (2 layers) color 35,35,35,255:1 inx::inx::MARKER SYMBOL (2 layers) color 31,120,180,255:1 ixg::ixg::MARKER SYMBOL (1 layers) color 51,160,44,255:1 ixl::ixl::MARKER SYMBOL (2 layers) color 112,49,166,255:1 moe::moe::MARKER SYMBOL (1 layers) color 31,120,180,255:1 ops::ops::MARKER SYMBOL (1 layers) color 227,26,28,255:1 rsx::rsx::MARKER SYMBOL (1 layers) color 136,72,214,255:1 slx::slx::MARKER SYMBOL (1 layers) color 33,123,213,255:1 soc::soc::MARKER SYMBOL (1 layers) color 32,183,206,255:1 syg::syg::MARKER SYMBOL (1 layers) color 51,160,44,255:1 syl::syl::MARKER SYMBOL (1 layers) color 31,120,180,255:1 syw::syw::MARKER SYMBOL (1 layers) color 227,26,28,255:1 syz::syz::MARKER SYMBOL (1 layers) color 112,49,166,255:1 tel::tel::MARKER SYMBOL (1 layers) color 60,130,112,255:1 vrt::vrt::MARKER SYMBOL (1 layers) color 40,74,146,255:1 : Traceback (most recent call last): File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 52, in exportStyles useMapUnits) = categorized(defs, sln, layer, renderer, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 260, in categorized useMapUnits) = (getSymbolAsStyle(symbol, stylesFolder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 554, in getSymbolAsStyle getIcon("styles/" + base_filename, File "C:\Users/tsimonneau01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 794, in getIcon scale = str(float(size) / float(svgWidth)) ^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '84.676pt' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:\Users\tsimonneau01\AppData\Local\Temp\qgis2web

[projet carte métiers.zip](https://github.com/user-attachments/files/17293098/projet.carte.metiers.zip)

**Comment by andreaordonselli** [comment]
Font and Ellipse Marker are not supported.

![2024-10-08 14_26_24-_metiers esi tout — QGIS](https://github.com/user-attachments/assets/0c83628b-f0c4-4a21-b0a9-88e9661d6d80)
![2024-10-08 14_26_46-_metiers esi tout — QGIS](https://github.com/user-attachments/assets/4ae7a98a-a4b9-4d20-b5f1-c8c3ef940aea)
![2024-10-08 14_27_44-_metiers esi tout — QGIS](https://github.com/user-attachments/assets/6e774baa-8180-4108-9764-99856e46389e)
![2024-10-08 14_28_00-_metiers esi tout — QGIS](https://github.com/user-attachments/assets/247b877b-f3ff-4931-82d3-d49b93ef4226)
![2024-10-08 14_28_28-_metiers esi tout — QGIS](https://github.com/user-attachments/assets/55bc903a-68ab-4918-98a8-cf46c5102b38)

this svg icon gives error, I don't know why

Once these problems have been solved, the export works
![image](https://github.com/user-attachments/assets/18cb24da-e0b5-4822-8852-2e054c5d347e)

Let me know if you can proceed

**Comment by thierryS51** [comment]
ok !! thanks !

**Comment by thierryS51** [comment]
i changed markers, there's only SVG and Simple now, but it's always the same error message.

**Comment by andreaordonselli** [comment]
try exporting this, and add what is missing as icons, each added icon try the export so you will know what gives error

[metiers esi tout.zip](https://github.com/user-attachments/files/17295026/metiers.esi.tout.zip)
