### ISSUE TITLE
The order of the pop-up contents is different than the order in QGIS attribute tables. Is there a way to correct this? I use qgis 3.38.3

### ISSUE THREAD

**Issue by paulsoz** [qgis2web/qgis2web#1107]
Before opening an issue:
- Check that you have installed the latest version of qgis2web
- Search among the issues if a similar report already exists and if you can find your solution
- Simplify your project with simple layer names, simple field names, simple symbols (Avoid apostrophe, double quotes, parentheses, accents..)
- Attach an example of your project so that we can reproduce the issue
- If you can't attach an example project, attach screenshots

For the experts:
- Paste qgis2web or QGIS Python console errors
- Paste browser console errors

**Comment by andreaordonselli** [comment]
For now it has never happened to me. I have to be able to reproduce the problem to correct it. Do you have a possibility to upload your project here as a zip?

**Comment by paulsoz** [comment]
I found something about 'Refactor fields' on the following site: https://gis.stackexchange.com/questions/363862/rearranging-attribute-order-for-export-to-excel 
I can't find this in de Processing Toolbox of the qgis version 3.38.3
[Test qgis2web.zip](https://github.com/user-attachments/files/17450100/Test.qgis2web.zip)

I pu a zip file of my project  here.

**Comment by andreaordonselli** [comment]
qgis2web exports the columns in the order they exist in the layer, even if you used "Organize Table Column", which is just a visual modification, not to the data.
![image](https://github.com/user-attachments/assets/0de5bb85-9ade-4146-b01c-c6dc8822fffb)

To actually edit the data you need to use a toolbox process called "Refactor fields", here is a video showing its use.
https://www.youtube.com/watch?v=xDWtC6Ww2ns&ab_channel=ArnoldKilaini

**Comment by paulsoz** [comment]
Thanks Andrea for your help, it solved my problem.

**Comment by andreaordonselli** [comment]
Kindly evaluates the donation of a coffee through the button in the GitHub home. Thanks
