### ISSUE TITLE
CLS Shift and Load Issues with 

### ISSUE THREAD

**Issue by oldtimemapper** [qgis2web/qgis2web#1111]
Hello, 

I am currently using latest version of qgis2web 3.23 and QGIS 3.38 on a Mac.

The issues I am having are with the attributions inside either the Leaflet or OpenLayers output.   It seems some of the symbols and characters that are used in the attributions and on the older measuring and layer tools cause CLS issues .

Can there be a way to add simple text attributions under the map instead of embedded in the maps if you want?   Seems you get a lot of CLS errors with attributions and some of the symbols used that are embedded in the map.   

We all want to rank well so we can pass Google's Core Web Vitals.   I am getting sort of tired of writing/placing  code to either move the attribution or remove them and then writing a friendly/fast loading attribution that is outside and below the map.  Would be nice to double check any embedded attribution updates in Lighthouse before a new qgis2web release so these attribution CLS bumps can be smoothed out.

Thank you

**Comment by andreaordonselli** [comment]
Hi, I'm glad you use qgis2web, 

have you considered excluding the webmap made by qgis2web from Google Search by adding this tag in the head section of the HTML?
`<meta name="robots" content="noindex">`
The page will not appear in the Google search, reducing the importance of Core Web Vitals.

Or: you have evaluated to exclude the page from sitemap.xml file?

I'll do some tests with Lighthouse but it would be convenient to have example layers that create your attributions. Can you include something?

Entering attributions off the map is excluded, We have to find together a CSS solution that solves the problem type using "fixed" or "absolute" or understanding if there are strange characters to avoid / preload.

Thanks

**Comment by andreaordonselli** [comment]
Closed due to lack of feedback
