### ISSUE TITLE
AttributeError: 'OpenLayersWriter' object has no attribute 'baseMap' 

### ISSUE THREAD

**Issue by stalefish57413** [qgis2web/qgis2web#1112]
Whenever i start "export projekt" im presented with this error Message:

`Traceback (most recent call last): File "C:\Users/Ma-Daniel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 105, in processAlgorithm writer.write(iface, write_folder) File "C:\Users/Ma-Daniel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 95, in write baseMap=self.baseMap, ^^^^^^^^^^^^ AttributeError: 'OpenLayersWriter' object has no attribute 'baseMap' `

I tried several maps incuding empty ones and on 3 different pcs, where one was a fresh install of QGIS.
It gives the same message on every instance.

**Comment by andreaordonselli** [comment]
Can you attach a zip file with your project?

**Comment by stalefish57413** [comment]
Thanks for reaching out.
Since i get this error on empty projects, i cant really attach anything. I was never able to even get the processing-dialog to show up.
I can send you a random populated project from my drive since they all output the same error an empty one does, but i don't think that would be of any help

**Comment by andreaordonselli** [comment]
What QGIS version you have installed?

**Comment by tomchadwin** [comment]
To be fair, although it should not crash, exporting an empty project is not the most common of uses for the plugin.

**Comment by stalefish57413** [comment]
3.38.3
although i also tried it on a computer with a brand new 3.40 version for the same effect.

**Comment by stalefish57413** [comment]
> To be fair, although it should not crash, exporting an empty project is not the most common of uses for the plugin.

Well the description said that one should reduce the complexity of the problem as much as possible. I get this error on every project i try to export and exporting an empty project is the least complex occurence of the problem.

**Comment by tomchadwin** [comment]
Ah, I understand. Apologies for my comment, in that case, and thanks for making every effort to simplify the issue.

**Comment by tomchadwin** [comment]
Oh, and forgive me for not registering precisely what you were doing. The processing provider and algorithm have not been working for some time, I'm afraid - only the manual GUI-based method of exporting works.

**Comment by stalefish57413** [comment]
Ah interesting. I was not aware. Thank you

**Comment by andreaordonselli** [comment]
We talk about it here https://github.com/qgis2web/qgis2web/issues/730
