### ISSUE TITLE
Escaping ' character in Title [SOLVED]

### ISSUE THREAD

**Issue by Awbmilne** [qgis2web/qgis2web#1114]
The project title appears to be copied directly into an HTML string in the javascript. The string is wrapped with the ' character, causing the use of ' inside the project name  to break the `index.html`.

Here is an example of the outputted Title chunk from `qgis2web.js`:
```javascript
//title

var Title = new ol.control.Control({
    element: (() => {
        var titleElement = document.createElement('div');
        titleElement.className = 'top-right-title ol-control';
        titleElement.innerHTML = '<h2 class="project-title">My Project Title</h2>';
        return titleElement;
    })(),
    target: 'top-right-container'
});
map.addControl(Title)
```

If the project's title is changed from

> My Project Title

to

> My Project's Title

the `index.html` is ultimately broken and the page does not load.

Im not sure how the data is handled, but It would be nice if all allowable QGIS characters are usable in the field.

Thanks for the help!
This is a very very useful plugin and it is an absolute blessing!

**Comment by andreaordonselli** [comment]
Hi, thanks for your feedback. I am aware of the problem and it will be fixed in the next releases, for now write by hand:

```javascript
        titleElement.innerHTML = "<h2 class='project-title'>My Project's Title</h2>";
```
