### ISSUE TITLE
Enabling saving export configuration

### ISSUE THREAD

**Issue by avikla** [qgis2web/qgis2web#1118]
I use the latest version of QGIS and qgis2web. It would be great to save the configuration before exporting the map data.

**Comment by avikla** [comment]
Thanks, Andrea, but the popup configuration has not been saved. In addition, sometimes the user needs to save more than one configuration for different web maps.

**Comment by andreaordonselli** [comment]
To memorize the "popup" options I will let you know.
To have several configs you need to create more QGIS projects

**Comment by andreaordonselli** [comment]
Next release will save the Popups option for each layer

**Comment by andreaordonselli** [comment]
In version [3.24.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.24.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.

**Comment by avikla** [comment]
request for coffee was accomplished
