### ISSUE TITLE
Popup disappears when trying to hover

### ISSUE THREAD

**Issue by avikla** [qgis2web/qgis2web#1119]
Here is a screencast of a disappearing popup when trying to click a link field inside it.

https://github.com/user-attachments/assets/8d8adb05-c0e6-4ae2-bf2c-c8902ef37b13

Using QGIS 3.40 and the latest qgis2web version.

**Comment by andreaordonselli** [comment]
Hi, if you need to select the content of the popup you have to export the project without the option "popup on hover"; disable it in the "Appareance" tab of the plugin

**Comment by avikla** [comment]
Thanks, your reply solved the problem
