### ISSUE TITLE
Add option to open folder on export instead of opening browser

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#296]
I think this would be more useful for some people, and could be the default behaviour for Macs which fail to open the browser anyway.

**Comment by tomchadwin** [comment]
Will work around #64.

**Comment by tomchadwin** [comment]
I think a dropdown would be good for `Action on export to folder`: Open in browser, Open export folder, None.

**Comment by tomchadwin** [comment]
Not sure how this will work with @nyalldawson's recent separation of the exporters.

**Comment by nyalldawson** [comment]
@tomchadwin should be relatively straightforward. You'd need to:

1. change the folder exporter configure method to use a dialog instead of the current directory picker, and add the option in there
2. make sure all the handling of the auto-browser-open is done in the exporter, and not in the dialog
