### ISSUE TITLE
QGISServer wms layers on OL3

### ISSUE THREAD

**Issue by stefan-simon** [qgis2web/qgis2web#306]
Hi,

when a layer url is server_url/qgisserver.fcgi?map=/location_to_qgs/proj.qgs,
in js code, "map=.." is encoded lyke "map%3D..." and this is causing error and
the qgis wms layer is not loaded

thanks,

Stefan

**Comment by tomchadwin** [comment]
OK. My testing was with Geoserver. I have no experience with QGIS server. What is the error?

**Comment by stefan-simon** [comment]
Actually is not an error, is an wrong answer from qgis server.
Ex:

var lyr_layer_one = new ol.layer.Tile({
                        source: new ol.source.TileWMS(({
                          url: "http://11.22.33/cgi-bin/qgis_mapserv.fcgi?map%3D/var/home/project.qgs",
                          params: {"LAYERS": "layer%20one", "TILED": "true"},
                        })),
                        title: "layer one",
                        
                        
                      })
we have to change %3D with =
and %20 with ' ' (space character)

If we alter the url to: http://11.22.33/cgi-bin/qgis_mapserv.fcgi?map=/var/home/project.qgs and
layers param to: layer%20one  we get the expected result: the layers are displayed in OL map.

Thanks,
Stefan

**Comment by tomchadwin** [comment]
Ah, thanks for figuring this out so quickly. Nice one! So I need to be able to detect when a Web services layer is from QGIS, and unencode those characters. If I search for `qgis_mapserv` in the layer address, will that do it?

**Comment by tomchadwin** [comment]
Looks like we'll have to query the server to find out:

http://lists.osgeo.org/pipermail/qgis-developer/2016-July/043717.html

Thanks, @elpaso, for the pointer.

**Comment by stefan-simon** [comment]
to check the project settings is a nice one :) . good luck..
