### ISSUE TITLE
Improve OL3 clustering

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#333]
Use https://github.com/webgeodatavore/supercluster/tree/ol3-version if it is ready for production.

**Comment by tomchadwin** [comment]
I forgot about this, @olakov. I believe it's an OL implementation of the same clustering algorithm that Leaflet exports use. Might be worth a look. Don't know if it's compatible with OL4.

**Comment by OlaKov** [comment]
Hmm it says a work in progress... I'll try it with my map and see what happens..
