### ISSUE TITLE
Popup fields GUI widgets too far to the right

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#440]
At the moment, the popup field widgets are to the right of the longest layer name. They need to be pulled over to the left, but this bit of the code makes my head hurt, and I'm not having any joy getting it done.

**Comment by tomchadwin** [comment]
The issue is that it is using the same TreeWidget as the parent layer. It needs to be nested instead, but I'm not having any joy achieving that.

**Comment by boesiii** [comment]
Could you somehow set the width of the column containing the layer name to a shorter distance and have it expand if needed?

**Comment by tomchadwin** [comment]
I think that would lose us now than we would gain. The layer title is primary.

**Comment by boesiii** [comment]
What if the popup fields were not children of Popup Fields but children of the layer and add a few spaces at the beginning to make them appear indented.  See mockup below.

![popup fields](https://cloud.githubusercontent.com/assets/2079638/24374639/9b250fea-1303-11e7-97e2-686b06784b5d.PNG)

**Comment by tomchadwin** [comment]
I think the issue is that they are not children of "Popup fields", and are not even children of the layer. They are *siblings* of the layer(s). That's why they are aligned to the same grid, rather than an embedded (ie child) grid.

**Comment by tomchadwin** [comment]
Perhaps this screenshot will make the issue clear:

![popups](https://cloud.githubusercontent.com/assets/7840213/24454068/3e82949e-1482-11e7-9c91-ef4eeea8bb84.png)

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

Best regards.
