### ISSUE TITLE
Separate HTML/JS in Leaflet output? 

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#496]
Following on from @Frederikssund's #495, should we consider separating the Leaflet HTML and JS (and CSS)?

Pro:
1. Traditionally good practice
2. Easier validation 
3. Matches OL export
4. More modular code

Con:
1. More HTTP requests (less important as HTTP2 becomes more prevalent)
2. Harder to embed in other pages/upload to a CMS
3. Modern best practice these days is toward separation of concerns, not separation of languages

What do others think?

**Comment by Frederikssund** [comment]
Another "nice to have" feature is that link, script and style tags should be nicely formatted.

Example from the qgis2web generated html-file:
```
         <link rel="stylesheet" type="text/css" href="css/qgis2web.css">
         <link rel="stylesheet" href="css/MarkerCluster.css" />
```
Should be:
```
         <link rel="stylesheet" type="text/css" href="css/qgis2web.css" />
         <link rel="stylesheet" type="text/css" href="css/MarkerCluster.css" />
```
Ie. explicit type definitions in link, script and style tags and proper closing of empty tags

ad. 1) Local caching on the client already helps 
ad. 2) There is a lot of includes already, so a couple more doesn't matter.
ad. 3) I'm an old fart. The combination of html, css and javascript in one file hurts my eyes and brain (really professional, I know)

**Comment by tomchadwin** [comment]
Aren't both closing empty tags and the type property for scripts and stylesheets only mandatory for XHTML, not HTML5?

**Comment by tomchadwin** [comment]
OK, I'd confused a couple of issues. Tidying up now, according to my best understanding of HTML5.
