### ISSUE TITLE
Vector tiles

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#566]
Investigate whether we can detect layers from https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin, and then export them natively in OL, and via https://github.com/Leaflet/Leaflet.VectorGrid.

**Comment by tomchadwin** [comment]
OK, first attempt at this is now in master:

- install QGIS plugin "Vector Tile Reader"
- use Vector Tiles Reader to load one of the server-based datasets (OpenMapTiles or Mapzen)
- export via qgis2web

Limitations:
- Leaflet export only at the moment (no OpenLayers yet)
- qgis2web preview doesn't work (and won't - I guess L.VectorGrid is incompatible with QtWebkit)
- in the Vector Tiles Reader dialog, don't select "Apply predefined OpenMapTiles style" (causes a JS error I don't yet understand)

Have a go and let me know if you have any success (ping @mnboos, @sfkeller, @nvkelso, @jachym). Early stages only.

**Comment by tomchadwin** [comment]
Vector Tiles Reader splits the VT source into multiple QGIS layers. qgis2web recombination them back into one, but with the styles which were assigned to each layer.

Other limitations:
- no popups
- no labels

**Comment by tomchadwin** [comment]
> Vector Tiles Reader splits the VT source into multiple QGIS layers. qgis2web recombines them back into one, but with the styles which were assigned to each layer.

The obvious result of this approach is that if you add a VT layer group via Vector Tiles Reader, and then add other non-VT layers in amongst the VT layers, that interleaved z-index will not be honoured in the webmap.

The alternative would be my initial approach, to create separate layers from each VT layer returned by the server, but that leads to HTTP requests for each tile for each layer, which is inefficient to the point of unusability. Add to that the fact that each discrete layer would actually contain the data for all the others as well, and the whole thing would grind to a halt.

**Comment by tomchadwin** [comment]
I've now got bare-bones OL export working locally,   but unstyled. I'll try to get styles working and then commit tomorrow.

**Comment by tomchadwin** [comment]
Two remaining issues:

1. The VT layers have different layers each for point, line, and poly, but since they have the same layer name, these styles overwrite each other

2. Because the VT loader plugin dynamically adds and removes layers at different zoom, levels, qgis2web only exports layers present at the current zoom

**Comment by sfkeller** [comment]
Ad 1. I realize now, that in fact some VT layers have the same name within the same group (= at same level of of Layers Panel) e.g. water_name with points and water_name with linestrings. That maybe work with browser viewers, but seems inconveniend for GIS and I wonder why QGIS accepted this.

@mnboos : Is it possible to add "_p", "_l" and "_a" to the layer names for point, linestring and area/polygon?

Ad. 2. Why is it an issue that the layers present at current zoom are exported? You know, VT sources indicate a max_level (which is e.g. 14 for Mapbox and OpenMapTiles). But this means, that you export 268,435,456 tiles (according to https://wiki.openstreetmap.org/wiki/Zoom_levels ) when the user currently looks at whole world.

**Comment by tomchadwin** [comment]
@sfkeller I've fixed 1 in OpenLayers output. Styling is dkne by a JS function which is called with features as an argument. I just put a check for the geometry type into the function, and I think it now works. I've not had a chance to look at the L.VectorGrid output to sort this issue for Leaflet exports yet, but I shall soon.

2. The exported VT object is just a single connection to a URL. `ol.format.MVT` handles the individual tile requests for each extent/zoom level. L.VectorGrid does the same for Leaflet. In other words, including an *unstyled* VT layer in a webmap is just one line of code (roughly speaking). The reason I need all layers in the QGIS layers list at all times is so that I can loop through then all to extract their styles and export them as JS. If some layers are not present when the map is exported, they can't have their styles extracted. 

Hope this makes sense.

**Comment by mnboos** [comment]
Adding postfixes to the layers should not be a big problem.

@tomchadwin I'm curious how you export the styles. How do you map the min/max scale conditions to the web map, i.e. pixels?

**Comment by tomchadwin** [comment]
@mnboos

> How do you map the min/max scale conditions to the web map, i.e. pixels?

The QGIS API exposes the scale-dependent min and max, and birth Leaflet and Openlayers accept them as parameters in layer constructors.

> mapping the Mapbox pixels (e.g. line-width) to QGIS map units

I've just had to do it the other way round (QGIS MapUnits to pixels. There's an easy formula for EPSG:3857, but if you support other projections, it seems you have to plot two points a known pixel distance apart and measure the geographic distance between them to get your ratio. Will find the link.

**Comment by tomchadwin** [comment]
Here you go:

```javascript
function newM2px() {
    var centerLatLng = map.getCenter();
    var pointC = map.latLngToContainerPoint(centerLatLng);
    var pointX = [pointC.x + 100, pointC.y];
    var latLngC = map.containerPointToLatLng(pointC);
    var latLngX = map.containerPointToLatLng(pointX);
    var distanceX = latLngC.distanceTo(latLngX)/100;
    reciprocal = 1 / distanceX;
    m2px = reciprocal;
}
```

**Comment by mnboos** [comment]
> I've just had to do it the other way round (QGIS MapUnits to pixels. There's an easy formula for EPSG:3857 [...]

Would love to see the formula.

**Comment by tomchadwin** [comment]
Is here:

http://wiki.openstreetmap.org/wiki/Zoom_levels

Section:

**Comment by tomchadwin** [comment]
Coming back to the issue of multiple layers with the same name in each group (one for each geometry type)...

As I say, I think I've solved it for OpenLayers. However, I don't think there's a way to detect the geometry type in L.VectorGrid. I've asked here https://github.com/Leaflet/Leaflet.VectorGrid/issues/125.

I think adding the _p/_l/_a suffix might therefore be helpful after all. Apologies.

**Comment by tomchadwin** [comment]
> I think adding the _p/_l/_a suffix might therefore be helpful after all. Apologies.

Actually, no, it won't. The Leaflet webmap reads the remote VT source directly, so that's where is gets its layers from, and therefore its layer names. The QGIS layer names are never used in the styles.

OK, I don't think I have a solution for this yet.

**Comment by tomchadwin** [comment]
Thanks to @IvanSanchez's solution in https://github.com/Leaflet/Leaflet.VectorGrid/issues/125, there should be a way to achieve this now. It's still going to take some work, as I have to group and order VT layer styles very specifically (the *order* of styles becomes important in this case) and very differently to how the plugin works for other layer types.

I also haven't yet implemented geographic units in OL, which will definitely be required.

Getting closer, though...

**Comment by tomchadwin** [comment]
OK, styling now works in Leaflet as well (ie point 1 above). I just need to get mapUnits working OL, and this might be ready to go.

**Comment by nvkelso** [comment]
Great to see all your progress on this :)

**Comment by tomchadwin** [comment]
Thanks! It's been a lot of work (and not the easiest), but I like the idea of a codeless method for restyling MBVTs and combining them with other data via QGIS.

**Comment by tomchadwin** [comment]
MapUnits now working in OL (at least for stroke width - marker size still to do, but that's less important, I think).

**Comment by tomchadwin** [comment]
Right, I think this is now tentatively working. No labels or popups/interactivity, so effectively basemapping only, but it should broadly work.

I think that there might be an error in OL when you click on the map - I'll look into it.

**Comment by tomchadwin** [comment]
Ack. Spoke too soon. OL throwing errors.

**Comment by tomchadwin** [comment]
OK, one OL error fixed. Looks like there's another to deal with, though.

**Comment by tomchadwin** [comment]
I'm getting a permissions error when I export an MBVT layer stack with SVGs:

1. Add OpenMapTiles with styling
2. Zoom in until the `moutain_peak` SVGs appear
3. Export with qgis2web

```
2017-11-24T18:44:24	1	Traceback (most recent call last):
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\maindialog.py", line 336, in saveMap
			    feedback=self.feedback)
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 100, in write
			    folder=dest_folder)
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 270, in writeLeaflet
			    useShapes, useOSMB)
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 98, in writeVectorLayer
			    outputProjectFileName, useShapes)
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletStyleScripts.py", line 117, in getLayerStyle
			    layer_alpha, sln, sl)
			  File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletStyleScripts.py", line 196, in getSymbolAsStyle
			    rotationAngle: %s,
			  File "C:\OSGEO4~1\apps\Python27\lib\shutil.py", line 119, in copy
			    copyfile(src, dst)
			  File "C:\OSGEO4~1\apps\Python27\lib\shutil.py", line 82, in copyfile
			    with open(src, 'rb') as fsrc:
			IOError: [Errno 13] Permission denied: u'C:/Users/tchadwin'```

**Comment by tomchadwin** [comment]
Nope, never mind - seems to affect all SVGs. Will look into that separately.

**Comment by mnboos** [comment]
I assume it's because the qgis2web plugin is not allowed to access arbitrary folders (in this case 'C:/Users/tchadwin').

**Comment by mnboos** [comment]
Maybe it helps adding the folder to the QGIS lookup paths and only refer the svg by name:

https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/vtr_plugin.py#L467-L473

**Comment by tomchadwin** [comment]
Not sure. I am certainly getting ? for all the POI SVGs - I assume that's not correct.

**Comment by mnboos** [comment]
That's because the icon could not be found. Did you restart QGIS after adding the paths?

**Comment by tomchadwin** [comment]
You mean after loading the MBVTR layers?

**Comment by mnboos** [comment]
No, only once after adding the svg path to the QGIS lookup paths.

Von: Tom Chadwin [mailto:notifications@github.com]
Gesendet: Samstag, 25. November 2017 10:43
An: tomchadwin/qgis2web <qgis2web@noreply.github.com>
Cc: Martin Boos <mboos@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [tomchadwin/qgis2web] Vector tiles (#566)


You mean after loading the MBVTR layers?

**Comment by tomchadwin** [comment]
Perhaps we're talking at cross-purposes. I've never explicitly added to the QGIS lookup paths.

**Comment by tomchadwin** [comment]
But a restart of QGIS has made this error disappear. Very odd.

**Comment by tomchadwin** [comment]
Right, after that false start, I think it is tentatively working again. So the process is as follows:

1. Load MBVTs via Vector Tiles Reader
2. Zoom/pan until you have all the MBVT layers you want loaded
3. Export via qgis2web

Notes:

1. No labels/text/popups/interactivity
2. If you get a blank map, and a "Permission denied" error in the qgis2web QGIS log, try restarting QGIS (and let us know, whether that works or not)

Feedback would be really useful, so do let us know how it works for you.

**Comment by tomchadwin** [comment]
Labelling now works in OpenLayers. However, some of the expression functions used by MBVTR are not yet implemented (such as `coalesce()`). Simplify those to plain fields to get it to work.

**Comment by tomchadwin** [comment]
Labelling not yet possible in Leaflet.

**Comment by tomchadwin** [comment]
Issue with error on click in OL now fixed. Remaining essential issues:

1. Leaflet - hide geometry for label-only layers
2. Leaflet labels

Desirable (but not sure how to achieve):

- Popups

**Comment by tomchadwin** [comment]
I have the beginnings of some code for Leaflet labels and popups, but only hacked into an exported Leaflet webmap. Next I have to code it into qgis2web.

No idea on OL popups yet - I think the OL VT implementation doesn't bring across properties (correct me if I'm wrong), so I need to find out whether there is some AJAX-based equivalent of WMS `GetFeatureInfo`.

**Comment by tomchadwin** [comment]
Leaflet labels: after a lot of pondering and wrangling, with considerable help from @perliedman, I'm reaching the conclusion that this is not going to be possible. There is a PR for Leaflet.VectorGrid which allows labelling (https://github.com/Leaflet/Leaflet.VectorGrid/pull/68) which I've updated to work against current master. It works, but it requires the MBVTs to have a field unique to each untiled feature. Without this, each fragment of a feature in each tile is labelled.

This is what happens with Leaflet.VectorGrid dynamic styling, but it's largely not noticeable because of the nature of the visual change made to the map. Text for labelling is a different matter: because text relies heavily on antialiasing, labels on  top of identical labels darken and blur. Add to this the fact that one is obviously adding processing overload to handle these multiple unwanted label copies, and it's a non-starter.

Even if a property unique per feature exists, as it does in some MBVTs (often `osm_id` or something derived from it), we cannot automatically detect which the unique field is, so to get it to work, we'd have to get the user to specify it. All in all, I think this tips the balance away from this being doable.

It's a shame, as Leaflet.VectorGrid does the job for geometry. So, I'll leave it in place, but labelling won't happen. Users will have to add a non-MBVT QGIS label layer.

**Comment by tomchadwin** [comment]
Perhaps @perliedman has just solved the issue. If we reapply Labelgun to stop overlapping, it will also by definition get rid of duplicate labels. We're already using Labelgun for GeoJSON layers, so *why didn't I think of that?*
