### ISSUE TITLE
Remove layer visible option from layer settings

### ISSUE THREAD

**Issue by boesiii** [qgis2web/qgis2web#569]
I think the "Visible" layer setting should be removed and get the layer visibility from Qgis.  You mentioned this in #456 but that was closed.

**Comment by tomchadwin** [comment]
Isn't that confusing visibility with presence in the export, or availability to export? I suppose we could get rid of visibility, and therefore always export all layers in the QGIS project. It's a big change, though. What do you think?

**Comment by tomchadwin** [comment]
Isn't that confusing visibility with presence in the export, or availability to export? I suppose we could get rid of visibility, and therefore always export all layers in the QGIS project. It's a big change, though. What do you think?

**Comment by boesiii** [comment]
I am only considering my workflow, which not be best.  When I prepare a project for using Q2W, I only have layers in my project file that will be exported, I typically remove any unnecessary layers.  The more I think about it I guess it may be better to leave it as is.

**Comment by tomchadwin** [comment]
No, you've been contributing to this plugin long enough to know that I relish the removal of functionality which QGIS can handle itself, and I also relish simplification of the qgis2web GUI. I therefore do think this is worth considering.
