### ISSUE TITLE
Customization of popup field

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#605]
I am trying to change the visual aspects of the popup fields by changing the code.
In Leaflet, header label, I would like to see the relative value centered. So the field name is aligned left and the value which comes on the second line (after the line-break 'br') is aligned center.

However, I have no luck and too little understanding of code to get this done. I can change the alignment but it always applies to both parts of the cell: before and after the line-break 'br'.

Any tips for me?

And is it possible to add customization options to the popup field? It is now 'no label, header label, or inline label' and I would like to have this alignment functionality as an option.
Also the possibility to choose a background colour for the popup field would be nice.

**Comment by tomchadwin** [comment]
I don't think there's an easy way to achieve what you want as things stand, and I'm not keen on cluttering the plugin GUI to add such options. However, if I were able to add CSS classes to the popup, you'd then be able to add whatever CSS rules you want. I'll look into this.

**Comment by touruyo** [comment]
I'd like to accomplish this as well by making the attributes appear like a table with field value on the left and description on the right. @tomchadwin were you able to look into the issue? Thanks

**Comment by andreaordonselli** [comment]
I have just released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which significantly changes the appearance of the popup discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
