### ISSUE TITLE
Processing algorithms not migrated

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#609]
I don't think the Processing algorithms are appearing. The provider is there, and I don't see any errors logged, but no algorithms. I can't find good docs for this particular change to QGIS3.

**Comment by tomchadwin** [comment]
OK, trying to copy https://github.com/alexbruy/processing-taudem. Making some progress, but I think the API seems to have changed a good deal.

**Comment by tomchadwin** [comment]
I think the algorithms are now loading correctly into a group. Nothing happens when you try to run them, though. Nothing at all - I don't see any errors anywhere. There must be more Processing API changed I haven't yet understood and implemented.

**Comment by tomchadwin** [comment]
Can you figure out why the qgis2web processing algorithms don't seem to do anything when double-clicked, @alexbruy? Provider and algorithms are here:

https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/qgis2webProvider.py
https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/qgis2webAlgorithm.py

**Comment by tomchadwin** [comment]
@wonder-sk at the FOSS4GUK codesprint has figured out the problem. I had implemented the API changes for processing algorithms, but I had left in an old method which I thought was not used (`id()`). It turns out that was overwriting another method. Also, I had not implemented `createInstance()` which is required (is that an API break which is not documented at https://qgis.org/api/api_break.html#qgis_api_break_3_0_Processing?).

The algorithms now run. They fail, but they fail with error messages, so we can now make some progress. I've not committed yet, but will do so if I can make more progress.

**Comment by shivareddyiirs** [comment]
While export project is working. It does not ask for export directory and export to default address. Is this intended? I feel user should be asked the destination folder or FTP location.

**Comment by andreaordonselli** [comment]
@tomchadwin Is this issue still valid or can I close it?
