### ISSUE TITLE
Use leaflet-heatmap  instead of leaflet-heat library.

### ISSUE THREAD

**Issue by havran** [qgis2web/qgis2web#634]
Hi. Leaflet.heat do good job, but sometimes we need something more flexible. I want share my experience with use alternative heatmap library for job.

My wife trying use heatmap with bunch of points (about 30k) and in global map view, with all points make big red area (default output from qgis2web):

![image](https://user-images.githubusercontent.com/326530/38185455-6b1ac69a-364e-11e8-9773-bf5753900aa0.png)

We want more detailed view, then I try implement leaflet-heatmap.js and we get much better result (with "scaleRadius": true):

![image](https://user-images.githubusercontent.com/326530/38185467-76f120f4-364e-11e8-8537-3c06769ec3f9.png)

Implementation is relatively simple:

I created directory `js-extra` and add libraries (from https://github.com/pa7/heatmap.js):

```html
        <!-- Heatmap JS -->
        <script src="js-extra/heatmap.js"></script>
        <script src="js-extra/leaflet-heatmap.js"></script>
```

Find line on which heatmap data and new heatmap layer are generated with fuction  `geoJson2heat()` and replace this lines with new code:

For example in my output:

```javascript
        var centroids_1_hm = geoJson2heat(json_centroids_1,
                                      '');
        var layer_centroids_1 = new L.heatLayer(centroids_1_hm, {
            attribution: '',
            radius: 40,
            max: 1,
            minOpacity: 1,
            gradient: {0: '#fef0d9', 0.25: '#fdcc8a', 0.5: '#fc8d59', 0.75: '#e34a33', 1: '#b30000'}});
```

is replaced by:

```javascript
        var centroids_1_hm = {
            max: 8,
            data: geoJson2heatmapJs(json_centroids_1, '')
        };

        var cfg = {
            // radius should be small ONLY if scaleRadius is true (or small radius is intended)
            // if scaleRadius is false it will be the constant radius used in pixels
            "radius": 0.002,
            "maxOpacity": .5,
            // scales the radius based on map zoom
            "scaleRadius": true,
            // if set to false the heatmap uses the global maximum for colorization
            // if activated: uses the data maximum within the current map boundaries
            //   (there will always be a red spot with useLocalExtremas true)
            "useLocalExtrema": true,
            // which field name in your data represents the latitude - default "lat"
            latField: 'lat',
            // which field name in your data represents the longitude - default "lng"
            lngField: 'lng',
            // which field name in your data represents the data value - default "value"
            valueField: 'weight'
        };
        var layer_centroids_1 = new HeatmapOverlay(cfg);
        layer_centroids_1.setData(centroids_1_hm);
```

Beware of correct use of variables names. 

And finally replace original method for generating data `geoJson2heat()` to function `geoJson2heatmapJs()`:

For example original function:

```javascript
        function geoJson2heat(geojson, weight) {
          return geojson.features.map(function(feature) {
            return [
              feature.geometry.coordinates[1],
              feature.geometry.coordinates[0],
              feature.properties[weight]
            ];
          });
        }
```

is replaced by:

```javascript
        function geoJson2heatmapJs(geojson, weight) {
            return geojson.features.map(function(feature) {
                return {
                    lat: feature.geometry.coordinates[1],
                    lng: feature.geometry.coordinates[0],
                    weight: feature.properties[weight]
                };
            });
        }
```

And here is result:

![image](https://user-images.githubusercontent.com/326530/38186409-361e15fa-3653-11e8-939e-6eb6dd1d937e.png)
![image](https://user-images.githubusercontent.com/326530/38186419-41c27086-3653-11e8-86f3-6269052e6644.png)

Thats all, thank for good work!

**Comment by tomchadwin** [comment]
Thanks for this! I feel that the original implementation used to work better, but agree that it seems not to produce correct output these days. I need to investigate why. But thanks again!

**Comment by andreiasgusmao** [comment]
@havran, 
I generated a heat map with qgis2web and showed nothing in the visualization. Could you provide this complete sample code? I tried with your tips, but I still didn't succeed. Thanks

**Comment by jnrdhn** [comment]
he, I'm trying to use leaflet-heatmap in a react app but it doesn't seem to recognize the model :(
![image](https://user-images.githubusercontent.com/68679694/221492447-0c7fcbf2-0b40-4f24-9ae1-4e4f8e537a44.png)

**Comment by ZaheerNiazi007** [comment]
@jnrdhn  you have to import before Lealflet
