### ISSUE TITLE
TopoJSON format

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#652]
Alternative to current GeoJSON only export. Discussed in #171.

**Comment by mb72** [comment]
When do you think this will be available as an option?

**Comment by tomchadwin** [comment]
I'm afraid no-one is working on this at the moment, so there is no timescale. All contributions are welcome.

**Comment by tomchadwin** [comment]
If you mean you'd create the TopoJSON manually yourself, then it shouldn;t be a big deal: just change `layers/layers.js` to replace `new ol.format.GeoJSON();` with `new ol.format.TopoJSON();`. **Note**: Remember that all JSON must be saved as JSONP.

**Comment by mb72** [comment]
What's the easiest way to save it as JSONP?

**Comment by tomchadwin** [comment]
Assign the JSON to a js variable:

```javascript
var your_topojson_layer_name = "PUT_YOUR_TOPOJSON_HERE";
```

If you do a normal qgis2web export, have a look at one of the generated layer files, and you'll see how it works. The variable name that you choose is the one then used in the main script to refer to your data.
