### ISSUE TITLE
Wrong Template location i Help in QGIS 3 version

### ISSUE THREAD

**Issue by magerlin** [qgis2web/qgis2web#668]
The help page states:

Select HTML template for webmap - add your own templates to the /qgis2web/templates directory in your .qgis2 folder 

The right QGIS 3 folder is
C:\Users\Username\AppData\Roaming\QGIS\QGIS3\profiles\default\qgis2web\templates

**Comment by magerlin** [comment]
As far as I can see help page stil only tells about Qgis 2 location?

Template 
Select HTML template for webmap - add your own templates to the /qgis2web/templates directory in your .qgis2 folder

**Comment by tomchadwin** [comment]
Ah, I fixed in the README/repo home page, but not in the wiki. Thanks - will fix.

**Comment by tomchadwin** [comment]
Now fixed on repo home page and wiki

**Comment by tomchadwin** [comment]
Released as 3.5.0 and pushed to QGIS plugins repo.

**Comment by magerlin** [comment]
Hope not being a p... in the a...

Wanted to make a new template (using QGIS3) , could not remember loaction of templates. Opened the Help tab in qgis2web (latest version) inside Qgis and I am being told:

_Template 
Select HTML template for webmap - add your own templates to the /qgis2web/templates directory in your .qgis2 folder_ 

See screenshot
![screenshot 2019-02-24 18 27 51](https://user-images.githubusercontent.com/1887531/53302791-8cb2f680-3862-11e9-8a5c-0ec4a787fbc7.png)

**Comment by tomchadwin** [comment]
Ack

**Comment by andreaordonselli** [comment]
Solved in new wiki section
