### ISSUE TITLE
Labels (background) in leaflet change shape and position

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#687]
Hi Tom,

Using qgis 2.18.23 and qgis2web 2.34.0 I noticed both the preview and export changes my label design and position using Leaflet.
The label is build using Background, shape: circle and Position: around centroid and the option Force placement point within polygon checked. That last one is important to me, otherwise labels will be placed outside the polygon and thus visually refer another polygon.

qgis2web changes the shape to rectangular with the width following the size of the labeltext and disregards the Position settings.

I have time to test possible solutions, but I have little to none experience with coding.

**Comment by Jeroen-GroeneBij** [comment]
Hmm, that is a pity.
I will try to see if I can manually change some code in the export files if I can find the specific settings.

Your plugin is helping me a lot. I think being able to create webmaps is one of the most important features in GIS software. And having the full possibilities of visual styles exported to a webmap is key in that.
Do you think qgis 3 will offer improvements in creating webmaps?

**Comment by tomchadwin** [comment]
> Is it possible to use marker?

The problem is that tooltips are the correct way to label in Leaflet, and trying to recreate the functionality they can provide by another means seems possibly unwise. What I don't know is whether tooltips can contain HTML rater than just plain text. If so, that could help.

**Comment by Jeroen-GroeneBij** [comment]
Why should tooltips be able to contain html? Would that help in rendering them differently?

**Comment by tomchadwin** [comment]
Forget what I said - speaking nonsense. For fuller control over L.Tooltip appearance, we would want to apply a CSS class as a styling hook and convert QGIS styles to CSS.
