### ISSUE TITLE
openlayers export: missing title / basemap names wrong / svg problems

### ISSUE THREAD

**Issue by jukos** [qgis2web/qgis2web#702]
Hello,
I recognized different things: (preview=after export / browser)

1. Missing map title
![grafik](https://user-images.githubusercontent.com/31866672/49338675-e7063780-f624-11e8-9a50-23074a40823b.png)

2. Wrong names for the basemaps
export deletes space character, and adds "_0" / "_1"
![grafik](https://user-images.githubusercontent.com/31866672/49338733-fb96ff80-f625-11e8-9947-2ff1e408a11d.png)

3. SVG problems
Export from svg confuses me.
An example: If I use three svg marker from standard qgis installation (not imported other svg) I get an empty map.
![grafik](https://user-images.githubusercontent.com/31866672/49338765-c63ee180-f626-11e8-8ea6-46eaa50b2084.png)

Are there plugin issues?

Thank you and greetings, Jürgen

QGIS 3.4.2
qgis2web 3.4
Windows 10
Firefox

**Comment by boesiii** [comment]
The map title should be shown in the tab of the browser.
![capture](https://user-images.githubusercontent.com/2079638/49380426-a9b2b000-f6df-11e8-9de6-3e62dc5ee690.PNG)
I don't know why the basemap names are renamed but I see the same on my system.

Can you include include more details about your SVG layer and include your project date so we can test?

**Comment by jukos** [comment]
Thank you for response. I have tested with a new test project.
1. I think it is better to have a title within the map, also in leaflet. Tab info is good, but only additional.
3. In my new test i can not fully response the result.
- with svg from qgis is now ok
- but with svg from https://openclipart.org/ I get an empty page
I put these svg in a new file, example:
C:\Program Files\QGIS 3.4\apps\qgis\svg\svgopenclipart\wait.svg

Greetings

**Comment by boesiii** [comment]
To have a title in the main map you will have to create you own template, similar to this post  https://github.com/tomchadwin/qgis2web/issues/415

**Comment by boesiii** [comment]
I grabbed an SVG from the openclipart page and was able to get a map exported but the SVG did not look right.  Can you specify the SVG you used or attach some of your files that you used in the project.

**Comment by jukos** [comment]
SVG:
OK. Also tested with MAKI Symbols from https://www.mapbox.com/maki-icons/ : no problems
It seems, as if the svg from openclipart are different.
I used these svg from openclipart:
[svg openclipart.zip](https://github.com/tomchadwin/qgis2web/files/2643021/svg.openclipart.zip)

I will try to find out, what are the reason.....

Thank you and greetings, Jürgen

**Comment by tomchadwin** [comment]
1. No, not supported in OpenLayers output. Supported in Leaflet, as Leaflet has a simple title control to achieve it.

2. Hopefully now fixed in master. I'd be grateful if you or @boesiii could test and report back.

3. Will investigate, but I've experienced problems with some SVGs in the past, and not been able to find a solution.

By the way, please would you mind not reporting multiple different issues in one ticket? It makes managing fixes harder. Thanks very much.

**Comment by boesiii** [comment]
Tom, I confirm that 2 is fixed in master.

**Comment by tomchadwin** [comment]
Thanks, @boesiii. Released as 3.5.0 and pushed to QGIS plugins repo.

**Comment by jukos** [comment]
Perfect!
Ok, only one issue in one ticket. Excuse me.

**Comment by andreaordonselli** [comment]
The issues mentioned in this issue should all have been resolved over time.
The latest update has also activated the ability to manage Title and Abstract for openlayers export.
Here is the [release](https://github.com/qgis2web/qgis2web/releases/tag/v3.21.0) already downloadable via the QGIS plugin repository

I close the issue hoping to have solved everything.
Thank you for using the plugin.
