### ISSUE TITLE
Preview / Export appears Blank

### ISSUE THREAD

**Issue by jtolar2** [qgis2web/qgis2web#706]
Hi all,

I am new to QGIS, and have been assigned a task of marking out all trees in a certain area of land, and subsequently converting this map to a html file.

I have learnt what I believe are the basic skills of QGIS needed to complete this task (through https://www.youtube.com/watch?v=aLmMovuydqI), and have opted to use the qgis2web plugin to handle the conversion.

Within the qgis2web plugin, when I go to 'Update preview' or 'Export', a blank screen is produced save for some navigational buttons. I would like to please learn how to overcome this, so that I may begin generating maps to provide to my colleagues in html form.

Apologies for the rudimentary nature of this question! 

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

I am using version:
- 2.34.0 of the qgis2web plugin
- QGIS 2.18.11

Screenshot of the output:
![qgis2web overview](https://user-images.githubusercontent.com/46802221/51360824-642c3400-1b21-11e9-84c1-59fa360e9682.PNG)

Screenshot of QGIS settings:
![qgis settings](https://user-images.githubusercontent.com/46802221/51361495-211f9000-1b24-11e9-9e69-e0598e29c26b.PNG)

I believe I've zip'ed the files correctly below:
[Example Project.zip](https://github.com/tomchadwin/qgis2web/files/2771390/Example.Project.zip)

**Comment by tomchadwin** [comment]
I can;t open your project from your zipped files - can you upload the shapefiles? Also, can you upload a zip of the exported webmap (the index.html file and all subdirectories)?

**Comment by jtolar2** [comment]
Hi Tom,

Thanks for getting back to me; let me know if the below works for you. I've:
- Made a folder for qgis2web to extract to and just .zip'ed the contents of this folder
- For the shapefiles I've right clicked a given layer, selected 'properties', clicked the 'Style' drop-down, 'Save Style', 'QGIS Layer Style File'

[Example Project r2.zip](https://github.com/tomchadwin/qgis2web/files/2777387/Example.Project.r2.zip)

**Comment by tomchadwin** [comment]
The Ocean layers's style hasn't exported properly, resulting is a malformed JS file, which prevents the page from rendering. Can you check the QGIS log messages (View > Panels > Log messages panel)? It might (should) have a qgis2web tab. If so, what is in that tab?

And I still don't have your shapefiles. You've exported your QGIS styles as QML files. I was asking for the .shp files which you added to your map/project. Looks like we can narrow it down to the Ocean shapefile.

**Comment by jtolar2** [comment]
Hi Tom,

The Log tab reads as below:
			  File "C:/Users/jtolar/.qgis2/python/plugins\qgis2web\olStyleScripts.py", line 82, in exportStyles
			    sln, size, face, color, value, geom)
			UnboundLocalError: local variable 'value' referenced before assignment

I've attached / zipped the shapefiles apologies:
[Example Project Shape Files.zip](https://github.com/tomchadwin/qgis2web/files/2809780/Example.Project.Shape.Files.zip)

Generally speaking, are there any known restrictions on what layers or shapefiles can be used by qgis2web? Whilst the 'Tortoise Island' project I've uploaded is just an example, I've noticed similar issues when trying to export certain layers (WMS layers, such as a Spookfish or an OpenLayers plugin world map) through qgis2web. Whilst this may be another issue entirely, is there a rule of thumb on WMS or inverted polygon layers not appearing during qgis2web exports? If so, perhaps in future I can migrate to using WMTS layers / stop using 'inverted polygons' to overcome this.

**Comment by tomchadwin** [comment]
Thanks for the layers - I'll take a look. As for your more general question, I can tell you straight away that inverted polygons are *not* supported, I'm afraid.

**Comment by jtolar2** [comment]
Hi Tom,

Removing the 'Ocean' layer renders the following result through qgis2web:
![image](https://user-images.githubusercontent.com/46802221/52024185-f84fbf80-2553-11e9-9fd2-9e2436f56661.png)

However I was anticipating (from QGIS) it would look more like this:
![image](https://user-images.githubusercontent.com/46802221/52024233-2503d700-2554-11e9-9064-d01b8b5e148e.png)

As such there appears to be issues rendering the:
- 'OpenStreetMap' raster layer from the 'OpenLayers Plugin'. This layer is a map of the whole world, so I'm curious if you know if it acts like an inverted polygon in anyway to qgis2web.
- 'Points' shapefile (including its subset vector layers 'Beach' and 'Tortoise'); as below:
![image](https://user-images.githubusercontent.com/46802221/52024868-78772480-2556-11e9-9ce9-f3bef01187f4.png)

Whilst there's not many feasible uses for inverted polygons, it would be great to understand how to get the 'OpenStreetMap' raster layer and custom vector layers to appear through qgis2web, as they're both critical to providing localised context in my maps for colleagues.

**Comment by tomchadwin** [comment]
The OpenLayers is no longer recommended. Try the QuickMapServices plugin (QMS) instead. I've just tested your project, replacing the OpenLayers OpenStreetMap layer with the OSM layer from QMS. That worked for me.

**Comment by tomchadwin** [comment]
Closing without feedback - comment if you want to reopen.

**Comment by jtolar2** [comment]
Hi Tom,

The QuickMapServices plugin worked great, thanks for the suggestion!

As above though, the 'pawprint' and 'B' shapefiles from the 'Points' group don't load in the qgis2web export. Are there any known issues with qgis2web processing certain shapes? i.e. should I avoid more complex symbologies?

**Comment by tomchadwin** [comment]
Many limitations, yes. Are you exporting in Leaflet or OpenLayers format?

**Comment by jtolar2** [comment]
Hi Tom,

I'm exporting in Openlayers.

**Comment by tomchadwin** [comment]
Remaining issues:

- Colouring SVGs is not supported, which is why the pawprint is coming out black. The solution is to create a coloured SVG and use that instead.
- The circle below the B marker seems to be obscuring the B.
- Font Marker symbol layers seem not to be appearing here, and I don't yet know why.
- Font size is too small.

I'll try to look at these issues.

**Comment by tomchadwin** [comment]
I've made a separate issue for the second bullet point above: #726

**Comment by TodoInTX** [comment]
Hi, this is my first time using qgis2web and I'm getting the same blank preview and output with my project.
I've switched the basemap to QMS OSM Standard, tried outputting in both OpenLayers and Leaflet and even leaving off the basemap layer altogether.

I don't see anything useful in the log panel, just a warning about     

"C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')       'U' mode is deprecated

**Comment by TodoInTX** [comment]
[VoterSuspense.zip](https://github.com/tomchadwin/qgis2web/files/3074519/VoterSuspense.zip)

**Comment by boesiii** [comment]
It looks like you are using an expression for a column in a categorized Precincts layer.  I believe this is causing your issue because it is not supported in qgis2web.  A work around would be to split your layer into two separate layers and use a feature filter.

**Comment by TodoInTX** [comment]
That was it, thanks!

**Comment by tomchadwin** [comment]
A little more detail on this issue. At a broad level, expressions are supported in qgis2web. However, the support is extremely basic:

- expressions are only supported in a few places (including labels)
- very few functions within expressions are supported

The second point is one which is ideal for contributions, for people familiar with Javascript. Take a look at https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/resources/qgis2web_expressions.js. Any function which only contains `return false` has not been implemented - as you can see there are many of them.

Obviously, geometric functions cannot be supported unless Leaflet or OpenLayers support the geometry operation in question. Beyond that limitation, some of these might be easy to write - you can see some that have been done already in that file.

If anyone would like to take a look and contribute, I'm very happy to answer any questions, and would obviously be delighted.

**Comment by TodoInTX** [comment]
Is there some reason fnc_round isn't implemented as simply "return
Math.round(values[0]);" ?

**Comment by tomchadwin** [comment]
Only that it hasn't been written. Contributions very welcome!

**Comment by Csrtlp** [comment]
Not sure if this issue is related but had the same issues (blank map) exporting WMTS layers through qgis2web/Leaflet.

Noticed the following:
When qgis2web exports the wmts layer, the url is 'shortened' by 1 letter. As in the 'wmts' gets cut to 'wmt'
Export qgis2web: layer_X = L.tileLayer.wmts('[https://url/wmt',{...}]); --> does not work
manually adding the s to wmt**s** in the end solved the issue.

qgis2web Installed version 3.16.0
QGIS 3.22.10

**Comment by SiDdHaRtHKaNoUjIa13** [comment]
I am unable to plot the shapefile points when i preview in the webmap please give some suggestions

**Comment by andreaordonselli** [comment]
Open a new issue and attach your project. thanks.
