### ISSUE TITLE
code for osmGeocoder

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#716]
Hi,

Building a Leaflet map with 3.5.0 I noticed a few 'settings' in the index.html in the var osmGeocoder that do not seem to have an effect.
`var osmGeocoder = new L.Control.Geocoder({
            collapsed: true,
            position: 'topleft',
            text: 'Search',
            title: 'Testing'
        }).addTo(map);
        document.getElementsByClassName('leaflet-control-geocoder-icon')[0]
        .className += ' fa fa-search';
        document.getElementsByClassName('leaflet-control-geocoder-icon')[0]
        .title += 'Search for a place';`

text: 'Search', I don't see this reflected anywhere in the webmap. Changing the value seems to have no effect in the webmap.
Should it change anything?
Clicking the magnify glass icon in the webmap shows the text "Search..."
Changing this text requires changing a value in the file leaflet-control-geocoder.Geocoder in the map JS.

title: 'Testing' I don't see this reflected anywhere in the webmap.

changing .title += 'Search for a place'; to a different value does change the mouse-over text shown in the webmap.

It would be nice if to be able to change the "Search..." within the index.html, like it is possible with the .title += option

**Comment by tomchadwin** [comment]
Here are the options which the Leaflet plugin offers:

https://github.com/k4r573n/leaflet-control-osm-geocoder#what-are-the-options-

I don't know which version qgis2web currently uses, so there might be a mismatch somewhere.

**Comment by Jeroen-GroeneBij** [comment]
Thanks,

Imo, considering the options form the link your html code could be a bit more simplified:
The option title: ' ', does not exist according to your link and since it doesn't seem to do anything, it could (should?) be left out.
The option text: ' ', is not working, I don't know why, but this can also be left out. 
You use the .title += part at the end to change the mouse-over text and this does work.

The option placeholder: ' ', could/should be added. It does work and changes the text of the searchbox itself (so no need to change the value set in leaflet-control-geocoder.Geocoder).
