### ISSUE TITLE
layer search leaflet) only centers map, additional actions possible?

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#718]
Hi,

Using the layer search in a Leaflet map (3.5.0) only center the map on the value entered (polygons). I still have to search manually (zooming in works good of course) for the exact polygon I am looking for.
Are other actions possible? Such as automatically highlighting the polygon? Or automatically showing the popup info on the searched polygon?

**Comment by tomchadwin** [comment]
Here are the relevant plugin options. Suggestions for alterations to what qgis2web generates are welcome:

https://github.com/stefanocudini/leaflet-search#options

**Comment by Jeroen-GroeneBij** [comment]
Thanks.

Suggestions:
textPlaceholder: 'attributionname', to change the default searchbox text Search... with the attribution name you are actually searching in (the Alias preferably).
collapsed: true (you use this with the osmGeocoder, so why not here)
position: 'topleft' (you use this with the osmGeocoder, so why not here)

I will be looking for other suggestions. I haven't found my main wishes (highlight the polygon and or show pop-up) within the options list.

**Comment by tomchadwin** [comment]
I'll take a look - thanks. Regarding consistency with the Address search/geocoder, I think I was rather trying to draw a distinction. A map with two similar looking icons with different functions deemed like a bad idea.

**Comment by Jeroen-GroeneBij** [comment]
I agree with the idea of distinction. That's why I think adding textPlaceholder: 'attributionname' gives you just that little bit more information what the searchbox is for.
Then collapsed: false might be a better standard setting, so you see the placeholder text immediately.
By adding this option as standard into the html makes it also more easy to change the textPlaceholder value to an even more suited text.

**Comment by azstumbler** [comment]
There used to be animation of a red circle zooming in for the layer search which was very helpful. Now it just causes the map to shift position. In many cases that is not of any help.

In regard to the Address search, I generally change the tooltip to "Search for a place". Not a perfect solution but it works.

**Comment by azstumbler** [comment]
After a little more testing the marker that shows where the result of the layer search is underneath the basemap layer and can not be seen unless you remove the basemap. I have tried this with several different basemaps (ESRI, Google, Bing, OSM, Wikimedia Map) and with the layer being search in several different places of the order of the layers. And the located symbol is ALWAYS hidden under the basemap.

**Comment by tomchadwin** [comment]
We raised this issue on the Leaflet search plugin repo, but have not yet had a solution:  https://github.com/stefanocudini/leaflet-search/issues/179

**Comment by ciaranevans** [comment]
Hi @tomchadwin 

Do you know if there's been any movement on the mentioned issue about the search highlight being behind basemaps?

I've got a friend doing a research project and we've landed here with the same issue, appears to be whenever a basemap is used (or just a layer that has big polygons that cover the highlight).

Appreciate any suggestions you have!

**Comment by josch591** [comment]
Faced the same issue when using qgis 3.10.13 & web2gis 3.16.0
Searched a bit via console, found in leaflat.css, that z-index of .leaflat-pane and z-index of .leaflat-overlay-pane equals.

> **.leaflet-pane         { z-index: 400; }**
.leaflet-tile-pane    { z-index: 200; }
**.leaflet-overlay-pane { z-index: 400; }**
.leaflet-shadow-pane  { z-index: 500; }
.leaflet-marker-pane  { z-index: 600; }
.leaflet-tooltip-pane   { z-index: 650; }
.leaflet-popup-pane   { z-index: 700; }

.leaflet-map-pane canvas { z-index: 100; }
.leaflet-map-pane svg    { z-index: 200; } `


Changed z-index of .leaflet-overlay-pane to 450 and now the animated red circle is visible :-)

**Comment by andreaordonselli** [comment]
I have released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread. The update its just available in QGIS plugin repository.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
