### ISSUE TITLE
Extract tiles from raster mbtiles instead of rendering a TIF

### ISSUE THREAD

**Issue by kannes** [qgis2web/qgis2web#724]
QGIS 3.4.4-Madeira, qgis2web 3.5.0.

I just tried to preview a map in qgis2web where I had a raster mbtiles layer loaded. This ended up OOMing my system as a huge TIF file was created in /tmp/ (where the .mbtiles file was loaded from).

Please try to extract and directly use the files from a raster mbtiles file. Or if that is not possible, give some indication to the user that a massively huge and slow operation might occur once they try to preview or export. :o)

Resulting QGIS crash error for discoverability:
```
Critical: Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalUtils.py", line 108, in runGdal
    universal_newlines=True,
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithm.py", line 133, in processAlgorithm
    GdalUtils.runGdal(commands, feedback)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalUtils.py", line 120, in runGdal
    len(loglines), u'\n'.join(loglines[-10:])))
OSError: [Errno 12] Cannot allocate memory
Tried 5 times without success. Last iteration stopped after reading 1 line(s).
Last line(s):
GDAL execution console output

Killed

```

**Comment by tomchadwin** [comment]
MBTiles currently unsupported. Contributions welcome.

**Comment by tomchadwin** [comment]
If anyone could upload a small typical MBTiles file for me to test with, that would help.

**Comment by tomchadwin** [comment]
Bumping this - can anyone upload a small mbtiles file for me to try to test this and implement - sounds like a good idea.

**Comment by kannes** [comment]
Here you go!

[map.mbtiles.gz](https://github.com/tomchadwin/qgis2web/files/4719497/map.mbtiles.gz)

Created with GDAL and a random image via:
```
gdal_translate -a_srs EPSG:3857 -a_ullr 7056000 -2237000 7058048 -2239048 map.png map.mbtiles
gdaladdo map.mbtiles
```

**Comment by Landnode** [comment]
Hello Tom, did you work in support for mbtiles?

**Comment by kannes** [comment]
No, if he did, this issue would have been closed.

Maybe you can contribute something like another mbtiles file created in different software, a custom projection or some other shenanigans?

**Comment by badshah424** [comment]
Hi I am using a geotif image in QGIS and trying converting it to offline with QGIS2WEB plugin .

But nowhere I'm getting options for Raster map and as a result my web map is not having the geotif file anywhere .

Basically I want to create a offline map with layers. One of the layers being Raster of geotif.

Please help.

**Comment by kannes** [comment]
Hi, this is not a website for user support. Please ask your question on https://gis.stackexchange.com/ rather.
