### ISSUE TITLE
q2w doesn't differentiate between 0 and NULL?

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#746]
Hi Tom,

Is it me, or has the handling of NULL values changed again?
I am using qgis 3.4.5 and q2w 3.7

I have a map with an attribute X (qlonglong, Integer64) that has both NULL values and integer values ranging 0 - 8000
Creating a rule-based style "X" => 0 AND "X" <= 400 shows all polygons with these values, and does not show polygons with NULL value (no data). Which is the correct behaviour.

q2w leaflet however shows all polygons with these values including all polygons with NULL

Any idea what is going on?

**Comment by tomchadwin** [comment]
Sounds like a type handling error. Can you upload just the exported file `index.html`? I think some of this is also caused that (from memory), JSON's concept of NULL is confusing. I'll investigate.

**Comment by Jeroen-GroeneBij** [comment]
Here is the index file, the attribute name is "dichtheid"
[index.zip](https://github.com/tomchadwin/qgis2web/files/3212489/index.zip)

**Comment by tomchadwin** [comment]
Many apologies - I actually need `js/qgis2web_expressions.js`. Sorry!

**Comment by Jeroen-GroeneBij** [comment]
[qgis2web_expressions.zip](https://github.com/tomchadwin/qgis2web/files/3212524/qgis2web_expressions.zip)

**Comment by tomchadwin** [comment]
Hmm. Looks good to m:

```javascript
return ((feature.properties['dichtheid']  >= 0) && (feature.properties['dichtheid']  <= 400));
```

What does one of the NULL values look like in the exported JSON? The file will be `data/dichtheid_koopbuurt_0.js`.

**Comment by Jeroen-GroeneBij** [comment]
{"type":"Feature","properties":{"naam":"Kazerneterrein","woningaant":"4","perc_koop":null,"perc_huur_":null,"perc_huu_1":null,"perc_huu_2":null,"perc_onbek":null,"opp_ha":"39","opp_land_h":"33","opp_water_":"5","aant_koop":null,"opp":0.39,"dichtheid":null},"geometry":{"type":"MultiPolygon","coordinates":[[[[6.167578189981301,51.374726042949796],[6.165642031299819,51.371704797142868],[6.162271068663841,51.369137013787295],[6.155232669799938,51.372872891724008],[6.156291186195642,51.37501773069291],[6.161148783812969,51.37561749637937],[6.161452406314636,51.376251199980864],[6.162990710270426,51.375145906306351],[6.167578189981301,51.374726042949796]]]]}}

**Comment by Jeroen-GroeneBij** [comment]
It seems to miss the " "

**Comment by tomchadwin** [comment]
That's correct (see https://stackoverflow.com/questions/21120999/representing-null-in-json, citing http://www.json.org/. I'm not sure what is causing the problem here.

**Comment by Jeroen-GroeneBij** [comment]
Interesting: three attributes are missing "". These are exactly the three attributes I created in DB Manager.
I loaded the query result into qgis, then simplified the geometry to create a much smaller size file/map ans saved this map as shp file.
And I have been working since with this shp file.

**Comment by tomchadwin** [comment]
There should be quotes if it's a string, and no quotes if it's numeric.

**Comment by Jeroen-GroeneBij** [comment]
The DB manager query writes the three attributes as int4.
When I load this into qgis, the attribute type is int, int4
So no quotes is expected.
However, this layer has the same issue in q2w: 0 and NULL are treated as similar.

**Comment by Jeroen-GroeneBij** [comment]
There is more going on: in the example given you see "woningaant": "4"
Woningaant is not a calculated/created value, it is an existing value.
DB manager says this attribute is int,int4
Qgis (after saving the layer as ESRI shp) says this attribute is qlonglong, Integer64.
But the export shows "4" as if it were a string.

I have been trying to recreate this, but so far without luck.

**Comment by Jeroen-GroeneBij** [comment]
And some more info:

using to_char in DBManager to create "dichtheid" as string (qgis gives QString, text) has the following effect:
the data js file gives NULL values as null (no quotes) and all others as "623" (with quotes).

**Comment by riccardoklinger** [comment]
stumbled upon the int as string thingy also in #776 ... quite confusing!
