### ISSUE TITLE
remove tailing spaces from test case html and export

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#753]
Currently the test case HTMLs are set with tailing spaces. these are automatically removed by some editors (like Atom). If you save a test case HTML it is removed but it is added by the exports in QGIS2web
This should be solved by disabling tailing white spaces in the qgis2web export and update the HTML datasets.
I've tested this only with the leaflet web pages / test cases.

**Comment by tomchadwin** [comment]
I didn't realize there were tailing spaces in the output, to be honest. Some of the formatting issues arise from the fact that there is a delicate balance between the tidiness of the HTML/JS output and the tidiness of the Python code. There are two main things we could do to improve this:

1. Remove all inline output string fragments, making them all standalone files
2. Call an HTML tidy function on output

Both of these would be brilliant additions, but I've not had a chance to do either myself.
