### ISSUE TITLE
qgis2web Page crash on iPads

### ISSUE THREAD

**Issue by rhartings** [qgis2web/qgis2web#756]
I have gotten qgis2web to work now and the sites created are nice.  The issue i'm having now is that when I try to open the site on our iPad's it crashes the browser.  I've tried using Safari and Chrome and get the same thing with both browsers.

Also, When I select Openlayers instead of Leaflet the map is on top of all of my map data.

Using QGIS 3.6.3 on Windows 10
![1](https://user-images.githubusercontent.com/51768005/59444907-af92f780-8dcc-11e9-8b13-90c808253769.png)
![2](https://user-images.githubusercontent.com/51768005/59444908-af92f780-8dcc-11e9-8bc2-061a22370d4e.png)
![3](https://user-images.githubusercontent.com/51768005/59444909-af92f780-8dcc-11e9-86b1-d3bb280c8857.png)
![4](https://user-images.githubusercontent.com/51768005/59444910-af92f780-8dcc-11e9-9365-2b0f11ba3f85.png)

**Comment by tomchadwin** [comment]
For the order of the layers, avoid using layer groups, if that is an option - they just don't work well (#175). I'm afraid I don't have an iPad to test the other issue, so if anyone else can look into this, that would be great.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
