### ISSUE TITLE
enhancement: add filter option 

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#757]
webmapping pages often offers the option to filter data in your webmap. I am proposing the following functionality:
* add a dropdown with every field of a layer in the layer tree
* according to the field type a filter is added to the webmap
* the filter is visualized either in a separate control window in the webmap (leaflet-perspective, don't know about OL)
* field type int and double will create a two sided slider with min/max values
* field type string will create a multilpe select combobox
* field type date will create a calendar range 
* field type boolean will create a radio select

**Comment by riccardoklinger** [comment]
a first raw implementation could look like this:
![image](https://user-images.githubusercontent.com/7377897/59566492-58f21b80-9061-11e9-8158-bb4d02d36c87.png)
it uses materialize css and most items are separate from the leaflet controls.

**Comment by riccardoklinger** [comment]
after a main export, we can use materialize to split up the screen by adding
```
<script>
$( "#map" ).wrap( "<div class='row'></div>" ).wrap( "<div class='col s9'></div>" );
$( ".row" ).css( "height","100%").append("<div class='col s3'></div>");
$(".s9").css( "height","100%").css( "width","75%").css( "float", "left").css( "display","inline");
$(".s3").css( "height","100%").css( "width","25%").css( "float", "right").css( "display","inline");
</script>
```

**Comment by tomchadwin** [comment]
Sounds good. Things to consider:

- how complex will this make the qgis2web GUI?
- I don't want to introduce jQuery, so I'd rather implement those styles in `qgis2web.css` rather than scripting them

**Comment by riccardoklinger** [comment]
The GUI will not be affected that much. There will a single combobox per vectorlayer with fieldname of this layer. Combarable to the search layer selector. 
Unfortunately my proposed solution uses jquery at the moment to embed the map div and the menu at the side and further css adjustments.
What keeps you away from using query?

**Comment by riccardoklinger** [comment]
pseudo code could be:
* 
* iterate over layers
    * get field name and field type

    * if  a layer consists of a field name/type then
        * add materialize css, materialize js
        * add new script tag after first major scripts tag
        *  alter style of map by introducing the map and the menu as materialize cols
        * for string lists: 
```
$( "#menu").append("<div class='input-field col s12'><select id='LAYER_FILTER' multiple><option value='' disabled>Choose your option</option></select></div><label>LAYER: FIELD</label>");
//iterate over field values:
 for (entry in JSON_DATA.features){
    $('#LAYER_FILTER').append('<option value="' + JSON_DATA.features[entry].properties.FIELD + '">' +  JSON_DATA.features[entry].properties.FIELD +'</option>');
}
```
* for number fields:
```
$( "#menu").append("<div id='LAYER_FILTER'></div>"); 
var LAYER_SLIDER = document.getElementById('LAYER_FILTER');
          noUiSlider.create(slider, {
           start: [20, 80], //read this from features
           connect: true,
           step: 1, //1/make this the number of items
           orientation: 'horizontal',
           range: {
             'min': 0, //read this from features
             'max': 100  //read this from features
           },
           format: wNumb({
             decimals: 0 // read number of decimals from field type
           })
          });
```
* initiate the menus:
```
$(document).ready(function(){
    $('select').formSelect();
});
```
* create change listeners like this fo strings:
```
$("#LAYER_FILTER").on('change', function() {
          arr = [];
          for (item in JSON_DATA.features){
            if ($("#LAYER_FILTER").val().includes(JSON_DATA.features[item].properties.FIELD) || $("#LAYER_FILTER").val().length == 0){
              arr.push(JSON_DATA.features[item]);
            }
          }
          LAYER_NAME.clearLayers();
          LAYER_NAME.addData(arr);          
       });
```
* and for number filters:
```
LAYER_SLIDER.noUiSlider.on('update', function( values, handle ) {
            minMax = slider.noUiSlider.get() //this holds the min /max values as array
for (item in JSON_DATA.features){
            if (JSON_DATA.features[item].properties.FIELD >= minMax[0] && JSON_DATA.features[item].properties.FIELD <= minMax[1]){
              arr.push(JSON_DATA.features[item]);
            }
          }
          LAYER_NAME.clearLayers();
          LAYER_NAME.addData(arr);       
        })
```

**Comment by tomchadwin** [comment]
> The GUI will not be affected that much. There will a single combobox per vectorlayer with fieldname of this layer. Combarable to the search layer selector.

Won't it be a checkbox for each field within each layer? Or I guess we can do a combobox, but allow multiple selections?

> Unfortunately my proposed solution uses jquery at the moment to embed the map div and the menu at the side and further css adjustments.

I'm pretty sure we can do that without jQuery - it's just CSS layout, after all.

> What keeps you away from using query?

It's an extra dependency which needs to be kept up to date, it's old, and not very much favoured in web dev any more, it adds bloat to the output. But at the end of the day, I just feel it's no necessary. Admittedly, not sure about eg your calendar control, but I'm guessing we can find a solution for that without the whole of jQuery.

**Comment by riccardoklinger** [comment]
Thanks for your thoughts. At first place I haven’t intended to allow multiple filters per layer. It’s more one filter field per layer. Multiple filters per layer will skyrocket the implementation issues and will overload the GUI

**Comment by riccardoklinger** [comment]
Hi @tomchadwin, thanks for the comment once more. As you can see on the pseudo code above, the code heavily relies on jquery and selectors. I am working on this "enhancement" for QGIS2web as a client demands it. 
As your critic regarding jquery is valid I would like to get an idea about a newer alternative. I was working with dojo in the past as it is used for ESRI's web apps and the web app builder but I think, porting the plugin to work with dojo/require might be a bit over the top right now. Furthermore: I am not capable of programming this fancy shite in aproper way. I would like to suggest to go with jquery at first place and the maybe rearrange the functions in use to work without jquery in the end?

**Comment by tomchadwin** [comment]
One field per layer sounds sensible.

As for jQuery, I'm not suggesting replacing it with some other framework, but coding it in vanilla JS/CSS. Very broadly, two examples would be:

1. For your code in https://github.com/tomchadwin/qgis2web/issues/757#issuecomment-502473832, explicitly write out the HTML and CSS in `index.html` and `qgis2web.css`, rather than scripting it via jQuery. In other words, write out different code in Python to change the HTML/CSS structure, rather than changing it via JS/jQuery.

2. For jQuery `$` selectors, use vanilla `getElementByID()` or `querySelector()`.

I don't mean to frustrate you - it's just that adding in an unnecessary dependency seems like A Bad Thing.

**Comment by riccardoklinger** [comment]
no, that sounds doable. My main goal is to make this as modular as possible so I don't need to alter the current core functionality as much as possible. Otherwise we will need to rewrite all the test cases as well which adds more time on anything.

**Comment by tomchadwin** [comment]
I don't think we'll alter other test cases, as we would only alter the HTML etc when a filtered layer is present, and none of the existing cases will deal with that.

**Comment by riccardoklinger** [comment]
Just a short question to you @tomchadwin . I really like the look and feel of these materialize css selects/forms and the no-UIslider JS/CSS. Using this will add two more dependencies but will show much better selects (check screenshot above).
Is it a no-go or something to consider to use materialize and noUiSlider?

**Comment by riccardoklinger** [comment]
a preview for text filters:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7377897/60773536-40789c80-a107-11e9-8923-bd3b0957027a.gif)

**Comment by Jeroen-GroeneBij** [comment]
Hi,
I just noticed the filter function. I think this will be great.

For now, since I am not sure if I should open a new issue on this:
how will this function co-exists nicely with the 'add layer list: expanded' option? Especially on small screens? My first test is not promising. The layer list all ready has difficulty adapting to small screens, often covering half or more of the map. Adding the filter to the right side leaves even less space.
The filter box it self does scale well on smaller screens however, the data itself is impossible to read, and hence select, because you will see just the first 5 or 10 symbols.

I am not good at coding, but I do have time for testing, so let me know if i can be of any help.

**Comment by Jeroen-GroeneBij** [comment]
Thinking a bit further about this new function and the way you have it visualized at this moment, I really like your use of the separate area on the side of the map. This can also be used to put the Title, legend (which is layer list) and in the future a static info box (in stead of pop-ups, see also my biggest wish #689 )
That way, those elements will no longer or may be less often interfere with the map itself and no longer pop ups will open 'behind' the layer list and things like that.

**Comment by jhpoosthoek** [comment]
Dear all, I was wondering, what is the status of this proposed new filter function?
