### ISSUE TITLE
Disable popup field drop-downs when "Popups" is unchecked

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#760]

**Comment by riccardoklinger** [comment]
Is there a currently a function in qgis2web which alters the GUI according to the change of some parameters? looking for it as it is needed in #762 as well.

**Comment by riccardoklinger** [comment]
Appearently things can be handled in the toggleOptions function in maindialog.py . Yet, this issue here is a bit different.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

Best regards.
