### ISSUE TITLE
enhancement: add abstract to a map

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#762]
I thought about this for a while. Often a webmap needs some context (like an about, subtitle) or something else with some more word about the map. 
What do you think about an option to export the abstract of a QGIS project as a Control like the title:
![grafik](https://user-images.githubusercontent.com/7377897/59882542-ca5c0200-93b2-11e9-8189-5906c4cc6626.png)
nd in the webmap like this: 
![grafik](https://user-images.githubusercontent.com/7377897/59883339-009a8100-93b5-11e9-8b06-3a0e0a785e68.png)
implementation could be done by myself as it might get funded.

**Comment by riccardoklinger** [comment]
If needed, the export of the Abstract field could be checked and unchecked in the Appearance tab (maybe set to uncheck as default)

**Comment by tomchadwin** [comment]
I really like this, but make sure you clarify - the subtitle is already brought through (in Leaflet, at least), but not the abstract. I also wonder whether this will mean that we need to allow users to control position of controls (top-left, bottom-right, etc). Leaflet supports this natively, but it could crowd the qgis2web GUI.

**Comment by riccardoklinger** [comment]
I only saw the option to export "Title" from the QGIS Metadata-Identification. This will be used as the title of the HTMl page as well as the text in the upper right control box.
I would, for a start, add it right below the control wit the title as suggested in the second screen shot.

**Comment by tomchadwin** [comment]
> I only saw the option to export "Title" from the QGIS Metadata-Identification.

Hrm, you're right. qgis2leaf exported the subtitle as well: https://github.com/Geolicious/qgis2leaf/blob/8438632797a50e601df7941b79ef79ddfe034090/qgis2leaf_exec.py#L1132. I wonder why it was removed.

> I would, for a start, add it right below the control wit the title as suggested in the second screenshot. So at the start: no position control!

Position fine to begin with. I'd then consider adding a new GUI option: title position, with a dropdown of top-left, etc. Could add more such options, depending on which controls support position, though if course we'd have to figure out how to implement them in OL, too.

**Comment by tomchadwin** [comment]
Subtitle was removed here: https://github.com/tomchadwin/qgis2web/commit/150c60ec42fde993c58b2d4b0e62f9216b6e22d6

**Comment by riccardoklinger** [comment]
Hi Tom,

> Position fine to begin with. I'd then consider adding a new GUI option: title position, with a dropdown of top-left, etc. Could add more such options, depending on which controls support position
In another thread you mentioned an "overcrowding" of a GUI: Are you interested in a non-complex GUI in the layer tree or is this "fear" of an overcrowded GUI also applying for the appearance tab? An "interesting" option could be to separate the whole appearance tab in a basic and expert mode or even integrate a control.json file in the project which is imported when a project should be exported with qgis2web. This control.js could have additional non-GUI parameters to take into account for exporting.

**Comment by riccardoklinger** [comment]
function is nearly finished:
![grafik](https://user-images.githubusercontent.com/7377897/60197240-551f7f80-983f-11e9-8398-91795d29f270.png)
I will adjust test cases and look into the openlayers export.

**Comment by riccardoklinger** [comment]
please test

**Comment by tomchadwin** [comment]
> In another thread you mentioned an "overcrowding" of a GUI: Are you interested in a non-complex GUI in the layer tree or is this "fear" of an overcrowded GUI also applying for the appearance tab?

Perhaps overcrowding was not the best choice of words. Usability is the prime concern, so I just want to make sure that if/when we add more GUI elements, we make them clear enough for the user.

> An "interesting" option could be to separate the whole appearance tab in a basic and expert mode

Not sure I like this. We already have a tabbed interface, so we can put more advanced options on other tabs if necessary.

> integrate a control.json file in the project which is imported when a project should be exported with qgis2web. This control.js could have additional non-GUI parameters to take into account for exporting.

Not quite sure I understand this idea. All config is saved to the QGIS project file. How would this differ?

**Comment by tomchadwin** [comment]
> 
> 
> please test

I shall, once I've finished with #705.

**Comment by tomchadwin** [comment]
> ![grafik](https://user-images.githubusercontent.com/7377897/60197240-551f7f80-983f-11e9-8398-91795d29f270.png)

I wonder if it would be tider to have title (& subtitle) & abstract all in the one control, and rely on HTML/CSS to style it up. I have slight concerns with multiple overlaid boxes looking untidy. What do you think?

**Comment by Jeroen-GroeneBij** [comment]
Hi,
I really like this idea of being able to show more information.
Question: where in QGIS (I am using 3.4) can I set subtitl;e? I don't see that option.

Having the abstract as a separate box for me would mess up my map, because of the size of the box. There is usually to much info. Especially on smaller screens these boxes (same applies to title and legend) do not scale nicely.  Easy to check when you make your webbrowser more narrow.
To solve this I had a third party make changes to the html to allow for a title element at the top of the page, which has an info-button. That info-button opens a box on top of the map. See [this map](https://www.groenebij.nl/Kaarten/netbeheer) as an example.

So, using a Control, the most important feature for me would be to very easily minimize that control in the browser. That would mean it needs a separate icon.
Second most important feature would be the be able to influence the position, top-left, top-right, etc,

**Comment by tomchadwin** [comment]
> where in QGIS (I am using 3.4) can I set subtitle?

My apologies to both of you for confusing this issue. I can't find it either. I therefore presume it has been removed, having been there in earlier versions. Please ignore any mention I've made of it.

**Comment by riccardoklinger** [comment]
Currently I export the abstract from the metadata in the QGIS project itself as a separate control window in leaflet. in the latest commit you can decide whether you would like to show this as an info box on the upper right lower right upper left and lower left corner this functionality is disabled in open layers as it does not support it so well. 
Therefore you can “leverage” this metadata as a separate box for some information for the user. It also supports HTML. The option, to make this “abstract” box foldable is a nice idea. I will take a look into it. 
If you think your abstract of a GIS project is too long, simply use the None option in the appearance tab item “add abstract”. It is everything in place already. At least for leaflet ;)

**Comment by riccardoklinger** [comment]
ready and committed @Jeroen-GroeneBij 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7377897/60369657-a755d180-99f4-11e9-96ca-2f77524829ca.gif)

**Comment by Jeroen-GroeneBij** [comment]
That is a very nice enhancement and I hope an often used one.

Is it possible to make thie i icon a bit smaller by default, preferably the same size as the zoom buttons and the collapsed layer list button?

Does it need to work in OL as well before it will be part of the plugin?

**Comment by riccardoklinger** [comment]
Currently I am using a self made “i” icon. My goal would be to have a similar look and feel icon like the layer switcher menu. The plus/minus signs in leaflet are simple letters and no custom icons. 
If you come across a nice info icon png I am willing to buy it.

**Comment by Jeroen-GroeneBij** [comment]
What is wrong with a simple i within a standard box with the same styling as the zoom buttons, search button, etc? That styling is part of leaflet.css.
It doesn't have to be anything fancy, does it?

**Comment by riccardoklinger** [comment]
This is much cleaner now! 
![Selection_129](https://user-images.githubusercontent.com/7377897/60465137-b2a53900-9c50-11e9-9a8b-b34641b7c7df.png)

![image](https://user-images.githubusercontent.com/7377897/60465114-a02aff80-9c50-11e9-9191-1ad59ed5eab6.png)

**Comment by tomchadwin** [comment]
Looking great. I'll test.

**Comment by Jeroen-GroeneBij** [comment]
Looking forward to it.

**Comment by tomchadwin** [comment]
OK, tested and merged into master. Thanks very much for the contribution!

**Comment by tomchadwin** [comment]
Reopening, as we need to develop an OL version.

**Comment by riccardoklinger** [comment]
> Reopening, as we need to develop an OL version.

Sorry about closing this too soon

**Comment by riccardoklinger** [comment]
I was able to reproduce the title generation OL as well now. This was not working either in the past:
![grafik](https://user-images.githubusercontent.com/7377897/63841313-e23b9d80-c982-11e9-8648-2f07a5df9a2c.png)
Next up: abstracts

**Comment by JJDokes** [comment]
Tom and Riccardo,  Thank you for this feature (and for all of qgis2web)!  I saw it in the GUI and wondered what it did, so checked its box but nothing showed up.  Then found that it comes from the project's properties, so put it there, and it works great.  Question.  How can I change the icon?  I wrongly assumed it is an image, but don't find it in any of the Leaflet folders.  Then thought maybe it came from a URL, but don't find a URL to it.  Now I read where Riccardo says it is just the letter I (text).  I want the icon to say, "To submit comments..." so when people click on it they get instructions to comment on the map.  I have searched the files in the Leaflet folder for "abstract" but don't find anything that looks like it sets the I.  Any help finding where I would make changes to the icon would be appreciated.

**Comment by andreaordonselli** [comment]
To change the "i" icon, add this css code in the index.html file of the exported project, before the <title>
We are saying that the height of the "i" will be 0px, so we hide it and with background-image you can add your icon.
```css
<style>
.abstract {
	font-size: 0px;
	background-image: url('css/images/start_@2X.png');
	background-size: contain;
	background-repeat: no-repeat;
}
</style>
```
Here the result
![image](https://github.com/qgis2web/qgis2web/assets/89784373/9469e18b-da64-4097-b5fe-a7f405389949)

**Comment by andreaordonselli** [comment]
I close the issue as the abstract works well both in openlayers and in leaflets. See releases [3.21.0 ](https://github.com/qgis2web/qgis2web/releases/tag/v3.21.0)
