### ISSUE TITLE
Wish: add more descriptions

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#765]
As I am deepdiving into the code for 2 weeks now, it is still hard for me, to figure out, what function is doing what in which situation. I am not a heavy-coder and I would like to propose to write a short description into every function/class on the purpose of it and when it is called.
This is done nicely in the exporter.py file already but is missing for most of the others.

**Comment by tomchadwin** [comment]
That would be extremely welcome, of course. The lack of docstrings is absolutely a hindrance to potential contributors.
