### ISSUE TITLE
Leaflet Popup Width

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#791]
Tested on IE 11, FF 60.7 : Popup Width is to small for longer strings.

The default value for max-width is set to 300px. We could easily enhance this value to 600px as this would still maintain useability for normal users but would give better look and feel for users with longer strings: 
Reference here:
https://leafletjs.com/reference-1.5.0.html#popup 

Issue was raised already in #402 but was solved by the user back then without adjusting code base

**Comment by tomchadwin** [comment]
Problem is mobile use. If we can do it responsively, then yes - we've had people raise this issue before.

**Comment by riccardoklinger** [comment]
the problem is the !important; flag in qgis2web.ss line 26. increasing the padding to 20px will work both on mobile (tested with 320x480px view on FF) and on desktop.

**Comment by riccardoklinger** [comment]
old discussion also here #532 and #493

**Comment by riccardoklinger** [comment]
mobile devices are getting bigger and bigger in terms of pixels and resolution are rocketing. but with the current setup this appears on desktop:
![image](https://user-images.githubusercontent.com/7377897/62088339-550f0700-b265-11e9-9fa2-d544a8470aff.png)
by using a simple text:
`Ein Test für HTML only<br>
<i><b>Italic Bold</b></i>`

If we remove the '!important;' tag in qgis2web css the popup will look much better:
![image](https://user-images.githubusercontent.com/7377897/62088462-b9ca6180-b265-11e9-8b3f-329ba6336ef1.png)
and it  also works on mobile devices (320x 480px):
![image](https://user-images.githubusercontent.com/7377897/62088603-234a7000-b266-11e9-8aec-a68a9ccec30c.png)

**Comment by Jeroen-GroeneBij** [comment]
Interesting.

For me, Leaflet pop-ups often are to small.
I had a webdesign consultant write me a workaround that lets me choose a min-width for popups.
Based on attribution data I can easily choose between 'middle' (180px), 'large' (230px) or 'xlarge' (300px)
This is done in two steps:
I have a custom css with many changes including
`body.popup-middle .leaflet-popup {
	min-width: 180px;`
which I add to the exported files
and then adding `<body class="popup-large">` in the index.html

I will test a few maps to see how removing !important will help me.
