### ISSUE TITLE
Popups settings are not stored correctly

### ISSUE THREAD

**Issue by riccardoklinger** [qgis2web/qgis2web#798]
When I change the visibility of a popup in a layer it is not stored in the project settings. This should be implemented:
![image](https://user-images.githubusercontent.com/7377897/62241590-bc4dc800-b3d9-11e9-9e8d-3d8a272a9b87.png)

**Comment by andreaordonselli** [comment]
It seems that the problem of saving settings is now solved, I'll close the issue for now.
Feel free to reopen it if you still encounter problems.
