### ISSUE TITLE
Processing algorithm error: Export project

### ISSUE THREAD

**Issue by janddd** [qgis2web/qgis2web#804]
Hi,

I encountered a bug when using the processing algorithm Export project in QGIS 3.8 on Windows (tested with a single vector layer in the workspace).

First I got the error:

`Traceback (most recent call last): File "C:/Users/bi.admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 102, in processAlgorithm writer.cluster) = self.getLayersAndGroups() File "C:/Users/bi.admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 118, in getLayersAndGroups layer.wbbType() != QgsWkbTypes.NoGeometry) and AttributeError: 'QgsVectorLayer' object has no attribute 'wbbType' `

This seems to be a typo with regards to wbbType (should be wkbType I think?), I solved it by changing line 118 in qgis2webAlgorithm.py to: 

`layer.wkbType() != QgsWkbTypes.NoGeometry`

However this created a new issue, for which I have no clue:

`Traceback (most recent call last): File "C:/Users/bi.admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 105, in processAlgorithm writer.write(iface, write_folder) File "C:/Users/bi.admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 101, in write folder=dest_folder) File "C:/Users/bi.admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 267, in writeLeaflet interactive[count], json[count], IndexError: list index out of range `

I would be happy to check some more things if necessary.

**Comment by riccardoklinger** [comment]
it seems like an issue with my latest contribution with an interactivity switch. I will dive into it.

**Comment by tomchadwin** [comment]
@riccardoklinger Are you sure? The Processing algorithms have been broken for ages. I'll find the open issue.

**Comment by tomchadwin** [comment]
Existing issue is https://github.com/tomchadwin/qgis2web/issues/609

**Comment by andreaordonselli** [comment]
We talk about it here https://github.com/qgis2web/qgis2web/issues/730
