### ISSUE TITLE
Settings not saving?

### ISSUE THREAD

**Issue by tomchadwin** [qgis2web/qgis2web#815]
The state of option in the qqis2web `Settings` tab should save and persist automatically - I'm fairly sure they used to. They don't now, at least for me. Do others see the same?

**Comment by boesiii** [comment]
I am seeing the same.  Typically I leave these at the default values so I don't know if they worked before.

**Comment by jukos** [comment]
With qgis2 no problems.
(I must working with qgis2....no images in the popups under qgis3....you know....)
Greetings, Jürgen

**Comment by jukos** [comment]
Edit:
the checkbox cluster is not saved

QGIS 3.4.13
qgis2web  3.12.1

**Comment by jukos** [comment]
Edit:
the checkbox cluster is not saved

QGIS 3.10.10
qgis2web 3.16

**Comment by andreaordonselli** [comment]
It seems that the problem of saving settings is now solved, I'll close the issue for now.
Feel free to reopen it if you still encounter problems.
