### ISSUE TITLE
Python error when renderers have != number of layers

### ISSUE THREAD

**Issue by olivierh65** [qgis2web/qgis2web#828]
Hello,
At least with version 3.10.0 and RuleBasedRenderer, there is an error if a rule have not the same number of layers of the first rule.
A quick workaround is to change line 134 in leafletStyleScripts.py from
if rule.symbol().symbolLayer(sl) is not None:
to 
if rule.symbol().symbolLayerCount() > sl and rule.symbol().symbolLayer(sl) is not None:

That works for me (now) because I have just the last rule with less layer than others.
But I think that it's neccessary to check the number of layers for each rule.

Regards.

**Comment by tomchadwin** [comment]
Yes, you've come across one of the problems with the way we hand;e the different layer/symbology structure across the formats. It's not an easy issue to solve, but I'll have a think and see if there is a way round it.
