### ISSUE TITLE
leaflet popup labels

### ISSUE THREAD

**Issue by jukos** [qgis2web/qgis2web#834]
Hello,
case:
If i choose "inline label" for the popupfields I can see all fields/attributes.
But I want see only these fields with content.
Sometimes it looks like very bad: look at the screenshot:
![000756](https://user-images.githubusercontent.com/31866672/68577789-0a5e7700-0471-11ea-9198-9f6e48f5e7ab.png)
In this time I could only choose "no label", but this is not really an option. If I have content for example with "yes" or "no" the user can not see, for what is yes or no.....

Question:
Is it possible to integrate the function:
**"Show only the field/s with content"  ?**

Greetings, Jürgen

**Comment by jukos** [comment]
I have not found a perfect solution.
In some cases I could for example use the field calculator to set a label-text within the content.
Greetings

But with a new function it would be more easier and would be look better.

**Comment by Jeroen-GroeneBij** [comment]
That would a nice feature, especially when it is optional. So I can choose which attributes are always shown in the popup and which ones are only displayed when they contain data.

**Comment by andreaordonselli** [comment]
If these options were available in the input they would meet your expectations?

Label input:
- no label
- inline label (always visible)
- inline label (visible with data)
- header label (always visible)
- header label (visible with data)

**Comment by jukos** [comment]
> If these options were available in the input they would meet your expectations?

Yes.

Please also note: 
https://github.com/qgis2web/qgis2web/issues/833

The default setting should still be customisable in the "maindialog.py" file.
It would be ideal if you could choose the default setting yourself, so that the setting is not changed during qgis2web updates - code changes should be avoided.

Greetings, Jürgen

**Comment by andreaordonselli** [comment]
Regarding this I'm thinking of an extra line in the Layer tab, composed as follows: Set all "2 options: Layer/Label" to "2 options for Layer: Visible/Not Visible" and "5 options for Label as written above" + " ok button".  The choice changes all settings of all layers.  What do you think?

**Comment by jukos** [comment]
![QGIS labels](https://github.com/qgis2web/qgis2web/assets/31866672/04a7739f-9022-4272-a5f0-da6ee99460e4)


Something like the picture?
Then: Yes!

**Comment by andreaordonselli** [comment]
In reference to this issue I send the modification files, I ask for a test from you.
[qgis2web - visible with data.zip](https://github.com/qgis2web/qgis2web/files/13870973/qgis2web.-.visible.with.data.zip)

Now there are 5 total variables:

- inline label - always visible
- inline label - visible with data
- hidden field
- header label - always visible
- header label - visible with data

If you give me the ok I'll start working on issue 833 for the massive setting

**Comment by jukos** [comment]
Did a test. Positive. That's a good thing.

What is still missing is the option to make the setting for many layers and popup fields at once. Simultaneous setting for all popup fields in all layers.  This might be sufficient for most projects. Different individual settings can then be made.

Please note: If new layers are added, they should also immediately be provided with the basic setting made.

**Comment by andreaordonselli** [comment]
For the massive setting option I will write in issue 833. Thank you for the test, I will commit both solutions as soon as they are ready.

**Comment by andreaordonselli** [comment]
Released version [3.17.3](https://github.com/qgis2web/qgis2web/releases/tag/v3.17.3) which includes a fix for this issue. The update will be available soon from the QGIS plugin repository. Thanks for the tip. Please consider a small donation to support qgis2web via the button on the home page. Thank you.
