### ISSUE TITLE
Popup fields from GUI drag and drop designer

### ISSUE THREAD

**Issue by jb-cloud** [qgis2web/qgis2web#853]
QGIS: 3.4.15
qgis2web: 3.12.1

Is it possible for the qgis2web GUI to use the drag and drop designer's form layout as the source of the popup fields? That would be pretty handy vs. hiding and creating virtual fields and would allow easy reordering.

**Comment by tomchadwin** [comment]
It would be very nice indeed, but it has a some knock-on considerations, such as then having to save field order/visibility etc as qgis2web-specific layer properties in the QGIS project file. In other words, I agree this would be a good feature, but it's not one I'm likely to implement in the near future. Code contributions extremely welcome.
