### ISSUE TITLE
add abstract - html text

### ISSUE THREAD

**Issue by jukos** [qgis2web/qgis2web#865]
If I use html text there's a strange thing:
After every link there are a break.
If I use for example text with a link ("Text: Link") additional there are a break after the word "Text".

Export with leaflet

**Comment by tomchadwin** [comment]
@riccardoklinger?

**Comment by riccardoklinger** [comment]
the abstract export is triggert using the same function which works on the title export. The relevant coding is here:
`    titleSub += webmap_head.replace("'", "\\'") + """</h2>';` 
Especially the replacement might destroy html hyperlinks. 
Can you provide your example abstract text from project settings with "anomyzed" urls @jukos?

**Comment by riccardoklinger** [comment]
links are working correct, used abstract entry like this: 
`this is a <a href="https://google.com">test</a>`
<img width="695" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79380402-b5171c00-7f60-11ea-85ae-f36cb8426ffd.png">
But I can confirm the linebreak:
<img width="113" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79380497-d415ae00-7f60-11ea-8ef5-56ecb840717d.png">
The generated HTML export looks exactly as desired:
`this._div.innerHTML = 'this is a <a href="https://google.com">test</a>';`

**Comment by riccardoklinger** [comment]
The line break seems to originate from the max-width settings in the .uncollapsed class. this works great for longish texts:
<img width="904" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79382873-826f2280-7f64-11ea-9e32-b546bda7196a.png">
Yet it breaks this short text with the link as above. if I remove the max-width it looks better. 
The border-ish structure origins from the leaflet-bar class. 
WIth leaflet-bar:
<img width="388" alt="grafik" src="https://user-images.githubusercontent.com/7377897/79382986-b8aca200-7f64-11ea-936e-fa906ae80da3.png">
without see above.

**Comment by riccardoklinger** [comment]
"leaflet-bar" was introduced with my commit here 3a27242  ... can we remove it or is it essential for mobile devices?

**Comment by riccardoklinger** [comment]
the only other place, where this class is used is in the zoom buttons and the geocoder plugin.

**Comment by riccardoklinger** [comment]
the abstract uses the leaflet-bar class like the zoom buttons and the geocoder plugin which are somehow supportive for mobile devices. I don't see a real value here and will remove them. 
was introduced here 438575f709b4ad15301dee6ec3bf55ff683692e7 10 month ago.

**Comment by riccardoklinger** [comment]
by changing the max-width value of the abstractUncollapsed to 50% it workd for my small string. might be wrong solution for other strings. So waiting for your string as reference @jukos .

**Comment by riccardoklinger** [comment]
changing this value will affect the size of the box if it is uncollapsed.

**Comment by riccardoklinger** [comment]
fix is here in master: dcef3a064b3be86f29318f0c3a7f3999e14a6c07 please test @jukos

**Comment by jukos** [comment]
**No more problems with html text and links.**

But I have now not the same Design as for the search and -/+ icons.
I can change the code after export, I tested this.  But the best is: No changes after export.

Thank you and greetings

**Comment by Jeroen-GroeneBij** [comment]
Hi,

Testing this on qgis 3.10.4 and q2w 3.13 the linebreak even repeats when using multiple words as link, such as: 
This is a <a href="https://www.google.com"> link to google</a> please use this link.
The abstract then contains three "sort of boxes" that contain the link, one for each word 'link', 'to' and 'google'. It puts these boxes beneath one another and they get mixed up with the rest of the text after </a>.

The fixed presented does remove this issue and for me it also improves the design of the abstract.
It now has the same look and feel as Title. Personally I like that better than the abstract sharing the look and feel of the search and -/+ icons.
