### ISSUE TITLE
Not displaying individual raster symbols for points

### ISSUE THREAD

**Issue by gioorgioo** [qgis2web/qgis2web#873]
Hello, I am quite new to QGIS and qgis2web, then sorry if this is a stupid question.
I have created a map in QGIS 3.12.1-București that contains a layer of points with a field reporting the url of images that I would like to display at each point (each point has a specific image).
Then in the properties of the layer I add Single Symbol and change symbol label type from Simple marker to Raster image marker, and use a Data-defined override for the file location
Field type: string → name_of_the_field_with_url
Mostly following the instructions reported at the last section of this page:
https://bnhr.xyz/2019/09/22/geotagged-photos-in-qgis.html

The raster symbols are properly displayed on the map: each point has its own image. But when I try to export to a web gis using qgis2web (2020/04/08 3.13.0) the following happens:
- export to OpenLayers creates an empty page, no preview is provided. When Export is tried the error reported later is generated.
- export to Leaflet renders simple point markers, but not the raster symbols
- export to Mapbox GL JS hangs on and I have to shut down QGIS.

I have tried both linking images from the web, with a specific url, both referring to files on my pc.
I thank you in advance!
 
-----------------------
Error generated by export to OpenLayers (note that the layers is a shape file named punti_csv_esportati);

Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting punti_csv_esportati to JSON... done done
Exception in layer punti_csv_esportati_cf38750e_fbd6_4771_ade3_13cc74a15d39 with renderer SINGLE: MARKER SYMBOL (1 layers) color 0,0,0,255: Traceback (most recent call last): File "C:/Users/Giorgio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 49, in exportStyles layer, feedback) File "C:/Users/Giorgio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 214, in singleSymbol feedback) File "C:/Users/Giorgio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 565, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:\Users\Giorgio\AppData\Local\Temp\qgis2web

**Comment by tomchadwin** [comment]
I'm afraid raster symbols are not supported yet in qgis2web.
