### ISSUE TITLE
Measure symbol and "shadow" missing when opening in Edge and Chrome

### ISSUE THREAD

**Issue by Cordillera94** [qgis2web/qgis2web#889]
First time using GitHub and fairly new to QGIS so please bear with me.

Any web map I export is missing the following when opened using Microsoft Edge or Google Chrome:
- measure/ruler icon ("shadow" is still there)
- "shadow" around zoom icons
- "shadow" around layers list

They are not missing if I open the same web map using Internet Explorer or Firefox.

Edit: I am exporting to a Leaflet web map

QGIS version: 3.10.3
qgis2web version: 3.14.0
Microsoft Edge version: 44.17763.831.0
Google Chrome version: 81.0.4044.138
Internet Explorer version: 11.1217.17763.0
Firefox version: 76.0.1

Firefox:
![Firefox_Screenshot](https://user-images.githubusercontent.com/65731507/82594538-7bd65b00-9b61-11ea-80a6-f3b8c036666e.JPG) 

Microsoft Edge:
![MicrosoftEdge_Screenshot](https://user-images.githubusercontent.com/65731507/82594539-7bd65b00-9b61-11ea-893e-5cb15d37bfcb.JPG)

**Comment by tomchadwin** [comment]
A couple of questions:

1. Are you seeing these issues when looking at local copies of the files? If so, are you able to upload them to a web address, and browse them there? Does that make a difference?
2. Are there any errors in the browser console (hit F12 in your browser to show the console)?

**Comment by tomchadwin** [comment]
I can see these issues. However, I'm not having a lot of joy understanding the cause or fixing them. Can anyone help?

**Comment by jipexu** [comment]
working on my mac with all browser (not tested edge but working also with chrome)
QGIS version: 3.14
qgis2web 3.16.0
Google Chrome
Version 83.0.4103.116 (Build officiel) (64 bits)

**Comment by jipexu** [comment]
Hi
Working for me with  chrome and safari and FF (all latest version)  in my mac
qgis 3.14.0
qgis2web 3.16.0
for leaflet and openlayer

howewer we can notice that the script(s) call some fonts that are not in the folder /webfonts generated by qgis2web ... (probably is a  be different issue)


[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-brands-400.woff2
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-brands-400.woff
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-brands-400.ttf
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-brands-400.svg#fontawesome
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-regular-400.woff2
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-regular-400.woff
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-regular-400.ttf
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-regular-400.svg#fontawesome
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-solid-900.woff
[Error] Not allowed to load local resource: file:///Users/jpb/Documents/Chine/qgis2web_2020_07_05-08_34_04_510344/webfonts/fa-solid-900.svg#fontawesome

**Comment by abodsalas** [comment]
I'm having the same issue.

However, I've used Qgis2web for a few years without any issues.
If i open previous index.html generated files, the measure icon is OK.
The error probably has to do with the plugin.

![Measure_Icon_Missing](https://user-images.githubusercontent.com/54449155/105504131-29c47700-5ca6-11eb-9633-91af614f09db.JPG)

QGIS version: 3.16.1-Hannover
qgis2web version: 3.16.0
Google Chrome version: Versión 87.0.4280.141

Any suggestions?

**Comment by Mikester-Calgary** [comment]
Would it make sense to compare a leaflet.js that DOES work with one that DOES NOT and see what is causing the problem and tell Tom so we can have a permanent fix?

**Comment by Mikester-Calgary** [comment]
That swap the leaflet.js procedure didn't work for me anyway.

**Comment by abodsalas** [comment]
I have the lastest QGIS installed (3.30) with an up to date QGIS2Web plugin (3.1.6 of June 2020) on a Windows 10 machine. 

I still have the same issue.
I discovered QGIS2Web generates a Leaflet map using **Leaflet version 1.6.0 !!!**

That seems to be the problem. If I replace **Leaflet.js** with a more recent (or even older) version it works OK !!!
Leaflet 1.6.0 seems to be the only one with issues.

I downloaded  the latest version from:
[https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3)

**Comment by nameloCmaS** [comment]
The latest version of qgis2web uses Leaflet version 1.7.1. Have you tried that version?

Unless rewriting the exported html and JavaScript code, all the exported files in the same file structure should be used.

**Comment by andreaordonselli** [comment]
In the latest versions of Chrome and Edge the problem has been resolved. I ask you to reopen the issue if there are further problems.
