### ISSUE TITLE
Pop up images not optimizing size after first pop up

### ISSUE THREAD

**Issue by MapperMonday** [qgis2web/qgis2web#892]
Hi Tom, noticing something relating to pop up images attached to points.  The first time the point is clicked and the image pops up it optimizes the size of the image perfectly - landscape, portrait, different dimensions no problem.  Then, when I go back and click it a second time it defaults to a particular size (portrait) with scroll bars.  Refreshing the page clears it and it will open optimally again.

Cheers, Andrew

**Comment by tomchadwin** [comment]
Any chance you can upload or link to an example?

**Comment by MapperMonday** [comment]
mappermonday.github.io/Exodus - work in progress!

**Comment by tomchadwin** [comment]
Urg. For me, first click us far from perfect - image is full-size and overlaps popup (Firefox). Will have to investigate.

**Comment by MapperMonday** [comment]
Thankyou!  I'm finding that on Chrome and IE it does what I describe - first rendering ok then not.

**Comment by andreaordonselli** [comment]
I have just released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
