### ISSUE TITLE
не могу разобраться 

### ISSUE THREAD

**Issue by Pavel-Aktobe** [qgis2web/qgis2web#894]
Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting Здания to JSON... done
Exporting Трубопровод_СО to JSON... done
Exporting Подключение to JSON... done
Exporting Задвижки to JSON... done
Exporting Камеры to JSON... done done
Exception in layer akt_pipes_420170922025304304 with renderer Rule-based renderer: RULE - scale [0,0] - filter - symbol [] RULE - scale [0,0] - filter - symbol LINE SYMBOL (1 layers) color 251,5,0,255 RULE до 1998 года - scale [0,0] - filter "year_laying_t1" NULL and "chek"= 'да' - symbol LINE SYMBOL (1 layers) color 248,126,147,255 RULE Другие - scale [0,0] - filter "ownership" = 'Другие' - symbol LINE SYMBOL (1 layers) color 235,2,193,255 RULE Акимат - scale [0,0] - filter "ownership" = 'Акимат' - symbol LINE SYMBOL (1 layers) color 198,132,255,255 RULE бесхозные сети - scale [0,0] - filter "ownership" = 'Бесхозные сети' - symbol LINE SYMBOL (1 layers) color 116,213,234,255 RULE Проверены - scale [0,0] - filter "external_d_t1" = NULL or "chek"= 'нет' - symbol LINE SYMBOL (1 layers) color 242,21,5,255 RULE Канальная - scale [50,2000] - filter "type_laying" = 'канальная' - symbol LINE SYMBOL (3 layers) color 0,0,0,255 RULE Надземная - scale [0,0] - filter "type_laying" = 'надземная' - symbol LINE SYMBOL (1 layers) color 35,149,255,255 RULE нету года - scale [0,0] - filter "year_laying_t1" = NULL or "year_laying_t1" = 0 - symbol LINE SYMBOL (1 layers) color 255,226,5,255 RULE 'Управляющая компания' - scale [0,0] - filter "ownership" = 'Управляющая компания' - symbol LINE SYMBOL (1 layers) color 255,149,234,255 RULE Отключены - scale [0,0] - filter "status_pipe" = 'Отключен' - symbol LINE SYMBOL (1 layers) color 0,0,0,255 RULE Инветарный - scale [0,0] - filter "inventory_number" NULL or "inventory_number" '' - symbol LINE SYMBOL (1 layers) color 20,250,0,255 : Traceback (most recent call last): File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 62, in exportStyles layer_alpha, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 316, in ruleBased renderer, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 565, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Exception in layer akt_connection_point_920170922022640951 with renderer Rule-based renderer: RULE - scale [0,0] - filter - symbol [] RULE - scale [0,0] - filter - symbol MARKER SYMBOL (1 layers) color 228,7,191,255 RULE - scale [50,2000] - filter "id_block_heat_meters" = 'true' - symbol MARKER SYMBOL (1 layers) color 218,58,77,255 : Traceback (most recent call last): File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 62, in exportStyles layer_alpha, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 316, in ruleBased renderer, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 481, in getSymbolAsStyle svg = xml.etree.ElementTree.parse(sl.path()).getroot() File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse tree.parse(source, parser) File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 587, in parse source = open(source, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4wLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLVNWRy0yMDAxMDkwNC9EVEQvc3ZnMTAuZHRkIj4NCjwhLS0gQ3JlYXRvcjogQ29yZWxEUkFXIFg4IC0tPg0KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIHdpZHRoPSIyMTBtbSIgaGVpZ2h0PSIyOTdtbSIgdmVyc2lvbj0iMS4wIiBzaGFwZS1yZW5kZXJpbmc9Imdlb21ldHJpY1ByZWNpc2lvbiIgdGV4dC1yZW5kZXJpbmc9Imdlb21ldHJpY1ByZWNpc2lvbiIgaW1hZ2UtcmVuZGVyaW5nPSJvcHRpbWl6ZVF1YWxpdHkiIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIg0Kdmlld0JveD0iMCAwIDIxMCAyOTciDQogeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPg0KIDxnIGlkPSLQodC70L7QuV94MDAyMF8xIj4NCiAgPG1ldGFkYXRhIGlkPSJDb3JlbENvcnBJRF8wQ29yZWwtTGF5ZXIiLz4NCiAgPGVsbGlwc2UgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjRTYzQzI0IiBzdHJva2Utd2lkdGg9IjMiIGN4PSIxMDUiIGN5PSIxNDkiIHJ4PSIzNSIgcnk9IjMyIi8+DQogIDxnIGlkPSJfMjAxMDU4MjQ2ODc1MiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMC4yIiB4MT0iMTA1IiB5MT0iMTE3IiB4Mj0iMTA1IiB5Mj0gIjExNyIgLz4NCiAgPC9nPg0KICA8ZyBpZD0iXzIwMTA1ODI0NjcwMjQiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuNSIgeDE9IjExOSIgeTE9IjEyNCIgeDI9IjkwIiB5Mj0gIjEyNCIgLz4NCiAgPC9nPg0KICA8ZyBpZD0iXzIwMTA1ODI0Njc4ODgiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiB4MT0iMTE5IiB5MT0iMTI2IiB4Mj0iOTAiIHkyPSAiMTI2IiAvPg0KICA8L2c+DQogIDxnIGlkPSJfMjAxMDU4MjQ2NzMxMiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMS41IiB4MT0iMTE5IiB5MT0iMTI4IiB4Mj0iOTAiIHkyPSAiMTI4IiAvPg0KICA8L2c+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9Ijc5IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9Ijg2IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjkzIiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNEMkQyRDIiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjEwMSIgeT0iMTM0IiB3aWR0aD0iNS41MDMzIiBoZWlnaHQ9IjguNjc4MyIvPg0KICA8cmVjdCBmaWxsPSIjRDJEMkQyIiBzdHJva2U9IiMyQjJBMjkiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSIxMDgiIHk9IjEzNCIgd2lkdGg9IjUuNTAzMyIgaGVpZ2h0PSI4LjY3ODMiLz4NCiAgPHJlY3QgZmlsbD0iI0QyRDJEMiIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuMiIgeD0iMTE0IiB5PSIxMzQiIHdpZHRoPSI1LjUwMzMiIGhlaWdodD0iOC42NzgzIi8+DQogIDxyZWN0IGZpbGw9IiNFQjVFNUQiIHN0cm9rZT0iIzJCMkEyOSIgc3Ryb2tlLXdpZHRoPSIwLjIiIHg9IjEyMiIgeT0iMTM0IiB3aWR0aD0iNS41MDMzIiBoZWlnaHQ9IjguNjc4MyIvPg0KICA8Y2lyY2xlIGZpbGw9IiNBM0EzQTQiIGN4PSI4NiIgY3k9IjE1OCIgcj0iNiIvPg0KICA8Y2lyY2xlIGZpbGw9IiNGRUZFRkUiIHN0cm9rZT0iI0ZFRkVGRSIgc3Ryb2tlLXdpZHRoPSIwLjIiIGN4PSI4NiIgY3k9IjE1OCIgcj0iMSIvPg0KICA8cmVjdCBmaWxsPSIjRkVGRUZFIiBzdHJva2U9IiNGRUZFRkUiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSI4NiIgeT0iMTU1IiB3aWR0aD0iMC4zNzA1IiBoZWlnaHQ9IjMuNjkwOSIvPg0KICA8cmVjdCBmaWxsPSJub25lIiBzdHJva2U9IiNFNjNDMjQiIHN0cm9rZS13aWR0aD0iMC4yIiB4PSI4NSIgeT0iMTU1IiB3aWR0aD0iMC42MjE3IiBoZWlnaHQ9IjAuMjI0OSIvPg0KICA8ZyBpZD0iXzIwMTA1ODI0NTYxNDQiPg0KICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkIyQTI5IiBzdHJva2Utd2lkdGg9IjAuNSIgeDE9IjkyIiB5MT0iMTY1IiB4Mj0iODAiIHkyPSAiMTY1IiAvPg0KICA8L2c+DQogIDxjaXJjbGUgZmlsbD0iI0EzQTNBNCIgY3g9IjEyMiIgY3k9IjE1NSIgcj0iOCIvPg0KICA8Y2lyY2xlIGZpbGw9IiNFNjNDMjQiIHN0cm9rZT0iI0U2M0MyNCIgc3Ryb2tlLXdpZHRoPSIwLjIiIGN4PSIxMjIiIGN5PSIxNTUiIHI9IjEiLz4NCiAgPHJlY3QgZmlsbD0iI0U2M0MyNCIgc3Ryb2tlPSIjRTYzQzI0IiBzdHJva2Utd2lkdGg9IjAuMiIgeD0iMTIyIiB5PSIxNTEiIHdpZHRoPSIwLjM3MDUiIGhlaWdodD0iMy42OTA5Ii8+DQogIDxnIGlkPSJfMjAxMDU4MjQ1MDg5NiI+DQogICA8bGluZSBmaWxsPSJub25lIiBzdHJva2U9IiMyQjJBMjkiIHgxPSIxMzEiIHkxPSIxNjQiIHgyPSIxMTQiIHkyPSAiMTY0IiAvPg0KICA8L2c+DQogIDxyZWN0IGZpbGw9IiNFMUUwREUiIHg9Ijk0IiB5PSIxNzAiIHdpZHRoPSIyNC4yMzU4IiBoZWlnaHQ9IjMuNDkyNSIvPg0KIDwvZz4NCjwvc3ZnPg0K' 
Exception in layer akt_valves_1820170922024855400 with renderer Rule-based renderer: RULE - scale [0,0] - filter - symbol [] RULE - scale [0,0] - filter - symbol MARKER SYMBOL (1 layers) color 234,8,4,255 RULE Новая задвижка по ОВ - scale [0,0] - filter ( "installation_date_t1" ) = 01-01-2000 or ( "installation_date_t1" ) > 2010 and ( "installation_date_t2" ) = 01-01-2000 or ( "installation_date_t2" ) > 2010 - symbol MARKER SYMBOL (1 layers) color 162,91,15,255 RULE Новая задвижка по ПВ - scale [0,0] - filter ( "installation_date_t2" ) = 01-01-2000 or ( "installation_date_t2" ) > 2010 and ( "installation_date_t1" ) = 01-01-2000 or ( "installation_date_t1" ) > 2010 - symbol MARKER SYMBOL (1 layers) color 255,0,0,255 RULE Новая задвижка по ПВ и ОВ - scale [0,0] - filter ( ( ( "installation_date_t1" ) ) = 01-01-2000 or ( "installation_date_t1" ) > 2010 ) and ( ( "installation_date_t2" ) = 01-01-2000 or ( "installation_date_t2" ) > 2010 ) - symbol MARKER SYMBOL (1 layers) color 189,31,23,255 RULE Ремонт ревизия ПВ - scale [0,0] - filter year(age( now(), to_date( "revision_date_t1" ))) >0 and year(age( now(), to_date( "revision_date_t1" ))) 0 and year(age( now(), to_date( "revision_date_t2" ))) 1 and year(age( now(), to_date( "revision_date_t1" ))) 0 and year(age( now(), to_date( "repair_date_t1" ))) 0 and year(age( now(), to_date( "repair_date_t2" ))) 0 and year(age( now(), to_date( "revision_date_t1" ))) 0 and year(age( now(), to_date( "revision_date_t2" ))) 0 and year(age( now(), to_date( "repair_date_t1" ))) 0 and year(age( now(), to_date( "repair_date_t2" ))) Traceback (most recent call last): File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 62, in exportStyles layer_alpha, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 316, in ruleBased renderer, sln, layer, feedback) File "C:/Users/Dorogokuplya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 481, in getSymbolAsStyle svg = xml.etree.ElementTree.parse(sl.path()).getroot() File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse tree.parse(source, parser) File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\xml\etree\ElementTree.py", line 587, in parse source = open(source, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNi4wLjEsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9ItCh0LvQvtC5XzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB3aWR0aD0iNTEycHgiIGhlaWdodD0iNTEycHgiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA1MTIgNTEyIiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxwb2x5Z29uIGZpbGw9IiNGRjAwMDAiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiBwb2ludHM9IjEzLjUsOTMuMDMxIDI1NywyNDYuMjY4IDEzLjUsMzk5LjUgIi8+DQo8cG9seWdvbiBmaWxsPSIjRkYwMDAwIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgcG9pbnRzPSI1MDAuNSwzOTkuNSAyNTcsMjQ2LjI2NCA1MDAuNSw5My4wMzEgIi8+DQo8cGF0aCBmaWxsPSIjMDcwMDAwIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgZD0iTTI3OC45MTUsMjQ2LjI2NmMwLDE0LjAxMS0xMC42ODUsMjUuMzY5LTIzLjg2MiwyNS4zNjkNCgljLTEzLjE3OSwwLTIzLjg2Mi0xMS4zNTUtMjMuODYyLTI1LjM2OWMwLTE0LjAxLDEwLjY4My0yNS4zNjcsMjMuODYyLTI1LjM2N0MyNjguMjMyLDIyMC44OTgsMjc4LjkxNSwyMzIuMjU0LDI3OC45MTUsMjQ2LjI2NnoiLz4NCjwvc3ZnPg0K' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:/Users/Dorogokuplya/AppData/Local/Temp/qgis2web/321

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by Pavel-Aktobe** [comment]
как их здесь загрузить или дайте электрону почту

**Comment by Pavel-Aktobe** [comment]
как загрузить суда файлы

**Comment by tomchadwin** [comment]
> как их здесь загрузить или дайте электрону почту

https://stackoverflow.com/a/10963250/5613104

**Comment by Pavel-Aktobe** [comment]
[Отправить.zip](https://github.com/tomchadwin/qgis2web/files/4749660/default.zip)

**Comment by Pavel-Aktobe** [comment]
[12345.zip](https://github.com/tomchadwin/qgis2web/files/4749665/12345.zip)

**Comment by tomchadwin** [comment]
Sorry, but opening that tells me there is a missing dependent layer.

**Comment by Pavel-Aktobe** [comment]
[123.zip](https://github.com/tomchadwin/qgis2web/files/4755953/123.zip)

**Comment by Pavel-Aktobe** [comment]
[123111.zip](https://github.com/tomchadwin/qgis2web/files/4762297/123111.zip)

**Comment by Pavel-Aktobe** [comment]
решение не найдено

**Comment by Pavel-Aktobe** [comment]
не получается мне помочь
