### ISSUE TITLE
Error with raster image marker for symbols

### ISSUE THREAD

**Issue by yarzaryeni** [qgis2web/qgis2web#910]
I am using QGIS 3.14 and latest qgis2web to date. When I use raster image marker for symbols, I cannot export and get error. I tried with different image format JPG, PNG, TIF with transparency or without transparency but it produces the same error message as followed. I use openLayers option to export. (_Leaflet and Mapbox options also  produce different errors tho_)

Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting Adman_Sea to JSON... done
Exporting Regions and States to JSON... done
Exporting Township Boundries to JSON... done
Exporting Water Bodies to JSON... done
Exporting Roads to JSON... done
Exporting Towns to JSON... done
Exporting Health-Facilities to JSON... done done
Exception in layer Health_Facilities_9d396f02_c332_46f8_a798_2e66c6891f51 with renderer Rule-based renderer: RULE - scale [0,0] - filter - symbol [] RULE HS - scale [0,0] - filter "HF_TYPE" = 'VB' - symbol MARKER SYMBOL (1 layers) color 0,0,0,255 : Traceback (most recent call last): File "C:/Users/John/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 62, in exportStyles layer_alpha, sln, layer, feedback) File "C:/Users/John/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 316, in ruleBased renderer, sln, layer, feedback) File "C:/Users/John/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 565, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to D:/HF-Web

**Comment by tomchadwin** [comment]
I'm afraid raster image markers are not yet supported in qgis2web.
