### ISSUE TITLE
ArcGIS Feature Services displayed in Single Symbol (black) for MapBox

### ISSUE THREAD

**Issue by MyGIS** [qgis2web/qgis2web#911]
After loading a layer from ArcGIS Feature Services in QGIS (polygons). I classify the polygons and symbolize them differently. I try creating a web map using qgis2web. The symbology is changed to single symbol - black  for Mapbox. Symbology is maintained the same for leaflet and OL.

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.
