### ISSUE TITLE
qgis2web mapbox crashes while writing data

### ISSUE THREAD

**Issue by bestestusername** [qgis2web/qgis2web#913]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible
## User Feedback

I had a firefox web browser open with 8 tabs.

## Report Details

**Crash ID**: [7516acda68f70e875c68bf26c103fb14cc0f5736](https://github.com/qgis/QGIS/search?q=7516acda68f70e875c68bf26c103fb14cc0f5736&type=Issues)

**Stack Trace**
<pre>
QList<QgsSymbolLayer * __ptr64>::QList<QgsSymbolLayer * __ptr64> qlist.h:807
QgsSymbol::hasDataDefinedProperties qgssymbol.cpp:754
QgsSymbolLayerUtils::symbolPreviewPixmap qgssymbollayerutils.cpp:792
meth_QgsSymbolLayerUtils_symbolPreviewPixmap sip_corepart1.cpp:36247
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.
