### ISSUE TITLE
qgis2web auto hiding closeby features when zoomed out

### ISSUE THREAD

**Issue by okhan01** [qgis2web/qgis2web#915]
Hi everyone,

I'm having an issue with qgis2web (release: 2020/06/15, with qgis 3.14.15). I'm mapping some villages and on the initial view (zoomed out) some villages don't show up. I have to zoom in so that they appear. Is there a way to avoid this?
Its important that all features are visible when zoomed out.

Im using openlayers.

**Comment by riccardoklinger** [comment]
Happened to me in the past as well. Check the geometries of the buildings layer and try use „fix geometries“ in qgis. 
In my case the geometries were broken/invalid.

Von meinem iPhone gesendet

**Comment by okhan01** [comment]
> Happened to me in the past as well. Check the geometries of the buildings layer and try use „fix geometries“ in qgis. In my case the geometries were broken/invalid. Von meinem iPhone gesendet
> […](#)
> Am 09.09.2020 um 20:30 schrieb okhan01 ***@***.***>: ﻿ Hi everyone, I'm having an issue with qgis2web (release: 2020/06/15, with qgis 3.14.15). I'm mapping some villages and on the initial view (zoomed out) some villages don't show up. I have to zoom in so that they appear. Is there a way to avoid this? Its important that all features are visible when zoomed out. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Ok. But in my case I dont think there are broken geometries. I guess is standard for qgis2web to hide features that are very close to each other to avoid overlapping. And I'd rather have them overlapping than not showing up when zoomed out.

**Comment by tomchadwin** [comment]
Can you let us know which output webmap format you are using? OpenLayers declutters by default, but other formats do not, so changing to another export format might solve your problem.

**Comment by okhan01** [comment]
I was using openlayers. When I switched to leaflet the problem was solved. Now there is no automatic clustering and I can see all the points when zoomed out. Thanks a lot Tom!

I tried to switch between openlayers and leaflet before, but it was not working. The map would come blank if I chose leaflet, but now it works. Is there any reason for that? Mapbox doesnt work at all...maybe because I have xyz tiles (google image and open street maps).

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
