### ISSUE TITLE
Location Marker moved to background and therefore not visible

### ISSUE THREAD

**Issue by sledbird** [qgis2web/qgis2web#918]
I would like to show the location marker on top of the map. Currently using leaflet, the marker successfully locates but is moved to the background and therefore not visible unless deselecting the layers. I've tried multiple settings, multiple browsers, multiple devices and still get the issue. Please find a simplified version of the map with only one layer.

[qgis2web_2020_09_17-08_43_15_804182.zip](https://github.com/tomchadwin/qgis2web/files/5236843/qgis2web_2020_09_17-08_43_15_804182.zip)

I've also deployed the map to my website, where it is showing the same issue. Here is a link to the full version of the map:
[continental-divide.eu/map/map.html](url)

**Comment by sledbird** [comment]
I kept working on the problem since my post. The original code had used the createPane and getPane methods, which seemed to be interfering with the L.control.locate() method. I commented out each of the panes and now it seems to be working as expected. You can find the live page at [continental-divide.eu/map/map.html](url). I would be interested if there is any other way to solve this issue.

        layer_TFOSMOutdoors_1;
        //map.createPane('pane_OpenStreetMap_2');
        //map.getPane('pane_OpenStreetMap_2').style.zIndex = 402;
        var layer_OpenStreetMap_2 = L.tileLayer('http://a.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            //pane: 'pane_OpenStreetMap_2',
            opacity: 1.0,
            attribution: '',
            minZoom: 1,
            maxZoom: 28,
            minNativeZoom: 0,
            maxNativeZoom: 19
        });

**Comment by w-mcalister** [comment]
I had the same issue as sledbird. Thanks for the workaround. I commented out all lines that allocated the basemap to a defined pane:

`   //     map.createPane('pane_ESRIworldimagery_0');
   //     map.getPane('pane_ESRIworldimagery_0').style.zIndex = 400;
        var layer_ESRIworldimagery_0 = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    //        pane: 'pane_ESRIworldimagery_0',
            opacity: 1.0,
            attribution: '',
            minZoom: 5,
            maxZoom: 28,
            minNativeZoom: 0,
            maxNativeZoom: 18
        });`

**Comment by ghoffart** [comment]
Having the same issue. It popped up after approx. 20 layers in QGIS 3.10 with qgis2web 3.16.0, when exporting to Leaflet: the map tiles overlayered all data points, so the markers weren’t visible. Same with QGIS 3.20 with qgis2web 3.16.0.

Manual fix: open _index.html_ and change the _zindex_ value of the map manually to something lower than the first data layer zindex.

**Comment by andreaordonselli** [comment]
I have released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
