### ISSUE TITLE
Should the Declutter option for OpenLayers be False by default?

### ISSUE THREAD

**Issue by boesiii** [qgis2web/qgis2web#919]
I think the declutter option should be set to false by default.  If a new user exports there map and they don't see some of their features they are initially going to think something is wrong.  Thoughts?

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
