### ISSUE TITLE
Expanded leaflet legend not collapsible

### ISSUE THREAD

**Issue by ntrip6** [qgis2web/qgis2web#928]
If the Add Layer List: Expanded option is selected in the Appearance tab there's no way to hide the legend.
If the Add Layer List: Collapsed option is selected the legend is can be collapsed or expanded, but it begins collapsed into the small icon and many users don't realize there's a legend available under the icon. It would be great to have the Expanded legend have a Collapse icon (perhaps an roll-up arrow in the legend title bar).
Alternately, the Collapsed legend could appear at first and then collapse itself after a few gestures which would draw attention to the presence of the legend and the Expand icon.

**Comment by jukos** [comment]
> and many users don't realize there's a legend available under the icon

You could change the png symbol. For example additional with text "LAYERS".

Greetings

**Comment by andreaordonselli** [comment]
In version [3.22.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.22.0) the issue discussed in this thread is resolved. The update it's just available within the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
