### ISSUE TITLE
Cannot display raster map exported with transparency settings

### ISSUE THREAD

**Issue by Krukarius** [qgis2web/qgis2web#938]
I would like to include the semi-transparent map in my project.
The map is raster - .geotiff file. The layer is partially filled-in, but mostly includes a white background, like you see below.
![QGIS transparent map](https://user-images.githubusercontent.com/40125405/100362518-6b60da80-2ff3-11eb-843a-0f5abefb5597.png)

Obviously, this white background has been removed (set full transparent) following the thread below:

https://gis.stackexchange.com/questions/171405/how-to-make-the-white-background-of-an-rgb-raster-transparent

I was expecting to have the same result in the interactive version (OpenLayers), all the more that the map is visible in the preview mode.

![GIS map preview mode](https://user-images.githubusercontent.com/40125405/100364054-7caae680-2ff5-11eb-96ce-fccc01a22850.png)

but is NOT visible 

![QGIS No map](https://user-images.githubusercontent.com/40125405/100364940-af091380-2ff6-11eb-961e-b67899ff75be.png)

despite the code in the layers.js file, which seems to be alright

         var lyr_Area7_1 = new ol.layer.Image({
                            opacity: 1,
                            title: "Area7",
                            
                            
                            source: new ol.source.ImageStatic({
                               url: "./layers/Area7_1.png",
                attributions: ' ',
                                projection: 'EPSG:3857',
                                alwaysInRange: true,
                                imageExtent: [-27464.855018, 6812717.879307, -24138.625451, 6816052.643985]
                            })
                        });
                  var lyr_Area6_2 = new ol.layer.Image({
                            opacity: 1,
                            title: "Area6",
                            
                            
                            source: new ol.source.ImageStatic({
                               url: "./layers/Area6_2.png",
                           attributions: ' ',
                                projection: 'EPSG:3857',
                                alwaysInRange: true,
                                imageExtent: [-23488.879733, 6814799.233467, -22713.936608, 6815622.095812]
                              })
                          });

Where is the problem then?

Thank you in advance for your help

**Comment by mroswell** [comment]
Try changing `opacity: 1,` to `opacity: 0.5` or some other number lower than 1.

**Comment by andreaordonselli** [comment]
@Krukarius Thanks for the tip
@mroswell Thanks for the answer, it's correct, you can set layer's transparency manually after export, but there's a simpler method, you can set layer's transparency in QGIS.

You can find all the info in the qgis2web Wiki at the following link https://github.com/qgis2web/qgis2web/wiki/Set-Styles

I hope you are happy with qgis2web, I ask you to consider making a donation of a coffee to support the project; you can do this via the button on the home page.

Thanks again.
Greetings.
