### ISSUE TITLE
My large raster layer not visible on the map

### ISSUE THREAD

**Issue by Krukarius** [qgis2web/qgis2web#939]
The issue is very similar to the previous one. The raster map is visible in the preview mode, but can't be loaded in the interactive version. The file is large because it counts finally about 33MB (png file after [processing by the plugin). Is there any way to make it visible on my map?

**Comment by jukos** [comment]
Hello,
I think, 33 MB are not the problem:
My test:
- tiff picture 125 MB
- export (leaflet and openlayers) to png : 70 MB
Ok for preview and for export.

My system:
- Windows 10, QGIS 3.10.10, qgis2web 3.16
