### ISSUE TITLE
qgis2web Output Blank Page

### ISSUE THREAD

**Issue by Dotmess** [qgis2web/qgis2web#940]
Hi Tom,

I am using QGIS 3.10 and qgis2web is the most up-to-date.

I ran qgis2web with 4 layers (listed below) with OpenStreetMap, but both OpenLayers and Leaflet show a blank page on the output. I tried different combinations and found out it happens only when I have the layer Sub-structures_ST on.

I buffered a layer (see (3) ZoI 100m) from it and that layer appears on the qgis2web output correctly. Could you have a look for me see what I have done wrong please?

Layers:
(1) Applications
(2) Sub-structures_ST
(3) ZoI 100m (_buffered_ from Sub-structures with _Dissolve Result_)
(4) Overlap ZoI (_intersection_ of (1) & (2))

Thank you.

Jude

**Comment by jukos** [comment]
Please try:
Set for sub-structures a coordinate reference system.
Greetings
