### ISSUE TITLE
qgis2web -openlayers -search for all the attributes in a layer

### ISSUE THREAD

**Issue by fatih0057** [qgis2web/qgis2web#941]
first of all sorry for my english
In my map I created with qgis2web openlayers.
First Name
last name
Father name
I want to bring my columns in order when searching.
can i achieve this
Thanks in advance forever.
var searchLayer = new SearchLayer({
      layer: lyr_mezarlar_2,
      colName: 'adi', 'soyadi','babaadi',
      zoom: 10,
      collapsed: true,
      map: map
    });

    map.addControl(searchLayer);
    document.getElementsByClassName('search-layer')[0]
    .getElementsByTagName('button')[0].className +=
    ' fa fa-binoculars';
![search](https://user-images.githubusercontent.com/77175143/104071377-1af7b200-521a-11eb-87a5-21207e479cc6.jpg)

**Comment by andreaordonselli** [comment]
In qgis layer you can create a new field dedicated to the search and use the field calculator to insert the data "field1 + field2 + field3"
