### ISSUE TITLE
Is there a way to interactively change a layer's opacity/transparency using a slider, apart from the nouislider?

### ISSUE THREAD

**Issue by mbrynard** [qgis2web/qgis2web#942]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by andreaordonselli** [comment]
For openlayers i have replaced the layerswitcher with this one that has what you are looking for:
https://viglino.github.io/ol-ext/examples/control/map.switcher.html

**Comment by anstadel** [comment]
@andreaordonselli that interesting feature! 
I am only a beginner with openlayers and js. Maybe you could help me a bit. 
I have build the npm package openlayer-ext and now have a lot of files. 
I tried to replace in index.html the stylesheet and script ol-layerswitcher.js/css by LayerSwitcher.js/css. But this is probably a to easy way of thinking ;-) 
I also replaced the files resource/ol-layerswitcher* by ol-ext.* by renaming ol-ext into ol-layerswitcher. This gave me a legend with the new features, but no visible layers. Maybe this is a starting point, but obviously I have to do some more changes.

**Comment by andreaordonselli** [comment]
Produce export with qgis2web without layerswitcher (`add layer list: none` in appearance tab).
In the `index.html` file add this in the head after `qgis2web.css`
```
<!-- ol-ext -->		 
		<link rel="stylesheet" href="http://viglino.github.io/ol-ext/dist/ol-ext.css" />
		<link rel="stylesheet" href="http://viglino.github.io/ol-ext/examples/style.css" />
```
and this in the body after `qgis2web.js`:
```
<!-- ol-ext -->
  <script type="text/javascript" src="http://viglino.github.io/ol-ext/dist/ol-ext.js"></script>
  <script>
  var layerSwitcher = new ol.control.LayerSwitcher({
	noScroll : false, 
	reordering: true,
	});
	map.addControl(layerSwitcher);
  </script>
```

**the new layerswitcher will work**

You can customize its appearance as you like via css code. For example, I chose to set the variable `noScroll: false` and I added this in the `index.html` file after `style.css`
```
<!-- custom layerswitcher style -->	
<style>		
.ol-control.ol-layerswitcher.ol-forceopen {
		z-index: 2;
		height: 100%;
		max-height: calc(100% - 120px);
		padding: 3px;
		right: 8px;
		}
		
		.ol-layerswitcher.ol-unselectable.ol-collapsed{
		min-height: 43px;
		min-width: 43px;
		padding: 3px;
		right: 8px;
		}
		
		.ol-layerswitcher.ol-forceopen .panel-container {
		width: 250px;
		margin-top: 40px;
		height: calc(100% - 47px);
		overflow-y: scroll;
		background-color: #f8f8f8;
		padding-left: 2px;
		}
		
		.ol-layerswitcher .panel {
		right: -3px;
		}
		.ol-layerswitcher .panel ul {
		padding: 0 0 7px 22px;
		}

		.ol-layerswitcher .panel li label {
		max-width: unset;
		width: 178px;
		height: auto;
		white-space: unset;
		max-height: 250px;
		overflow-y: auto;
		}

		.ol-layerswitcher .panel li > div {
		display: contents;
		}
		
		.ol-layerswitcher .panel li label span {
		position: relative;
		left: 5px;
		width: 98%;
		}
</style>
```
I hope I was helpful.

**Comment by anstadel** [comment]
That was very helpfull! Thank you very much for the detailed and easy understandable instruction!

**Comment by andreaordonselli** [comment]
If you think the problem solved, I ask you to close the issue.
Greetings.
