### ISSUE TITLE
raster map cannot visualize

### ISSUE THREAD

**Issue by LFF50340** [qgis2web/qgis2web#943]
I create webgis using the qgis2web tool but when I visualize the raster layers, within the qgis2web, they appear to me and yet, when I open it from the explorer, they are not loaded or displayed.

**Comment by jukos** [comment]
Hello,
which versions of qgis / qgis2web?
Export leaflet or openlayers?
Maybe a size or projection problem?
Greetings

**Comment by LFF50340** [comment]
Hi, about your questions:
which versions of qgis / qgis2web?  QGIS 3.10.13 and qgis2web 3.16
Export leaflet or openlayers? export as leaflet
Maybe a size or projection problem? I think is a size problem, beacause when file is smaller there's no problem, but if it's bigger like 15000x11000 pixels is imposible in qgis 3.10 but it's ok in 2.14.22 version. Do you know which is the limit?

I'm not the author of this last question.

Thanks for your interest!

**Comment by jukos** [comment]
Hello,
I don't know the size limit.
But for big raster images this is better:

> Update: QGIS now supports native XYZ layers, and qgis2web exports them.

source:
https://gis.stackexchange.com/questions/216327/is-it-possible-to-insert-an-xyz-tile-layer-to-an-openlayers-webmap-created-by-qg

You can use processing toolbox: generate xyz tiles (directory)

Greetings
