### ISSUE TITLE
WMS getfeatureinfo popup problem

### ISSUE THREAD

**Issue by feryomon** [qgis2web/qgis2web#945]
i got a problem in my first image below, WMS getfeatureinfo popup is showing "Single value expected for request parameter version but instead found: [1.3.0, 1.1.1]".
- Activated getfeatureinfo
- QGIS 3.10 LTS and QGIS2WEB ver 3.16 (latest)
- PostGIS database
- Geoserver 2.8 
- CORS Enable on tomcat
![Screenshot 2021-01-26 165446](https://user-images.githubusercontent.com/34015068/105829739-56a2c200-5ff7-11eb-8526-4eb32d7a284c.jpg)

But , when i try to use L.TileLayer.BetterWMS.js [https://gist.github.com/rclark/6908938](url) , it does work well (see. image bellow)
![Screenshot 2021-01-26 164551](https://user-images.githubusercontent.com/34015068/105828788-20187780-5ff6-11eb-8b01-efe065d3fdcf.jpg)

**Comment by andreaordonselli** [comment]
Can you provide the WMS server address? Does the problem still exist with the latest version of qgis2web?
