### ISSUE TITLE
Qgis2Web yields blank map

### ISSUE THREAD

**Issue by Smithsinarazz** [qgis2web/qgis2web#948]
Hi Tom. I'm using Qgis2web to export a map made up of a polygon layer, 2 point layers and a base map (Open Layers Transport Dark). However, when I try to export it/ preview it, it comes up as a blank map. It must be a problem with the point layers because when I turn them off the other two layers come up ok. I've tried a) changing the styling so it isn't categorised b) exporting the points in the project CRS (they were in a different CRS to begin with; now everything's in WGS84) c) taking out lots of the fields in the attribute table d) not making any of the fields "hidden", but none of these makes any difference. Could it be the size of the datasets? There's about 1500 points in one and 2000 in the other. Cheers Jo

**Comment by tomchadwin** [comment]
Hi Jo

It shouldn;t be the size of the dataset, no. IT will be something else in the data or styling. Can you remove all other layers from your project, and then upload the project file and that layer here? Without being able to recreate the error, it's hard to solve.

**Comment by Smithsinarazz** [comment]
Thanks very much Tom. I tried taking off the label styling and it worked! 
cheers Jo
    On Thursday, 18 March 2021, 14:14:40 GMT, Tom Chadwin ***@***.***> wrote:  
 
 


Hi Jo

It shouldn;t be the size of the dataset, no. IT will be something else in the data or styling. Can you remove all other layers from your project, and then upload the project file and that layer here? Without being able to recreate the error, it's hard to solve.

**Comment by tomchadwin** [comment]
It would be useful to see the project file and layer, to see what specifically about the styling caused the failure. Upload them if you can.

**Comment by Smithsinarazz** [comment]
Hi Tom, here is the dataset that was causing the problem, plus the style file. See what you think. Jo
[policestations2010wurbanruralwgs.zip](https://github.com/tomchadwin/qgis2web/files/6165803/policestations2010wurbanruralwgs.zip)
[police2010style.zip](https://github.com/tomchadwin/qgis2web/files/6165804/police2010style.zip)

**Comment by binu-alexander** [comment]
Hi Tom,  it looks like I have a similar problem with blank , preview and blank exports. Tried with Mac and Windows, my other projects are getting saved to web without any problem. Can't figure out this particular layers doesn't export I am running QGIS 3.20 on both Mac and Windows devices. Appreciate any pointers. 
[Archive.zip](https://github.com/tomchadwin/qgis2web/files/6723913/Archive.zip)

**Comment by tomchadwin** [comment]
@binu-alexander In your case, there is a line break in the "Francophone Africa" values in your table. qgis2web is not handling this. If you are able to change your data to get rid of the line break, and then reclassify your layers in QGIS, that should fix the issue.

**Comment by binu-alexander** [comment]
@tomchadwin Thanks its working now !
