### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by JJDokes** [qgis2web/qgis2web#952]
Edit >> You can ignore or delete this post.  I removed some layers and it now appears to work, so it appears that error apparently means there is an invalid layer. <<

Not sure if this is a problem with qgis2web or with my layers.  Just downloaded the latest qgis2web zip file from here https://plugins.qgis.org/plugins/qgis2web/ , and installed it, clicked on qgis2web and immediately got this Python error, 

...\qgis2web\maindialog.py", line 370, in populate_layers_and_groups
              if (layer.type() != QgsMapLayer.PluginLayer and
             AttributeError: 'NoneType' object has no attribute 'type'

Rebooted QGIS and it repeats.  Looked online and it seems that could be caused by qgis2web trying to populate with an invalid layer, or, it may be a problem with qgis2web.  I don't pretend to have a clue.  I am using QGIS version 3.10.10-A Coruña, QGIS code revision 8b051b9a43.

If the problem is with my files, sorry to have bothered you with this Tom.  If the problem is with qgis2web then I will be glad I gave you this heads up.  Thank you for qgis2web Tom, and for your continued work on it.

**Comment by Xenotech81** [comment]
Hi,
just ran into the same issue with Qgis 3.18.2-Zürich and Qgis2Web 3.16.0. The reason was a broken virtual layer (became empty after saving and reloading the project). Works after deletion of layer.

Regards
