### ISSUE TITLE
CLustering spiderweb not visible anymore? [SOLVED]

### ISSUE THREAD

**Issue by Japhys** [qgis2web/qgis2web#953]
I am using leaflet export 3.16.0

I haven't done an export is a while. I updated qgis and all plugins, made an export and uploaded it to the web. Then I noticed the spiderweb with clustering was not visible anymore. Am i missing something? I tried both FF and Chrome. 

![2021-04-05_102928](https://user-images.githubusercontent.com/24695937/113554809-2a5c8080-95fa-11eb-9fb3-79c90a4d9a43.png)

**Comment by Japhys** [comment]
No one?

**Comment by Japhys** [comment]
Still the case I have just noticed :) Is this plugin still being maintained at all? Are there alternatives?

**Comment by andreaordonselli** [comment]
Did you select the cluster option before exporting?
Just zoom.

Openlayers
![openlayers cluster](https://github.com/qgis2web/qgis2web/assets/89784373/2329eeba-2ed7-4689-b176-96b8abfbd43b)

Leaflet
![leaflet cluster](https://github.com/qgis2web/qgis2web/assets/89784373/6ebe2be3-908d-4b92-9015-1a08daf6f227)

**Comment by pds11001** [comment]
Any updates on this? Recently updated to Version 3.22 and experienced same issue. Cluster check box disappeared from settings. Downgraded back to Version 3.20.0 and problem resolved. In QGIS 3.34.11

**Comment by andreaordonselli** [comment]
I didn't understand what the problem is. Please explain clearly what is wrong. In the qgis2web release 3.21.0 this has been changed:

_"cluster" choice during export will be visible only if layer is "point" and with single symbol symbology_

Maybe you are using a layer with categorized or graduated symbol?

**Comment by pds11001** [comment]
Thank you, That is the issue. I have a layer with categorized symbology. I've downgraded back to the prior version as this was preferred for my use case, but appreciate the help!

**Comment by andreaordonselli** [comment]
In version [3.24.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.24.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
