### ISSUE TITLE
automating Qgis2Web

### ISSUE THREAD

**Issue by ridasti** [qgis2web/qgis2web#957]
Hello! 

I exported a project with Qgis2web on an FTP server. I need this web map to update when the Qgis project updates. Can somebody help me please ?

**Comment by boesiii** [comment]
It is not possible with the plugin but you could easily script something.

1. Use a batch file and OGR2OGR to convert your source data to geojson.  Make sure to use the same coordinate system.
2. Use a python script to copy the geojson files to the same location on your FTP site.

As long as you don't change attributes and labels it shouldn't be a problem.
Let me know if you need more help.

**Comment by andreaordonselli** [comment]
Buongiorno,
puoi spiegare come creare un batch file per convertire uno o più shp in json?
Grazie

**Comment by boesiii** [comment]
The code for the batch file is below

`ogr2ogr -f GeoJSON output.geojson input.shp`

**Comment by andreaordonselli** [comment]
We talk about it here #730
