### ISSUE TITLE
Measure Control Icon showing in preview but not map.

### ISSUE THREAD

**Issue by Mikester-Calgary** [qgis2web/qgis2web#958]
Leaflet Measure Control

-Latest QGIS2web plugin
-Tried on a very simple map
-Shows fine in preview
-rulers.png are in the right place when exported
-No ruler icon in Measure Control box when exported

![Leaflet Measure Tool](https://user-images.githubusercontent.com/64865458/115723161-ea590580-a33c-11eb-834f-c3a1c02eaa71.JPG)

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by Mikester-Calgary** [comment]
Tom:

There was no “here” link or anything, I just attached the project file.

m

**Comment by tomchadwin** [comment]
Apologies, by "here", I just meant in mreply on this thread. I don't see an attachment - you might need to browse to this thread to upload it, rather than attaching to am email reply (not sure). Thanks.

**Comment by tomchadwin** [comment]
In the meantime, a couple of checks:

- When it fails, are you viewing a local copy? If so, have you tried uploading and viewing online?
- If it fails online, are you viewing via HTTP or HTTPS?

Gut feeling suggests this is a mixed content or CORS issue, but not sure.

**Comment by Mikester-Calgary** [comment]
[Calgary.zip](https://github.com/tomchadwin/qgis2web/files/6358771/Calgary.zip)

**Comment by Mikester-Calgary** [comment]
Tom:

I zipped it and put it on the Git thread.

I am just viewing the local result in a browser.  Why would it appear different anywhere else?

I have put others on my Windows Server IIS service but the result is the same.

m

**Comment by tomchadwin** [comment]
Hrm. It works in Firefox, but fails in Chrome. That's why I didn't spot it. Don't know why yet.

**Comment by Mikester-Calgary** [comment]
You’re right.  Fails in Microsoft Edge as well.

**Comment by Mikester-Calgary** [comment]
Was there any progress with this in Chrome Tom?

**Comment by boesiii** [comment]
It looks like it is something with the CSS.  If you change the CSS on-the-fly in Chrome Developer tools the button will start to appear.

**Comment by Mikester-Calgary** [comment]
Lot’s of stuff in leaflet-measure.css!

What am I changing?

**Comment by ianholmes** [comment]
I have this exact same issue using the latest Qgis2Web plugin.  The 'measure' button doesn't display in a Leaflet map in Chrome when viewing locally or online, looks fine in FireFox though:

![image](https://user-images.githubusercontent.com/9719724/144403631-ff4c72d2-36de-4d9a-9d7d-ca3a97b1cbf2.png)

**Comment by abodsalas** [comment]
I have lastes QGIS installed (3.30) with an up to date QGIS2Web plugin (3.1.6 of June 2020). 
I still have the same issue.
QGIS2Web generates a LEaflet map using **Leaflet version 1.6.0 !!!**

That seems to be the problem. If I replace Leaflet.js with a more recent (or older) version it works OK !!!
Leaflet 1.6.0 seems to be the only one with issues.

I downloaded  the latest version from:
[https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3)
