### ISSUE TITLE
Scale based label visibility working for Leaflet but not OL3

### ISSUE THREAD

**Issue by fwxmikel** [qgis2web/qgis2web#961]
QGis 3.18, qgis2web 3.16

Scale based label visibility doesn't working when the map is exported via OpenLayers3, but work when exported via Leaflet.
Previously it worked in both.

**Comment by andreaordonselli** [comment]
This works in both openlayers and leaflet exports, but they work in different ways.
In leaflet there is no need to interact with the layerswitcher, with zoom the layer will turn on and off automatically, but if you want to see the features you can always turn on the layer by hand.
While in openlayers if the layer does not have the flag in the layerswitcher it will never turn on by itself, so you always need to turn on the layer and zoom in just to see the feature.
