### ISSUE TITLE
QGIS2Web - Settings

### ISSUE THREAD

**Issue by Uoppa** [qgis2web/qgis2web#963]
Good morning.
I'm doing a thesis work using QGIS2Web.
Can someone explain me the meaning of the tools in "Settings", please? I refer to "Preview on startup", "Close feedback on success" and "Preview feature limit per layer".

Thank you very much,

Riccardo

**Comment by patml1** [comment]
Hi,
If you have not worked it out already by experimenting:
"Preview on startup": When you open the QGIS2WEB window, the map that will be created is displayed on the right hand side.
"Close feedback on success": the feedback is the window that opens when you click export. This stays open once it finishes unless you set this.
"Preview feature limit per layer": If you have more than this number of features (points, lines) in any layer, it does not create the preview. This is to prevent spending a long time rendering a complex preview when you want to get on and export.
