### ISSUE TITLE
Qgis2web yields a blank map when a layer's name contains double quotes (")

### ISSUE THREAD

**Issue by geraads** [qgis2web/qgis2web#974]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by andreaordonselli** [comment]
In version [3.24.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.24.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
