### ISSUE TITLE
crashes when trying to export

### ISSUE THREAD

**Issue by samesterman** [qgis2web/qgis2web#976]
Hi, 
I’m trying to export a map I made, using qgis2web.
I am extremely novice at this, but when I try to export, it gets stuck at the exporting to JSON stage, and crashes qgis. 
Here is the stack trace.

QgsMapLayer::transformContext :
QgsVectorFileWriter::writeAsVectorFormat :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyObject_MakeTpCall :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

Any idea what you think I should do?

**Comment by boesiii** [comment]
Its most likely due to one of your layers.  Start with creating a project Qgis file and adding one layer and try the plugin.  If its successful then add another layer.  Rinse and repeat till you find the layer causing the issue.  Once you find the layer come back and post the info about the layer and we can assist.
