### ISSUE TITLE
Qgis2web is not working, shows python error. 

### ISSUE THREAD

**Issue by Thya1991** [qgis2web/qgis2web#981]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by Thya1991** [comment]
Hi anybody kindly provide a solution for Qgis2web error.
Thanks in advance

**Comment by bleonard252** [comment]
You have to give more information. As it stands you're bound to get this issue closed with no comment 🙃

**Comment by AndySpeed** [comment]
Thya1991 isn't the only person with this issue, I've just experienced it and I have tried three versions of QGIS: 3.10.14, 3.16.2 and 3.22.0 and all come up with the same python error:

An error has occurred while executing Python code: 

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\abbott.andrew' 
Traceback (most recent call last):
  File "C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 129, in writeOL
    writeFiles(folder, restrictToExtent, feedback)
  File "C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olFileScripts.py", line 17, in writeFiles
    os.makedirs(fontStore)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\abbott.andrew'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.14-A Coruña A Coruña, 8374282d2a 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/abbot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\abbot\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
