### ISSUE TITLE
Choropleth map has no colors

### ISSUE THREAD

**Issue by amr66** [qgis2web/qgis2web#984]
When I try to export my choropleth map with leaflet, it doesn't use the colors of my qgis layer, but shows all features in blue.
I have only 2 layers, the vector layer with choropleths and a base map from OSM. 
I'm using qgis2web 3.16.0 with qgis 3.16.4 on a windows10 machine.

Browser is newest firefox, but tried with chrome, too. Firefox JS-Console shows

````
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. index.html
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. S.extend/<@file:///E:/temp/qgis/qgis2web_2021_11_19-17_53_43_566346/js/leaflet.js:5:3222
S.extend@file:///E:/temp/qgis/qgis2web_2021_11_19-17_53_43_566346/js/leaflet.js:5:3240
@file:///E:/temp/qgis/qgis2web_2021_11_19-17_53_43_566346/js/leaflet.pattern.js:6:34
@file:///E:/temp/qgis/qgis2web_2021_11_19-17_53_43_566346/js/leaflet.pattern.js:6:7077
````

![screenshot](https://user-images.githubusercontent.com/10866105/142671810-cbe464a6-6496-4dfc-bb01-beeb012820f4.png)

**Comment by boesiii** [comment]
Can you provide your QGIS project file and a copy of your data?  Can you explain how you prepared your choropleth map in QGIS?  Did you use a graduated symbology?

**Comment by amr66** [comment]
I found out that using an expression instead of a field for graduated was the source of the error. Turning the expression into a new field solves it!
