### ISSUE TITLE
Layer group is in wrong layer order when exporting to web map

### ISSUE THREAD

**Issue by aronsommer** [qgis2web/qgis2web#989]
QGIS 3.22.2 on macOS 11.6.2

I have a layer group with multiple gpx tracks in QGIS.
This layer group is at the top in QGIS.
But when I export to web map it is at the bottom of the layer order.

<img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/12137789/148764155-33ec5e41-dd8d-4326-a2d2-fcb7e5c0e532.png">

**Comment by boesiii** [comment]
There is probably something weird with the layer group code.  It would be better to not use layer groups.  If you wanted to keep layer groups you could try to edit the html and js code results.

**Comment by aronsommer** [comment]
My current workaround is putting the other layers also in their own layer group. The order between different layer groups is correct.

**Comment by robbitt** [comment]
> 

Yep, putting other layers in their own layer group works for me too

**Comment by andreaordonselli** [comment]
For openlayers organizing layerList in the layers.js file you can choose the order. An example here #977

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
