### ISSUE TITLE
ModuleNotFoundError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by reginaldc** [qgis2web/qgis2web#990]
I get an error when installing the latest version of qgis2web.

I solved it bij changing the file xmltodict.py

Please change:
from cStringIO import StringIO

to 

from io import StringIO

I am not familiar enough with github to do this myself

**Comment by andreaordonselli** [comment]
The current declaration of the xmltodict.py file is as follows:

```python
try: 
    from cStringIO import StringIO
except ImportError: 
    try:
        from StringIO import StringIO
    except ImportError:
        from io import StringIO
```

Therefore, if "cStringIO" or "StringIO" are not supported, "io" acts

I'm closing the issue for now, if you have problems reopen it.
Thanks for the tip.
