### ISSUE TITLE
qgis2web I cannot export a map with a 3857 raster base

### ISSUE THREAD

**Issue by macrea** [qgis2web/qgis2web#991]
I am making a test map and I would like to use a raster base I created (crs 3857).
But when exporting it gives me phyton error: FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/p3/67vdfs9j0hsg3p907dz29b680000gn/T/wOmbre3857p01643529661_tifiped_3857.'.
I also attach the log and processing messages.
I state that my geotiff weighs about 26 mb.
How can I solve?

Thank you
Massimiliano Crea
<img width="830" alt="Schermata 2022-01-30 alle 09 19 10" src="https://user-images.githubusercontent.com/13200651/151692196-b2afd918-aeaa-4ce6-9a0d-c71b339f2cba.png">
<img width="1421" alt="Schermata 2022-01-30 alle 09 05 08" src="https://user-images.githubusercontent.com/13200651/151692228-f7541471-35b0-491f-b468-76353e4fb138.png">
<img width="1421" alt="Schermata 2022-01-29 alle 16 32 21" src="https://user-images.githubusercontent.com/13200651/151692267-7cf35d7f-4103-41e2-94ec-1ff9301a47a6.png">
<img width="941" alt="Schermata 2022-01-30 alle 09 19 41" src="https://user-images.githubusercontent.com/13200651/151692363-55e42d8b-6a0f-4b00-8483-80112c81cd57.png">

**Comment by boesiii** [comment]
Are you able to provide the Qgis project file and raster image?

**Comment by macrea** [comment]
I solved it by installing qgis version 3.16.
Now I can also export geotiffs.
