### ISSUE TITLE
OSM

### ISSUE THREAD

**Issue by malupaterni** [qgis2web/qgis2web#994]
Hello, I cannot see the OSM Standard when the index is opened in my Google Chrome. It is visible from the update preview but not when the index opens. I red your previous suggestions, adding the OSM from quickmapservices but it still does not work. Thank you
<img width="531" alt="prog" src="https://user-images.githubusercontent.com/102362565/160358956-c44da359-a4b9-49c6-94c0-85b551e8410a.PNG">

**Comment by boesiii** [comment]
Add OSM as an XYZ Tiles layer (Browser -> XYZ Tiles -> OpenStreetMap) and see if that fixes your issue.

**Comment by malupaterni** [comment]
Thank you very much
