### ISSUE TITLE
Enhancement: hide emtpy fields from popups

### ISSUE THREAD

**Issue by joooeey** [qgis2web/qgis2web#995]
# Summary

It would be sweet to be able to hide empty fields from Popups. You could introduce one checkmark saying "Hide empty fields" for every layer in the Layers and Group tab.

# Use Case 1

This issue is described over on [SolveForums](https://solveforums.msomimaktaba.com/threads/solved-qgis-web-map-with-qgis2web-and-removing-empty-fields.624208/#post-624349):

> Robin Brittain Asks: QGIS - Web Map with qgis2web and Removing Empty Fields
> I'm using QGIS Version 3.22.4. I'm using the qgis2web plugin to create a web map from a layer in QGIS. It has a number of fields, some are complete with data, while others can have null values. Then with popups for points on my map, there are displayed field labels and a blank space for the null values. I would like to hide these fields when there is no data.
> 
> ![desc](https://i.stack.imgur.com/ge70Q.jpg)
> 
> I know I can turn off 'inline' labels to 'no label' for different fields when creating the map using the qgis2web plugin, but this then leaves vertical gaps between lines in the popup which I could do without.
> 
> ![desc](https://i.stack.imgur.com/mTnf1.jpg)
> 
> And I know the qgis2web.js file can also be edited, and there was a post with code to edit, but it was nearly three years ago and it doesn't work for me which I assume may be due to software version changes?

# Use Case 2

My use case is that I have a true/false flag that makes the remaining fields meaningless (they'll be empty) if the flag is set to false. This would also be solved by being able to ignore emtpy fields.

![image](https://user-images.githubusercontent.com/28426758/161005508-825a3ce8-0123-4403-9f5f-49cc848568b1.png)

![image](https://user-images.githubusercontent.com/28426758/161005599-370baeab-51b9-472e-86b7-5205d678aaee.png)

**Comment by andreaordonselli** [comment]
Released version [3.17.3](https://github.com/qgis2web/qgis2web/releases/tag/v3.17.3) which includes a fix for this issue. The update will be available soon from the QGIS plugin repository. Thanks for the tip. Please consider a small donation to support qgis2web via the button on the home page. Thank you.
