### ISSUE TITLE
non-SHP vector files error during export

### ISSUE THREAD

**Issue by arturogallia** [qgis2web/qgis2web#996]
When you try to export a map with a vector file that is not a SHP file, and this file has a field with more of 256 characters (permitted in json or geopackage file in qgis), qgis2web deletes those features with so long field filled.
This happened in qgis 3.16 and 3.24. But in Qgis 3.10 it works perfectly without this issue

**Comment by boesiii** [comment]
Are you able to share a sample of your data?

**Comment by arturogallia** [comment]
[edifici_parma.zip](https://github.com/tomchadwin/qgis2web/files/8465507/edifici_parma.zip)

**Comment by boesiii** [comment]
The fields you included are 254 characters long.  I also exported it with qgis2web and didn't find a problem.

**Comment by boesiii** [comment]
I was using Qgis 3.16.16

**Comment by Cricotopus** [comment]
I think that I have the same issue. It worked with previous versions (not sure wich old one), but it no longer work with QGIS 3.24. 

I attach a sample data with a field of  > 2000 characters. I can see it in QGIS, but I can´t see it in qgis2web.

[ZURA sin FID.zip](https://github.com/tomchadwin/qgis2web/files/11396909/ZURA.sin.FID.zip)

**Comment by andreaordonselli** [comment]
I see the features in qgis2web both for openlayers and leaflet export, the popup also works

![image](https://github.com/qgis2web/qgis2web/assets/89784373/bd9ac093-2146-49f3-ae8b-15f28050e30d)


![image](https://github.com/qgis2web/qgis2web/assets/89784373/ab63b10b-9c76-49d6-ad19-866a8f701121)
