### ISSUE TITLE
OpenLayers Opacity Problem With Hosted Map Only

### ISSUE THREAD

**Issue by jb-cloud** [qgis2web/qgis2web#997]
Seeing a strange issue with qgis2web [3.16.0] exports. After exporting with the OpenLayers option the opacity is as expected when opening the index.html. in Chrome, FF, and Safari. When the exact same files are hosted and rendered in the same browsers, the opacity is 100% for both layers. With a Leaflet export, opacity is as expected. If it matters, these are on Google Cloud Storage. I've used GCS hundreds of times without issue. I can't figure out why the hosted version would be rendering so differently.

**Comment by tomchadwin** [comment]
Do you have a link to a version which displays this behaviour?

**Comment by jb-cloud** [comment]
Thanks Tom!

I was able to figure out at least the offending layer. I was using the Wikimedia base layer via QuickMapServices. For whatever reason, the qgis2web exports hosted with Google Cloud Storage and AWS S3 aren't able to pull that basemap. So the transparency wasn't actually the culprit, it just appeared that was the problem. I still don't understand the reason that Wikimedia endpoint can be pulled locally, but not when hosted elsewhere. As far as I know, Wikimedia doesn't require an account/token for access like a Google or Mapbox does.

While it would be nice to get some insight on this behavior, this isn't a qgis2web problem. That said, using QMS to grab a basemap is a pretty common workflow so I'll go through each option they offer and post a list of what works and doesn't when hosted. Happy to put that in the wiki if that's helpful.

**Comment by tomchadwin** [comment]
The most common reason for basemapping issues is when the webmap is on HTTPS and the basemapping on HTTP, or vice-versa. Could that be the issue here?
